
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/cmd/tagcheck"


)

var tests = []testing.InternalTest{

	{"TestRunReportsTagSummaryAndSamples", _test.TestRunReportsTagSummaryAndSamples},

	{"TestRunWarnsWhenUsedTagsHaveWrongScope", _test.TestRunWarnsWhenUsedTagsHaveWrongScope},

	{"TestRunOmitsWrongScopeWarningWhenUsedTagsAreGlobal", _test.TestRunOmitsWrongScopeWarningWhenUsedTagsAreGlobal},

	{"TestRunReturnsQueryError", _test.TestRunReturnsQueryError},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/cmd/tagcheck"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

