
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/cmd/slugfix"


)

var tests = []testing.InternalTest{

	{"TestRunAppliesMigrationsAndLogsRewriteCount", _test.TestRunAppliesMigrationsAndLogsRewriteCount},

	{"TestRunRewritesLegacyDurableProjectSlugs", _test.TestRunRewritesLegacyDurableProjectSlugs},

	{"TestRunReturnsMigrateErrorForCanceledContext", _test.TestRunReturnsMigrateErrorForCanceledContext},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/cmd/slugfix"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

