
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/wall"


)

var tests = []testing.InternalTest{

	{"TestResolvedRESTTargetPreservesProjectID", _test.TestResolvedRESTTargetPreservesProjectID},

	{"TestNoteCommandsPreserveRawValuesAndPresence", _test.TestNoteCommandsPreserveRawValuesAndPresence},

	{"TestReplaceWallCommandPreservesNotePresenceOrderAndValues", _test.TestReplaceWallCommandPreservesNotePresenceOrderAndValues},

	{"TestEdgeAndTransientContractsPreserveRawValues", _test.TestEdgeAndTransientContractsPreserveRawValues},

	{"TestRefreshReasonsMatchCompatibilityValues", _test.TestRefreshReasonsMatchCompatibilityValues},

	{"TestRESTEdgePreparationAuthorization", _test.TestRESTEdgePreparationAuthorization},

	{"TestPreparedRESTEdgeBindsDistinctContextsActorAndProject", _test.TestPreparedRESTEdgeBindsDistinctContextsActorAndProject},

	{"TestPreparedRESTEdgeCreatePreservesRawEndpointsAndPassesResult", _test.TestPreparedRESTEdgeCreatePreservesRawEndpointsAndPassesResult},

	{"TestPreparedRESTEdgeDuplicateNoOpStillPublishes", _test.TestPreparedRESTEdgeDuplicateNoOpStillPublishes},

	{"TestPreparedRESTEdgeDeletePreservesRawID", _test.TestPreparedRESTEdgeDeletePreservesRawID},

	{"TestPreparedRESTEdgeStoreFailuresReturnZeroAndSuppressRefresh", _test.TestPreparedRESTEdgeStoreFailuresReturnZeroAndSuppressRefresh},

	{"TestPreparedRESTEdgeAtMostOnceAcrossFamilyMethods", _test.TestPreparedRESTEdgeAtMostOnceAcrossFamilyMethods},

	{"TestPreparedRESTEdgeConcurrentExecutionStartsOneMethod", _test.TestPreparedRESTEdgeConcurrentExecutionStartsOneMethod},

	{"TestPreparedRESTEdgeConcurrentStoreFailureSuppressesRefresh", _test.TestPreparedRESTEdgeConcurrentStoreFailureSuppressesRefresh},

	{"TestPreparedRESTEdgeCanceledMutationContext", _test.TestPreparedRESTEdgeCanceledMutationContext},

	{"TestRESTWriterPreparationAuthorization", _test.TestRESTWriterPreparationAuthorization},

	{"TestRESTWriterPreparationBindsDistinctContextsActorAndProject", _test.TestRESTWriterPreparationBindsDistinctContextsActorAndProject},

	{"TestPreparedRESTNoteCreate", _test.TestPreparedRESTNoteCreate},

	{"TestPreparedRESTNotePatchPreservesOptionalPresence", _test.TestPreparedRESTNotePatchPreservesOptionalPresence},

	{"TestPreparedRESTNotePatchDefensivelyCopiesValuesAndPassesResult", _test.TestPreparedRESTNotePatchDefensivelyCopiesValuesAndPassesResult},

	{"TestPreparedRESTNotePatchFailureReturnsZeroAndSuppressesRefresh", _test.TestPreparedRESTNotePatchFailureReturnsZeroAndSuppressesRefresh},

	{"TestPreparedRESTNoteDelete", _test.TestPreparedRESTNoteDelete},

	{"TestPreparedRESTNoteAtMostOnceAcrossFamilyMethods", _test.TestPreparedRESTNoteAtMostOnceAcrossFamilyMethods},

	{"TestPreparedRESTNoteConcurrentExecutionStartsOneMethod", _test.TestPreparedRESTNoteConcurrentExecutionStartsOneMethod},

	{"TestPreparedRESTNoteConcurrentStoreFailureSuppressesRefresh", _test.TestPreparedRESTNoteConcurrentStoreFailureSuppressesRefresh},

	{"TestPreparedRESTNoteCanceledMutationContext", _test.TestPreparedRESTNoteCanceledMutationContext},

	{"TestRESTReplacementPreparationAuthorization", _test.TestRESTReplacementPreparationAuthorization},

	{"TestPreparedRESTReplacementBindsDistinctContextsActorAndProject", _test.TestPreparedRESTReplacementBindsDistinctContextsActorAndProject},

	{"TestPreparedRESTReplacementPreservesNotePresenceOrderValuesAndIsolation", _test.TestPreparedRESTReplacementPreservesNotePresenceOrderValuesAndIsolation},

	{"TestPreparedRESTReplacementStoreFailureReturnsZeroAndSuppressesRefresh", _test.TestPreparedRESTReplacementStoreFailureReturnsZeroAndSuppressesRefresh},

	{"TestPreparedRESTReplacementAtMostOnceAfterSuccessAndFailure", _test.TestPreparedRESTReplacementAtMostOnceAfterSuccessAndFailure},

	{"TestPreparedRESTReplacementConcurrentExecutionStartsOnce", _test.TestPreparedRESTReplacementConcurrentExecutionStartsOnce},

	{"TestPreparedRESTReplacementConcurrentStoreFailureSuppressesRefresh", _test.TestPreparedRESTReplacementConcurrentStoreFailureSuppressesRefresh},

	{"TestPreparedRESTReplacementCanceledMutationContext", _test.TestPreparedRESTReplacementCanceledMutationContext},

	{"TestRESTTransientPreparationAuthorization", _test.TestRESTTransientPreparationAuthorization},

	{"TestPreparedRESTTransientBindsDistinctContextsActorAndProject", _test.TestPreparedRESTTransientBindsDistinctContextsActorAndProject},

	{"TestPreparedRESTTransientPreservesRawCommandAndBuildsExactEvent", _test.TestPreparedRESTTransientPreservesRawCommandAndBuildsExactEvent},

	{"TestPreparedRESTTransientPublisherErrorPassesThrough", _test.TestPreparedRESTTransientPublisherErrorPassesThrough},

	{"TestPreparedRESTTransientAtMostOnceAfterSuccessAndFailure", _test.TestPreparedRESTTransientAtMostOnceAfterSuccessAndFailure},

	{"TestPreparedRESTTransientConcurrentExecutionPublishesOnce", _test.TestPreparedRESTTransientConcurrentExecutionPublishesOnce},

	{"TestPreparedRESTTransientConcurrentPublisherFailureAttemptsOnce", _test.TestPreparedRESTTransientConcurrentPublisherFailureAttemptsOnce},

	{"TestPreparedRESTTransientCanceledEffectContext", _test.TestPreparedRESTTransientCanceledEffectContext},

	{"TestPreparedRESTTransientCanceledMutationContextStillPublishes", _test.TestPreparedRESTTransientCanceledMutationContextStillPublishes},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/wall"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

