
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/oidc"


)

var tests = []testing.InternalTest{

	{"TestDiscoverProvider", _test.TestDiscoverProvider},

	{"TestSanitizeReturnTo", _test.TestSanitizeReturnTo},

	{"TestNormalizeIssuer", _test.TestNormalizeIssuer},

	{"TestIsEmailVerified", _test.TestIsEmailVerified},

	{"TestStateStoreSingleUse", _test.TestStateStoreSingleUse},

	{"TestStateStoreExpiry", _test.TestStateStoreExpiry},

	{"TestStateStoreUnknownKey", _test.TestStateStoreUnknownKey},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

	{"FuzzSanitizeReturnTo", _test.FuzzSanitizeReturnTo},

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/oidc"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

