
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/trelloimport"


)

var tests = []testing.InternalTest{

	{"TestBuildImportBundle_MinimalBoard", _test.TestBuildImportBundle_MinimalBoard},

	{"TestBuildImportBundle_OneOpenListSynthesizesDoneColumn", _test.TestBuildImportBundle_OneOpenListSynthesizesDoneColumn},

	{"TestBuildImportBundle_CardInClosedExistingListImportsIntoDoneColumn", _test.TestBuildImportBundle_CardInClosedExistingListImportsIntoDoneColumn},

	{"TestBuildImportBundle_CardReferencingMissingListIsHardError", _test.TestBuildImportBundle_CardReferencingMissingListIsHardError},

	{"TestBuildImportBundle_FailsWhenTooManyOpenLists", _test.TestBuildImportBundle_FailsWhenTooManyOpenLists},

	{"TestBuildImportBundle_ComprehensiveFixture", _test.TestBuildImportBundle_ComprehensiveFixture},

	{"TestBuildImportBundle_MalformedJSON", _test.TestBuildImportBundle_MalformedJSON},

	{"TestTrelloLabelColorHex", _test.TestTrelloLabelColorHex},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/trelloimport"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

