
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/calendar"


)

var tests = []testing.InternalTest{

	{"TestStaleRefreshDoesNotOverwriteHostKindAfterURLChange", _test.TestStaleRefreshDoesNotOverwriteHostKindAfterURLChange},

	{"TestMigratedSourceBackfillPublishesOnNotModified", _test.TestMigratedSourceBackfillPublishesOnNotModified},

	{"TestReadAgendaCopiesPersistedHostKind", _test.TestReadAgendaCopiesPersistedHostKind},

	{"TestReadAgendaDoesNotFetch", _test.TestReadAgendaDoesNotFetch},

	{"TestReadAgendaDisabledOmitsEvents", _test.TestReadAgendaDisabledOmitsEvents},

	{"TestMaybeRefreshSkipsFreshSnapshot", _test.TestMaybeRefreshSkipsFreshSnapshot},

	{"TestRefreshPublishesOnceWhenEventsChange", _test.TestRefreshPublishesOnceWhenEventsChange},

	{"TestRefreshNotModifiedDoesNotPublish", _test.TestRefreshNotModifiedDoesNotPublish},

	{"TestUnknownTimezoneKeepsLastGoodAndDoesNotPublish", _test.TestUnknownTimezoneKeepsLastGoodAndDoesNotPublish},

	{"TestTooManyOccurrencesKeepsLastGoodAndDoesNotPublish", _test.TestTooManyOccurrencesKeepsLastGoodAndDoesNotPublish},

	{"TestFirstFetchFailureReturnsEmptyStale", _test.TestFirstFetchFailureReturnsEmptyStale},

	{"TestSanitizeCalendarErrorNeverIncludesURL", _test.TestSanitizeCalendarErrorNeverIncludesURL},

	{"TestReadAgendaSpringForwardExcludesNextCivilMorning", _test.TestReadAgendaSpringForwardExcludesNextCivilMorning},

	{"TestReadAgendaFallBackIncludesLateEvening", _test.TestReadAgendaFallBackIncludesLateEvening},

	{"TestReadAgendaAllDaySpanningDSTSpringForward", _test.TestReadAgendaAllDaySpanningDSTSpringForward},

	{"TestExpansionWindowUsesCivilDaysAroundDST", _test.TestExpansionWindowUsesCivilDaysAroundDST},

	{"TestRefreshSourceCoalescesInFlightFetch", _test.TestRefreshSourceCoalescesInFlightFetch},

	{"TestReadAgendaMarksAgedSnapshotStale", _test.TestReadAgendaMarksAgedSnapshotStale},

	{"TestRefreshNotModifiedWithoutSnapshotFails", _test.TestRefreshNotModifiedWithoutSnapshotFails},

	{"TestInFlightURLRefreshDoesNotResurrectInvalidatedSnapshot", _test.TestInFlightURLRefreshDoesNotResurrectInvalidatedSnapshot},

	{"TestInFlightTimezoneRefreshDoesNotResurrectInvalidatedSnapshot", _test.TestInFlightTimezoneRefreshDoesNotResurrectInvalidatedSnapshot},

	{"TestObsoleteFailingRefreshDoesNotRecreateErrorSnapshot", _test.TestObsoleteFailingRefreshDoesNotRecreateErrorSnapshot},

	{"TestURLChangeInvalidatesCachedSnapshotAndValidators", _test.TestURLChangeInvalidatesCachedSnapshotAndValidators},

	{"TestRenameDoesNotInvalidateSnapshot", _test.TestRenameDoesNotInvalidateSnapshot},

	{"TestTimezoneChangeInvalidatesSnapshotAndReexpandsFloating", _test.TestTimezoneChangeInvalidatesSnapshotAndReexpandsFloating},

	{"TestAgendaEnabledOnlyDoesNotInvalidateSnapshot", _test.TestAgendaEnabledOnlyDoesNotInvalidateSnapshot},

	{"TestAgendaColorOnlyDoesNotInvalidateSnapshot", _test.TestAgendaColorOnlyDoesNotInvalidateSnapshot},

	{"TestAgendaTitleOnlyDoesNotInvalidateSnapshot", _test.TestAgendaTitleOnlyDoesNotInvalidateSnapshot},

	{"TestAgendaTitleAndColorDoNotInvalidateSnapshot", _test.TestAgendaTitleAndColorDoNotInvalidateSnapshot},

	{"TestHTTPFetcherAllowsLoopbackHTTPWhenConfigured", _test.TestHTTPFetcherAllowsLoopbackHTTPWhenConfigured},

	{"TestHTTPFetcherNotModified", _test.TestHTTPFetcherNotModified},

	{"TestHTTPFetcherRejectsServerError", _test.TestHTTPFetcherRejectsServerError},

	{"TestHTTPFetcherEnforcesSizeCap", _test.TestHTTPFetcherEnforcesSizeCap},

	{"TestHTTPFetcherAcceptsFeedAboveOldTwoMiBCeiling", _test.TestHTTPFetcherAcceptsFeedAboveOldTwoMiBCeiling},

	{"TestHTTPFetcherRejectsAboveNewCeiling", _test.TestHTTPFetcherRejectsAboveNewCeiling},

	{"TestHTTPFetcherTimeout", _test.TestHTTPFetcherTimeout},

	{"TestHTTPFetcherBlocksLoopbackWithoutAllow", _test.TestHTTPFetcherBlocksLoopbackWithoutAllow},

	{"TestHTTPFetcherBlocksPrivateResolution", _test.TestHTTPFetcherBlocksPrivateResolution},

	{"TestHTTPFetcherBlocksCGNATAndAllowsPublic", _test.TestHTTPFetcherBlocksCGNATAndAllowsPublic},

	{"TestHTTPFetcherBlocksRedirectToHTTP", _test.TestHTTPFetcherBlocksRedirectToHTTP},

	{"TestHTTPFetcherErrorDoesNotIncludeURL", _test.TestHTTPFetcherErrorDoesNotIncludeURL},

	{"TestCanonicalCalendarURLRejectsUserinfoAndNonHTTPS", _test.TestCanonicalCalendarURLRejectsUserinfoAndNonHTTPS},

	{"TestURLPreviewOmitsPathAndToken", _test.TestURLPreviewOmitsPathAndToken},

	{"TestPrepareRejectsTemporaryBoard", _test.TestPrepareRejectsTemporaryBoard},

	{"TestCreateRejectsMissingEncryptionKey", _test.TestCreateRejectsMissingEncryptionKey},

	{"TestCreateEnforcesSourceCapAndRedactsPreview", _test.TestCreateEnforcesSourceCapAndRedactsPreview},

	{"TestPatchSettingsValidatesTimezone", _test.TestPatchSettingsValidatesTimezone},

	{"TestPatchSettingsPersistsTitleWithoutChangingTimezone", _test.TestPatchSettingsPersistsTitleWithoutChangingTimezone},

	{"TestPatchSettingsPersistsColorWithoutChangingTitle", _test.TestPatchSettingsPersistsColorWithoutChangingTitle},

	{"TestCreateStoresHostKindAndNameOnlyUpdateDoesNotRecompute", _test.TestCreateStoresHostKindAndNameOnlyUpdateDoesNotRecompute},

	{"TestCalendarHostKindExactHostsAndSpoofs", _test.TestCalendarHostKindExactHostsAndSpoofs},

	{"TestCalendarHostKindUsesCanonicalHostCasing", _test.TestCalendarHostKindUsesCanonicalHostCasing},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/calendar"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

