
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/project"


)

var tests = []testing.InternalTest{

	{"TestMCPDurableCreationCallsOnceAndSynthesizesMaintainer", _test.TestMCPDurableCreationCallsOnceAndSynthesizesMaintainer},

	{"TestMCPDurableCreationReturnsStoreErrorUnchanged", _test.TestMCPDurableCreationReturnsStoreErrorUnchanged},

	{"TestMCPDeletionPreservesManagedDeleteSequenceAndPreReadProjection", _test.TestMCPDeletionPreservesManagedDeleteSequenceAndPreReadProjection},

	{"TestMCPDeletionStopsAtPreparationAndMutationFailures", _test.TestMCPDeletionStopsAtPreparationAndMutationFailures},

	{"TestMCPManagedProjectPreparationPreservesSequencing", _test.TestMCPManagedProjectPreparationPreservesSequencing},

	{"TestMCPManagedProjectPreparationClonesContextAndPreservesRoleRules", _test.TestMCPManagedProjectPreparationClonesContextAndPreservesRoleRules},

	{"TestMCPUpdatePreservesAtomicPatchAndPostReadSequence", _test.TestMCPUpdatePreservesAtomicPatchAndPostReadSequence},

	{"TestMCPUpdatePreservesPartialSuccessFailuresWithoutRetry", _test.TestMCPUpdatePreservesPartialSuccessFailuresWithoutRetry},

	{"TestMCPUpdatePreservesPatchFieldPresence", _test.TestMCPUpdatePreservesPatchFieldPresence},

	{"TestCreationCommandsPreserveRawValuesAndWorkflowPresence", _test.TestCreationCommandsPreserveRawValuesAndWorkflowPresence},

	{"TestUpdateCommandsPreserveTargetsPresenceAndValues", _test.TestUpdateCommandsPreserveTargetsPresenceAndValues},

	{"TestDeletionAndClaimCommandsKeepLifecycleFamiliesExplicit", _test.TestDeletionAndClaimCommandsKeepLifecycleFamiliesExplicit},

	{"TestRESTClaimUsesConditionalMutationAsSoleAuthorityThenPublishes", _test.TestRESTClaimUsesConditionalMutationAsSoleAuthorityThenPublishes},

	{"TestRESTClaimReturnsConditionalMutationErrorWithoutPublicationOrRetry", _test.TestRESTClaimReturnsConditionalMutationErrorWithoutPublicationOrRetry},

	{"TestRESTClaimAllowsNilPublisher", _test.TestRESTClaimAllowsNilPublisher},

	{"TestRESTDurableCreationPreservesWorkflowPresenceAndIsolation", _test.TestRESTDurableCreationPreservesWorkflowPresenceAndIsolation},

	{"TestRESTDurableCreationReturnsStoreErrorUnchanged", _test.TestRESTDurableCreationReturnsStoreErrorUnchanged},

	{"TestAnonymousBoardCreationCallsOnceWithoutCompensation", _test.TestAnonymousBoardCreationCallsOnceWithoutCompensation},

	{"TestRESTDeletionDeletesExactlyOnceThenPublishesSnapshot", _test.TestRESTDeletionDeletesExactlyOnceThenPublishesSnapshot},

	{"TestRESTDeletionReturnsMutationErrorWithoutPublication", _test.TestRESTDeletionReturnsMutationErrorWithoutPublication},

	{"TestRESTDeletionAllowsNilPublisher", _test.TestRESTDeletionAllowsNilPublisher},

	{"TestRESTUpdatePreparationPreservesModeSpecificTargetOrdering", _test.TestRESTUpdatePreparationPreservesModeSpecificTargetOrdering},

	{"TestRESTUpdateExecutionSequencesAndPublication", _test.TestRESTUpdateExecutionSequencesAndPublication},

	{"TestRESTUpdatePreservesMissingActorAndPartialFailureContracts", _test.TestRESTUpdatePreservesMissingActorAndPartialFailureContracts},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/project"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

