
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/mcp"


	_xtest "scrumboy/internal/mcp_test"

)

var tests = []testing.InternalTest{

	{"TestParseAdminUpdatableSystemRole_admin", _test.TestParseAdminUpdatableSystemRole_admin},

	{"TestParseAdminUpdatableSystemRole_user", _test.TestParseAdminUpdatableSystemRole_user},

	{"TestParseAdminUpdatableSystemRole_ownerRejected", _test.TestParseAdminUpdatableSystemRole_ownerRejected},

	{"TestParseAdminUpdatableSystemRole_unknownRejected", _test.TestParseAdminUpdatableSystemRole_unknownRejected},

	{"TestRequesterHasAnySystemRole", _test.TestRequesterHasAnySystemRole},

	{"TestJSONRPCAuthenticationStoreFailures", _test.TestJSONRPCAuthenticationStoreFailures},

	{"TestBoardGetContract_CapabilityAndAuthenticationGates", _test.TestBoardGetContract_CapabilityAndAuthenticationGates},

	{"TestBoardGetContract_DurableAccessAndNotFoundMasking", _test.TestBoardGetContract_DurableAccessAndNotFoundMasking},

	{"TestBoardGetContract_ExpiringBoardAccess", _test.TestBoardGetContract_ExpiringBoardAccess},

	{"TestBoardGetContract_AccessErrorMappingExposesStoreDetail", _test.TestBoardGetContract_AccessErrorMappingExposesStoreDetail},

	{"TestBoardGetContract_DurableReadOmitsActivityRefresh", _test.TestBoardGetContract_DurableReadOmitsActivityRefresh},

	{"TestBoardGetContract_ExpiringReadRefreshesActivityLast", _test.TestBoardGetContract_ExpiringReadRefreshesActivityLast},

	{"TestBoardGetContract_PriorFailurePreventsActivityRefresh", _test.TestBoardGetContract_PriorFailurePreventsActivityRefresh},

	{"TestBoardGetContract_ActivityFailureIsBestEffortAndReturnsProjection", _test.TestBoardGetContract_ActivityFailureIsBestEffortAndReturnsProjection},

	{"TestBoardGetContract_ActivityFailureIsBestEffortAcrossTransports", _test.TestBoardGetContract_ActivityFailureIsBestEffortAcrossTransports},

	{"TestBoardGetContract_LimitDefaultsAndBounds", _test.TestBoardGetContract_LimitDefaultsAndBounds},

	{"TestBoardGetContract_FirstPageCursorSentinels", _test.TestBoardGetContract_FirstPageCursorSentinels},

	{"TestBoardGetContract_PerColumnCursorIndependence", _test.TestBoardGetContract_PerColumnCursorIndependence},

	{"TestBoardGetContract_SuppliedCursorOverridesSortSentinel", _test.TestBoardGetContract_SuppliedCursorOverridesSortSentinel},

	{"TestBoardGetContract_EmptyCursorTokensUseFirstPageBoundary", _test.TestBoardGetContract_EmptyCursorTokensUseFirstPageBoundary},

	{"TestBoardGetContract_MalformedCursorVariants", _test.TestBoardGetContract_MalformedCursorVariants},

	{"TestBoardGetContract_OpaqueOutputCursorConstruction", _test.TestBoardGetContract_OpaqueOutputCursorConstruction},

	{"TestBoardGetContract_NoNextCursorWithoutReturnedContinuationRow", _test.TestBoardGetContract_NoNextCursorWithoutReturnedContinuationRow},

	{"TestBoardGetContract_SuccessfulStorePortCardinality", _test.TestBoardGetContract_SuccessfulStorePortCardinality},

	{"TestBoardGetContract_ColumnKeyPaginationContinuesSelectedLane", _test.TestBoardGetContract_ColumnKeyPaginationContinuesSelectedLane},

	{"TestBoardGetContract_WorkflowProjectionOrderAndShape", _test.TestBoardGetContract_WorkflowProjectionOrderAndShape},

	{"TestBoardGetContract_RecordingStoreDelegatesWithoutChangingResult", _test.TestBoardGetContract_RecordingStoreDelegatesWithoutChangingResult},

	{"TestBoardGetContract_FilterForwardingAndCardinality", _test.TestBoardGetContract_FilterForwardingAndCardinality},

	{"TestBoardGetContract_SprintSemantics", _test.TestBoardGetContract_SprintSemantics},

	{"TestBoardGetContract_SlugLookupAndCanonicalProjection", _test.TestBoardGetContract_SlugLookupAndCanonicalProjection},

	{"TestBoardGetContract_PortFailuresShortCircuit", _test.TestBoardGetContract_PortFailuresShortCircuit},

	{"TestBoardGetContract_ContextIdentityAcrossAccessAndDataPorts", _test.TestBoardGetContract_ContextIdentityAcrossAccessAndDataPorts},

	{"TestBoardGetContract_TargetStatePrecedenceMatrix", _test.TestBoardGetContract_TargetStatePrecedenceMatrix},

	{"TestBoardGetContract_ValidationBeforeAccess", _test.TestBoardGetContract_ValidationBeforeAccess},

	{"TestBoardGetContract_MalformedInputShape", _test.TestBoardGetContract_MalformedInputShape},

	{"TestBoardGetContract_AccessPrecedesSprintAndCursorValidation", _test.TestBoardGetContract_AccessPrecedesSprintAndCursorValidation},

	{"TestBoardGetContract_CursorKeyValidationFollowsWorkflow", _test.TestBoardGetContract_CursorKeyValidationFollowsWorkflow},

	{"TestBoardGetContract_UnknownColumnKeyFailsBeforeAnyLaneQuery", _test.TestBoardGetContract_UnknownColumnKeyFailsBeforeAnyLaneQuery},

	{"TestBoardGetContract_AgendaColumnKeyFailsBeforeAnyLaneQuery", _test.TestBoardGetContract_AgendaColumnKeyFailsBeforeAnyLaneQuery},

	{"TestBoardGetContract_ColumnKeyScopesLaneQueriesToOneColumn", _test.TestBoardGetContract_ColumnKeyScopesLaneQueriesToOneColumn},

	{"TestBoardGetContract_ColumnKeyIgnoresMalformedCursorForOtherValidColumn", _test.TestBoardGetContract_ColumnKeyIgnoresMalformedCursorForOtherValidColumn},

	{"TestBoardGetContract_UnknownCursorColumnStillRejectedWithColumnKey", _test.TestBoardGetContract_UnknownCursorColumnStillRejectedWithColumnKey},

	{"TestBoardGetContract_MalformedLaterCursorPreservesPartialReadBoundary", _test.TestBoardGetContract_MalformedLaterCursorPreservesPartialReadBoundary},

	{"TestBoardGetContract_NonEmptyInvalidAndMissingSlugContracts", _test.TestBoardGetContract_NonEmptyInvalidAndMissingSlugContracts},

	{"TestNormalizeDashboardTodosLimit_nilDefaultsTo20", _test.TestNormalizeDashboardTodosLimit_nilDefaultsTo20},

	{"TestNormalizeDashboardTodosLimit_validValue", _test.TestNormalizeDashboardTodosLimit_validValue},

	{"TestNormalizeDashboardTodosLimit_zeroRejected", _test.TestNormalizeDashboardTodosLimit_zeroRejected},

	{"TestNormalizeDashboardTodosLimit_tooLargeRejected", _test.TestNormalizeDashboardTodosLimit_tooLargeRejected},

	{"TestClientErrorDetailsAllowlist", _test.TestClientErrorDetailsAllowlist},

	{"TestLegacyInternalErrorSanitizesClientAndLogsCause", _test.TestLegacyInternalErrorSanitizesClientAndLogsCause},

	{"TestJSONRPCInternalErrorSanitizesStructuredContent", _test.TestJSONRPCInternalErrorSanitizesStructuredContent},

	{"TestJSONRPCBoardGetResultComposition", _test.TestJSONRPCBoardGetResultComposition},

	{"TestJSONRPCBoardGetResultCompositionSupportsDottedAlias", _test.TestJSONRPCBoardGetResultCompositionSupportsDottedAlias},

	{"TestJSONRPCToolResultCompositionAddsApprovedNonBoardMetadata", _test.TestJSONRPCToolResultCompositionAddsApprovedNonBoardMetadata},

	{"TestJSONRPCToolResultCompositionLeavesUnapprovedToolsUnchanged", _test.TestJSONRPCToolResultCompositionLeavesUnapprovedToolsUnchanged},

	{"TestJSONRPCToolResultCompositionPreservesDataOnCollision", _test.TestJSONRPCToolResultCompositionPreservesDataOnCollision},

	{"TestJSONRPCBoardGetResultCompositionHandlesMissingOrUnexpectedData", _test.TestJSONRPCBoardGetResultCompositionHandlesMissingOrUnexpectedData},

	{"TestJSONRPCRequestOnlyMethodsRequireID", _test.TestJSONRPCRequestOnlyMethodsRequireID},

	{"TestParseJSONRPCMessage_NullIDPreservedOnStructuralError", _test.TestParseJSONRPCMessage_NullIDPreservedOnStructuralError},

	{"TestParseJSONRPCMessage_InvalidIDHasNoRecoverableID", _test.TestParseJSONRPCMessage_InvalidIDHasNoRecoverableID},

	{"TestParseJSONRPCMessage_ParamsNullRejected", _test.TestParseJSONRPCMessage_ParamsNullRejected},

	{"TestNormalizeProjectMemberRoleForMCP", _test.TestNormalizeProjectMemberRoleForMCP},

	{"TestMapMembershipMutationPrepareError", _test.TestMapMembershipMutationPrepareError},

	{"TestMapMembershipAddError", _test.TestMapMembershipAddError},

	{"TestMapMembershipUpdateRoleError", _test.TestMapMembershipUpdateRoleError},

	{"TestMapMembershipRemoveError", _test.TestMapMembershipRemoveError},

	{"TestBurndownPointsToItems_mapsFields", _test.TestBurndownPointsToItems_mapsFields},

	{"TestRealBurndownPointsToItems_mapsFields", _test.TestRealBurndownPointsToItems_mapsFields},

	{"TestProjectLifecycleMCPMigrationNewComposesSeparateServices", _test.TestProjectLifecycleMCPMigrationNewComposesSeparateServices},

	{"TestProjectLifecycleMCPMigrationCreationPreservesRawNameBoundary", _test.TestProjectLifecycleMCPMigrationCreationPreservesRawNameBoundary},

	{"TestProjectLifecycleMCPMigrationUpdateDelegatesOneExactSequence", _test.TestProjectLifecycleMCPMigrationUpdateDelegatesOneExactSequence},

	{"TestProjectLifecycleMCPMigrationDeletionDelegatesOneExactSequence", _test.TestProjectLifecycleMCPMigrationDeletionDelegatesOneExactSequence},

	{"TestMapProjectApplicationErrorOwnsOnlyActorSentinel", _test.TestMapProjectApplicationErrorOwnsOnlyActorSentinel},

	{"TestParseProjectUpdatePatch_name", _test.TestParseProjectUpdatePatch_name},

	{"TestParseProjectUpdatePatch_defaultSprintWeeks", _test.TestParseProjectUpdatePatch_defaultSprintWeeks},

	{"TestParseProjectUpdatePatch_nameNull_rejected", _test.TestParseProjectUpdatePatch_nameNull_rejected},

	{"TestParseProjectUpdatePatch_unsupportedField", _test.TestParseProjectUpdatePatch_unsupportedField},

	{"TestParseProjectUpdatePatch_empty", _test.TestParseProjectUpdatePatch_empty},

	{"TestParseProjectUpdatePatch_invalidType", _test.TestParseProjectUpdatePatch_invalidType},

	{"TestParseProjectUpdatePatch_invalidWeeksValue", _test.TestParseProjectUpdatePatch_invalidWeeksValue},

	{"TestMapSprintDefinitionPrepareErrorSentinels", _test.TestMapSprintDefinitionPrepareErrorSentinels},

	{"TestMapSprintDefinitionPrepareErrorDelegatesRawErrors", _test.TestMapSprintDefinitionPrepareErrorDelegatesRawErrors},

	{"TestMapSprintLifecyclePrepareErrorSentinels", _test.TestMapSprintLifecyclePrepareErrorSentinels},

	{"TestMapSprintLifecyclePrepareErrorDelegatesSharedAndRawErrors", _test.TestMapSprintLifecyclePrepareErrorDelegatesSharedAndRawErrors},

	{"TestMapTagColorPrepareError", _test.TestMapTagColorPrepareError},

	{"TestMapTagColorUpdateError", _test.TestMapTagColorUpdateError},

	{"TestMapTagDeletionPrepareError", _test.TestMapTagDeletionPrepareError},

	{"TestMapTagDeletionExecuteError", _test.TestMapTagDeletionExecuteError},

	{"TestMapMCPCreateErrorPreservesLocalReferenceDetails", _test.TestMapMCPCreateErrorPreservesLocalReferenceDetails},

	{"TestMapMCPCreateErrorPreservesPrivilegedAuthorizationMapping", _test.TestMapMCPCreateErrorPreservesPrivilegedAuthorizationMapping},

	{"TestMapTodoLinkMutationPrepareErrorPreservesAccessAndSourcePolicy", _test.TestMapTodoLinkMutationPrepareErrorPreservesAccessAndSourcePolicy},

	{"TestMapTodoLinkMutationOperationErrorPreservesMutationAndProjectionPolicy", _test.TestMapTodoLinkMutationOperationErrorPreservesMutationAndProjectionPolicy},

	{"TestMapTodoLinkMutationProjectionErrorUsesCauseAndSanitizesClient", _test.TestMapTodoLinkMutationProjectionErrorUsesCauseAndSanitizesClient},

	{"TestMapTodoLinkMutationClassifiedErrorWithoutCauseIsInternal", _test.TestMapTodoLinkMutationClassifiedErrorWithoutCauseIsInternal},

	{"TestMapMCPMoveErrorPreservesAuthorizationSourceContract", _test.TestMapMCPMoveErrorPreservesAuthorizationSourceContract},

	{"TestTodoToItemForProjectSuppressesDormantSprintAssignment", _test.TestTodoToItemForProjectSuppressesDormantSprintAssignment},

	{"TestBuildUpdatePatch_patchSprintId_omitted", _test.TestBuildUpdatePatch_patchSprintId_omitted},

	{"TestBuildUpdatePatch_patchSprintId_assigns", _test.TestBuildUpdatePatch_patchSprintId_assigns},

	{"TestBuildUpdatePatch_patchSprintId_null_clears", _test.TestBuildUpdatePatch_patchSprintId_null_clears},

	{"TestBuildUpdatePatch_patchSprintId_invalidJSON", _test.TestBuildUpdatePatch_patchSprintId_invalidJSON},

	{"TestBuildUpdatePatch_mapsAllSupportedFields", _test.TestBuildUpdatePatch_mapsAllSupportedFields},

	{"TestBuildUpdatePatch_mapsNullableClearsAndEmptyPatch", _test.TestBuildUpdatePatch_mapsNullableClearsAndEmptyPatch},

	{"TestBuildUpdatePatch_rejectsNullReplacementAndUnsupportedFields", _test.TestBuildUpdatePatch_rejectsNullReplacementAndUnsupportedFields},

	{"TestImplementedTools_UniqueAndClaudeCompatible", _test.TestImplementedTools_UniqueAndClaudeCompatible},

	{"TestToolCatalog_NamesUniqueAndClaudeCompatible", _test.TestToolCatalog_NamesUniqueAndClaudeCompatible},

	{"TestToolCatalog_BoardGetAssigneeIsDocumentedStringUnion", _test.TestToolCatalog_BoardGetAssigneeIsDocumentedStringUnion},

	{"TestToolCatalog_BoardGetPriorityAdvertisesRuntimeContract", _test.TestToolCatalog_BoardGetPriorityAdvertisesRuntimeContract},

	{"TestToolCatalog_BoardGetSprintIDAdvertisesStoredIdentity", _test.TestToolCatalog_BoardGetSprintIDAdvertisesStoredIdentity},

	{"TestToolCatalog_BoardGetSortAdvertisesRuntimeContract", _test.TestToolCatalog_BoardGetSortAdvertisesRuntimeContract},

	{"TestLegacyToolAliases_AreDottedAndDisjointFromCatalog", _test.TestLegacyToolAliases_AreDottedAndDisjointFromCatalog},

	{"TestLegacyToolAliases_CoverRenamedToolSetAndUniqueTargets", _test.TestLegacyToolAliases_CoverRenamedToolSetAndUniqueTargets},

	{"TestMapUserAdminDeletionPrepareError", _test.TestMapUserAdminDeletionPrepareError},

	{"TestUserAdminMCPDeletionMigrationNewComposesDeletionService", _test.TestUserAdminMCPDeletionMigrationNewComposesDeletionService},

	{"TestUserAdminMCPDeletionMigrationValidationPreventsServiceEntry", _test.TestUserAdminMCPDeletionMigrationValidationPreventsServiceEntry},

	{"TestUserAdminMCPDeletionMigrationDelegatesOneExactSequence", _test.TestUserAdminMCPDeletionMigrationDelegatesOneExactSequence},

	{"TestUserAdminMCPDeletionMigrationPreservesStageMappings", _test.TestUserAdminMCPDeletionMigrationPreservesStageMappings},

	{"TestUserAdminMCPDeletionMigrationPreservesSelfAndTargetOrdering", _test.TestUserAdminMCPDeletionMigrationPreservesSelfAndTargetOrdering},

	{"TestUserAdminMCPDeletionMigrationMutationErrorsAreNotRetried", _test.TestUserAdminMCPDeletionMigrationMutationErrorsAreNotRetried},

	{"TestMapUserAdminRolePrepareError", _test.TestMapUserAdminRolePrepareError},

	{"TestMapUserAdminRoleUpdateErrorUsesPrivilegedMapperForMutation", _test.TestMapUserAdminRoleUpdateErrorUsesPrivilegedMapperForMutation},

	{"TestMapUserAdminRoleUpdateErrorUnwrapsRealProjectionCauseBeforeMapping", _test.TestMapUserAdminRoleUpdateErrorUnwrapsRealProjectionCauseBeforeMapping},

	{"TestUserAdminMCPRoleMigrationNewComposesRoleService", _test.TestUserAdminMCPRoleMigrationNewComposesRoleService},

	{"TestUserAdminMCPRoleMigrationDelegatesOneExactSequence", _test.TestUserAdminMCPRoleMigrationDelegatesOneExactSequence},

	{"TestUserAdminMCPRoleMigrationValidationPreventsServiceEntry", _test.TestUserAdminMCPRoleMigrationValidationPreventsServiceEntry},

	{"TestUserAdminMCPRoleMigrationPreservesStageMappings", _test.TestUserAdminMCPRoleMigrationPreservesStageMappings},

	{"TestUserAdminMCPRoleMigrationMutationOccursAtMostOnce", _test.TestUserAdminMCPRoleMigrationMutationOccursAtMostOnce},

	{"TestMCPMountDoesNotBreakSPARoutes", _xtest.TestMCPMountDoesNotBreakSPARoutes},

	{"TestMCP_InvalidBearerDoesNotFallBackToSessionCookie", _xtest.TestMCP_InvalidBearerDoesNotFallBackToSessionCookie},

	{"TestMCP_BearerTokenEndToEnd", _xtest.TestMCP_BearerTokenEndToEnd},

	{"TestMCPSystemGetCapabilities_FullPreBootstrap", _xtest.TestMCPSystemGetCapabilities_FullPreBootstrap},

	{"TestMCPSystemGetCapabilities_AnonymousMode", _xtest.TestMCPSystemGetCapabilities_AnonymousMode},

	{"TestMCPProjectsListRequiresAuthAfterBootstrap", _xtest.TestMCPProjectsListRequiresAuthAfterBootstrap},

	{"TestMCPProjectsListSuccessWithAuthenticatedSession", _xtest.TestMCPProjectsListSuccessWithAuthenticatedSession},

	{"TestMCPProjectsListCapabilityUnavailableInAnonymousMode", _xtest.TestMCPProjectsListCapabilityUnavailableInAnonymousMode},

	{"TestMCPTodosCreateSuccess", _xtest.TestMCPTodosCreateSuccess},

	{"TestMCPTodosCreateRequiresAuthAfterBootstrap", _xtest.TestMCPTodosCreateRequiresAuthAfterBootstrap},

	{"TestMCPTodosCreateCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTodosCreateCapabilityUnavailableInAnonymousMode},

	{"TestMCPTodosCreateValidationErrorForMalformedInput", _xtest.TestMCPTodosCreateValidationErrorForMalformedInput},

	{"TestMCPTodosGetSuccess", _xtest.TestMCPTodosGetSuccess},

	{"TestMCPTodosGetNotFound", _xtest.TestMCPTodosGetNotFound},

	{"TestMCPTodosGetRequiresAuth", _xtest.TestMCPTodosGetRequiresAuth},

	{"TestMCPTodosSearchSuccess", _xtest.TestMCPTodosSearchSuccess},

	{"TestMCPTodosSearchValidationErrorForMalformedInput", _xtest.TestMCPTodosSearchValidationErrorForMalformedInput},

	{"TestMCPTodosUpdateSuccess", _xtest.TestMCPTodosUpdateSuccess},

	{"TestMCPTodosUpdateOmittedFieldsRemainUnchanged", _xtest.TestMCPTodosUpdateOmittedFieldsRemainUnchanged},

	{"TestMCPTodosUpdateNullClearsSupportedFields", _xtest.TestMCPTodosUpdateNullClearsSupportedFields},

	{"TestMCPTodosUpdatePatchSprintIdAssignAndClear", _xtest.TestMCPTodosUpdatePatchSprintIdAssignAndClear},

	{"TestMCPTodosUpdateValidationErrorForMalformedPatch", _xtest.TestMCPTodosUpdateValidationErrorForMalformedPatch},

	{"TestMCPTodosUpdateRejectsInvalidNullField", _xtest.TestMCPTodosUpdateRejectsInvalidNullField},

	{"TestMCPTodosUpdateRequiresAuth", _xtest.TestMCPTodosUpdateRequiresAuth},

	{"TestMCPTodosUpdateCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTodosUpdateCapabilityUnavailableInAnonymousMode},

	{"TestMCPTodosDeleteSuccess", _xtest.TestMCPTodosDeleteSuccess},

	{"TestMCPTodosDeleteNotFound", _xtest.TestMCPTodosDeleteNotFound},

	{"TestMCPTodosDeleteRequiresAuth", _xtest.TestMCPTodosDeleteRequiresAuth},

	{"TestMCPTodosDeleteCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTodosDeleteCapabilityUnavailableInAnonymousMode},

	{"TestMCPTodosMoveSuccessToAnotherColumn", _xtest.TestMCPTodosMoveSuccessToAnotherColumn},

	{"TestMCPTodosMoveSuccessWithAfterLocalId", _xtest.TestMCPTodosMoveSuccessWithAfterLocalId},

	{"TestMCPTodosMoveSuccessWithBeforeLocalId", _xtest.TestMCPTodosMoveSuccessWithBeforeLocalId},

	{"TestMCPTodosMoveValidationErrorWhenBothNeighborsSet", _xtest.TestMCPTodosMoveValidationErrorWhenBothNeighborsSet},

	{"TestMCPTodosMoveValidationErrorForNonexistentNeighbor", _xtest.TestMCPTodosMoveValidationErrorForNonexistentNeighbor},

	{"TestMCPTodosMoveValidationErrorForWrongColumnNeighbor", _xtest.TestMCPTodosMoveValidationErrorForWrongColumnNeighbor},

	{"TestMCPTodosMoveValidationErrorForAmbiguousAfterPlacement", _xtest.TestMCPTodosMoveValidationErrorForAmbiguousAfterPlacement},

	{"TestMCPTodosMoveRequiresAuth", _xtest.TestMCPTodosMoveRequiresAuth},

	{"TestMCPTodosMoveCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTodosMoveCapabilityUnavailableInAnonymousMode},

	{"TestMCPSprintsListSuccess", _xtest.TestMCPSprintsListSuccess},

	{"TestMCPSprintsGetSuccess", _xtest.TestMCPSprintsGetSuccess},

	{"TestMCPSprintsGetActiveSuccess", _xtest.TestMCPSprintsGetActiveSuccess},

	{"TestMCPSprintsGetActiveNoActiveSprintReturnsNull", _xtest.TestMCPSprintsGetActiveNoActiveSprintReturnsNull},

	{"TestMCPSprintsAuthFailure", _xtest.TestMCPSprintsAuthFailure},

	{"TestMCPSprintsCapabilityUnavailableInAnonymousMode", _xtest.TestMCPSprintsCapabilityUnavailableInAnonymousMode},

	{"TestMCPSprintsCreateSuccess", _xtest.TestMCPSprintsCreateSuccess},

	{"TestMCPSprintsCreateValidationErrorForMalformedInput", _xtest.TestMCPSprintsCreateValidationErrorForMalformedInput},

	{"TestMCPSprintsCreateValidationErrorForInvalidDateRange", _xtest.TestMCPSprintsCreateValidationErrorForInvalidDateRange},

	{"TestMCPSprintsCreateAuthFailure", _xtest.TestMCPSprintsCreateAuthFailure},

	{"TestMCPSprintsCreateCapabilityUnavailableInAnonymousMode", _xtest.TestMCPSprintsCreateCapabilityUnavailableInAnonymousMode},

	{"TestMCPSprintsActivateSuccess", _xtest.TestMCPSprintsActivateSuccess},

	{"TestMCPSprintsCloseSuccess", _xtest.TestMCPSprintsCloseSuccess},

	{"TestMCPSprintsActivateValidationErrorFromWrongState", _xtest.TestMCPSprintsActivateValidationErrorFromWrongState},

	{"TestMCPSprintsCloseValidationErrorFromWrongState", _xtest.TestMCPSprintsCloseValidationErrorFromWrongState},

	{"TestMCPSprintActionsAuthFailure", _xtest.TestMCPSprintActionsAuthFailure},

	{"TestMCPSprintActionsCapabilityUnavailableInAnonymousMode", _xtest.TestMCPSprintActionsCapabilityUnavailableInAnonymousMode},

	{"TestMCPSprintsUpdateSuccess", _xtest.TestMCPSprintsUpdateSuccess},

	{"TestMCPSprintsUpdateOmissionLeavesFieldsUnchanged", _xtest.TestMCPSprintsUpdateOmissionLeavesFieldsUnchanged},

	{"TestMCPSprintsUpdateValidationErrorForStateFieldCombo", _xtest.TestMCPSprintsUpdateValidationErrorForStateFieldCombo},

	{"TestMCPSprintsUpdateMalformedTimestampValidation", _xtest.TestMCPSprintsUpdateMalformedTimestampValidation},

	{"TestMCPSprintsUpdateInvalidDateRangeValidation", _xtest.TestMCPSprintsUpdateInvalidDateRangeValidation},

	{"TestMCPSprintsUpdateAuthFailure", _xtest.TestMCPSprintsUpdateAuthFailure},

	{"TestMCPSprintsUpdateCapabilityUnavailableInAnonymousMode", _xtest.TestMCPSprintsUpdateCapabilityUnavailableInAnonymousMode},

	{"TestMCPSprintsDeleteSuccess", _xtest.TestMCPSprintsDeleteSuccess},

	{"TestMCPSprintsDeleteNotFound", _xtest.TestMCPSprintsDeleteNotFound},

	{"TestMCPSprintsDeleteAuthFailure", _xtest.TestMCPSprintsDeleteAuthFailure},

	{"TestMCPSprintsDeleteCapabilityUnavailableInAnonymousMode", _xtest.TestMCPSprintsDeleteCapabilityUnavailableInAnonymousMode},

	{"TestMCPTagsListProjectSuccess", _xtest.TestMCPTagsListProjectSuccess},

	{"TestMCPTagsListMineSuccess", _xtest.TestMCPTagsListMineSuccess},

	{"TestMCPTagsAuthFailure", _xtest.TestMCPTagsAuthFailure},

	{"TestMCPTagsCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTagsCapabilityUnavailableInAnonymousMode},

	{"TestMCPTagsUpdateMineColorSuccess", _xtest.TestMCPTagsUpdateMineColorSuccess},

	{"TestMCPTagsDeleteMineSuccess", _xtest.TestMCPTagsDeleteMineSuccess},

	{"TestMCPTagsDeleteMineValidationInvalidTagId", _xtest.TestMCPTagsDeleteMineValidationInvalidTagId},

	{"TestMCPTagsDeleteMineValidationUnknownField", _xtest.TestMCPTagsDeleteMineValidationUnknownField},

	{"TestMCPTagsDeleteMineAuthFailure", _xtest.TestMCPTagsDeleteMineAuthFailure},

	{"TestMCPTagsDeleteMineCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTagsDeleteMineCapabilityUnavailableInAnonymousMode},

	{"TestMCPTagsDeleteMineCapabilityUnavailableBeforeBootstrap", _xtest.TestMCPTagsDeleteMineCapabilityUnavailableBeforeBootstrap},

	{"TestMCPTagsDeleteMineNotInViewerLibraryNotFound", _xtest.TestMCPTagsDeleteMineNotInViewerLibraryNotFound},

	{"TestMCPTagsUpdateMineColorClearSuccess", _xtest.TestMCPTagsUpdateMineColorClearSuccess},

	{"TestMCPTagsUpdateMineColorMalformedColorValidation", _xtest.TestMCPTagsUpdateMineColorMalformedColorValidation},

	{"TestMCPTagsUpdateMineColorRejectsEmptyStringClear", _xtest.TestMCPTagsUpdateMineColorRejectsEmptyStringClear},

	{"TestMCPTagsUpdateMineColorMalformedInputValidation", _xtest.TestMCPTagsUpdateMineColorMalformedInputValidation},

	{"TestMCPTagsUpdateMineColorAuthFailure", _xtest.TestMCPTagsUpdateMineColorAuthFailure},

	{"TestMCPTagsUpdateMineColorCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTagsUpdateMineColorCapabilityUnavailableInAnonymousMode},

	{"TestMCPTagsUpdateProjectColorSuccess", _xtest.TestMCPTagsUpdateProjectColorSuccess},

	{"TestMCPTagsUpdateProjectColorTemporaryBoardSucceeds", _xtest.TestMCPTagsUpdateProjectColorTemporaryBoardSucceeds},

	{"TestMCPTagsUpdateProjectColorVisibleToOtherMemberViaListProject", _xtest.TestMCPTagsUpdateProjectColorVisibleToOtherMemberViaListProject},

	{"TestMCPTagsUpdateProjectColorPermissionFailure", _xtest.TestMCPTagsUpdateProjectColorPermissionFailure},

	{"TestMCPTagsUpdateProjectColorWrongProjectNotFound", _xtest.TestMCPTagsUpdateProjectColorWrongProjectNotFound},

	{"TestMCPTagsUpdateProjectColorUserOwnedTagSuccess", _xtest.TestMCPTagsUpdateProjectColorUserOwnedTagSuccess},

	{"TestMCPTagsUpdateProjectColorExactlyOneValidation", _xtest.TestMCPTagsUpdateProjectColorExactlyOneValidation},

	{"TestMCPTagsUpdateProjectColorByNameAllowsNonMaintainerMember", _xtest.TestMCPTagsUpdateProjectColorByNameAllowsNonMaintainerMember},

	{"TestMCPTagsUpdateProjectColorUserOwnedTagClearNoOpSuccess", _xtest.TestMCPTagsUpdateProjectColorUserOwnedTagClearNoOpSuccess},

	{"TestMCPTagsDeleteProjectSuccess", _xtest.TestMCPTagsDeleteProjectSuccess},

	{"TestMCPTagsDeleteProjectWrongProjectNotFound", _xtest.TestMCPTagsDeleteProjectWrongProjectNotFound},

	{"TestMCPTagsDeleteProjectUserOwnedTagNotFound", _xtest.TestMCPTagsDeleteProjectUserOwnedTagNotFound},

	{"TestMCPTagsDeleteProjectValidationInvalidTagId", _xtest.TestMCPTagsDeleteProjectValidationInvalidTagId},

	{"TestMCPTagsDeleteProjectValidationUnknownField", _xtest.TestMCPTagsDeleteProjectValidationUnknownField},

	{"TestMCPTagsDeleteProjectAuthFailure", _xtest.TestMCPTagsDeleteProjectAuthFailure},

	{"TestMCPTagsDeleteProjectCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTagsDeleteProjectCapabilityUnavailableInAnonymousMode},

	{"TestMCPTagsDeleteProjectCapabilityUnavailableBeforeBootstrap", _xtest.TestMCPTagsDeleteProjectCapabilityUnavailableBeforeBootstrap},

	{"TestMCPTagsDeleteProjectPermissionFailure", _xtest.TestMCPTagsDeleteProjectPermissionFailure},

	{"TestMCPTagsUpdateProjectColorMalformedColorValidation", _xtest.TestMCPTagsUpdateProjectColorMalformedColorValidation},

	{"TestMCPTagsUpdateProjectColorClearSuccess", _xtest.TestMCPTagsUpdateProjectColorClearSuccess},

	{"TestMCPTagsUpdateProjectColorAuthFailure", _xtest.TestMCPTagsUpdateProjectColorAuthFailure},

	{"TestMCPTagsUpdateProjectColorCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTagsUpdateProjectColorCapabilityUnavailableInAnonymousMode},

	{"TestMCPMembersListSuccess", _xtest.TestMCPMembersListSuccess},

	{"TestMCPMembersListNormalizesLegacyStoredRoles", _xtest.TestMCPMembersListNormalizesLegacyStoredRoles},

	{"TestMCPMembersListAvailableSuccess", _xtest.TestMCPMembersListAvailableSuccess},

	{"TestMCPMembersListAuthFailure", _xtest.TestMCPMembersListAuthFailure},

	{"TestMCPMembersListCapabilityUnavailableInAnonymousMode", _xtest.TestMCPMembersListCapabilityUnavailableInAnonymousMode},

	{"TestMCPMembersListAvailableCapabilityUnavailableInAnonymousMode", _xtest.TestMCPMembersListAvailableCapabilityUnavailableInAnonymousMode},

	{"TestMCPMembersListAvailablePermissionFailure", _xtest.TestMCPMembersListAvailablePermissionFailure},

	{"TestMCPMembersAddSuccess", _xtest.TestMCPMembersAddSuccess},

	{"TestMCPMembersAddDuplicateConflict", _xtest.TestMCPMembersAddDuplicateConflict},

	{"TestMCPMembersAddUnsupportedRole", _xtest.TestMCPMembersAddUnsupportedRole},

	{"TestMCPMembersAddUserNotFound", _xtest.TestMCPMembersAddUserNotFound},

	{"TestMCPMembersAddAuthFailure", _xtest.TestMCPMembersAddAuthFailure},

	{"TestMCPMembersAddCapabilityUnavailableInAnonymousMode", _xtest.TestMCPMembersAddCapabilityUnavailableInAnonymousMode},

	{"TestMCPMembersAddCapabilityUnavailableBeforeBootstrap", _xtest.TestMCPMembersAddCapabilityUnavailableBeforeBootstrap},

	{"TestMCPMembersAddPermissionFailure", _xtest.TestMCPMembersAddPermissionFailure},

	{"TestMCPMembersUpdateRoleSuccess", _xtest.TestMCPMembersUpdateRoleSuccess},

	{"TestMCPMembersUpdateRoleUnchangedNoOp", _xtest.TestMCPMembersUpdateRoleUnchangedNoOp},

	{"TestMCPMembersUpdateRoleUnsupportedRole", _xtest.TestMCPMembersUpdateRoleUnsupportedRole},

	{"TestMCPMembersUpdateRoleTargetNotMember", _xtest.TestMCPMembersUpdateRoleTargetNotMember},

	{"TestMCPMembersUpdateRoleAuthFailure", _xtest.TestMCPMembersUpdateRoleAuthFailure},

	{"TestMCPMembersUpdateRoleCapabilityUnavailableInAnonymousMode", _xtest.TestMCPMembersUpdateRoleCapabilityUnavailableInAnonymousMode},

	{"TestMCPMembersUpdateRoleCapabilityUnavailableBeforeBootstrap", _xtest.TestMCPMembersUpdateRoleCapabilityUnavailableBeforeBootstrap},

	{"TestMCPMembersUpdateRolePermissionFailure", _xtest.TestMCPMembersUpdateRolePermissionFailure},

	{"TestMCPMembersUpdateRoleSelfDemotionConflict", _xtest.TestMCPMembersUpdateRoleSelfDemotionConflict},

	{"TestMCPMembersUpdateRoleLastMaintainerDemotionConflict", _xtest.TestMCPMembersUpdateRoleLastMaintainerDemotionConflict},

	{"TestMCPMembersUpdateRoleLegacyOutputNormalization", _xtest.TestMCPMembersUpdateRoleLegacyOutputNormalization},

	{"TestMCPMembersRemoveSuccess", _xtest.TestMCPMembersRemoveSuccess},

	{"TestMCPMembersRemoveTargetNotMember", _xtest.TestMCPMembersRemoveTargetNotMember},

	{"TestMCPMembersRemoveAuthFailure", _xtest.TestMCPMembersRemoveAuthFailure},

	{"TestMCPMembersRemoveCapabilityUnavailableInAnonymousMode", _xtest.TestMCPMembersRemoveCapabilityUnavailableInAnonymousMode},

	{"TestMCPMembersRemoveCapabilityUnavailableBeforeBootstrap", _xtest.TestMCPMembersRemoveCapabilityUnavailableBeforeBootstrap},

	{"TestMCPMembersRemovePermissionFailure", _xtest.TestMCPMembersRemovePermissionFailure},

	{"TestMCPMembersRemoveLastMaintainerValidation", _xtest.TestMCPMembersRemoveLastMaintainerValidation},

	{"TestMCPMembersRemoveSelfSuccessWhenNotLastMaintainer", _xtest.TestMCPMembersRemoveSelfSuccessWhenNotLastMaintainer},

	{"TestMCPUnknownToolReturnsNotFoundEnvelope", _xtest.TestMCPUnknownToolReturnsNotFoundEnvelope},

	{"TestMCPInvalidJSONReturnsValidationError", _xtest.TestMCPInvalidJSONReturnsValidationError},

	{"TestMCPAdminUserMutationTransportProjectionAndRealtimeSilence", _xtest.TestMCPAdminUserMutationTransportProjectionAndRealtimeSilence},

	{"TestMCPAdminUserMutationOwnerOnOwnerAndSelfDowngrade", _xtest.TestMCPAdminUserMutationOwnerOnOwnerAndSelfDowngrade},

	{"TestMCPAdminUserMutationCapabilityAuthenticationAndInputPrecedence", _xtest.TestMCPAdminUserMutationCapabilityAuthenticationAndInputPrecedence},

	{"TestMCPAdminUserMutationAuthorityTargetAndOwnerInvariantPrecedence", _xtest.TestMCPAdminUserMutationAuthorityTargetAndOwnerInvariantPrecedence},

	{"TestMCPAdminUserMutationInputShapeDifferences", _xtest.TestMCPAdminUserMutationInputShapeDifferences},

	{"TestMCPAdminRoleMutationPreReadAndMutationErrorMeaningDiffer", _xtest.TestMCPAdminRoleMutationPreReadAndMutationErrorMeaningDiffer},

	{"TestMCPAdminRoleMutationStoreErrorProjection", _xtest.TestMCPAdminRoleMutationStoreErrorProjection},

	{"TestMCPAdminRoleCommittedMutationSurvivesPostReadFailure", _xtest.TestMCPAdminRoleCommittedMutationSurvivesPostReadFailure},

	{"TestMCPAdminDeleteOwnedProjectFailureProjectionAndRollback", _xtest.TestMCPAdminDeleteOwnedProjectFailureProjectionAndRollback},

	{"TestMCPAdminDottedNamesRemainUnavailable", _xtest.TestMCPAdminDottedNamesRemainUnavailable},

	{"TestMCPBoardGetAssigneeFilter", _xtest.TestMCPBoardGetAssigneeFilter},

	{"TestMCPBoardGetAssigneeValidation", _xtest.TestMCPBoardGetAssigneeValidation},

	{"TestMCPBoardGetAuthFailure", _xtest.TestMCPBoardGetAuthFailure},

	{"TestMCPBoardGetCapabilityUnavailableInAnonymousMode", _xtest.TestMCPBoardGetCapabilityUnavailableInAnonymousMode},

	{"TestMCPBoardGetPerColumnPagination", _xtest.TestMCPBoardGetPerColumnPagination},

	{"TestMCPBoardGetSuccess", _xtest.TestMCPBoardGetSuccess},

	{"TestMCPBoardGetFilters", _xtest.TestMCPBoardGetFilters},

	{"TestMCPBoardGetColumnKeyFilter", _xtest.TestMCPBoardGetColumnKeyFilter},

	{"TestMCPBoardGetSprintFilter", _xtest.TestMCPBoardGetSprintFilter},

	{"TestMCPBoardGetStoredSprintIDRoundTripsAcrossTransportsAndAlias", _xtest.TestMCPBoardGetStoredSprintIDRoundTripsAcrossTransportsAndAlias},

	{"TestMCPBoardGetTransportContract_LegacySuccessEnvelope", _xtest.TestMCPBoardGetTransportContract_LegacySuccessEnvelope},

	{"TestMCPBoardGetTransportContract_NullCreatorIsExplicitNull", _xtest.TestMCPBoardGetTransportContract_NullCreatorIsExplicitNull},

	{"TestMCPBoardGetTransportContract_LegacyErrorEnvelope", _xtest.TestMCPBoardGetTransportContract_LegacyErrorEnvelope},

	{"TestMCPBoardGetTransportContract_JSONRPCSuccessExposesPaginationMetadata", _xtest.TestMCPBoardGetTransportContract_JSONRPCSuccessExposesPaginationMetadata},

	{"TestMCPBoardGetTransportContract_CanonicalSlugIdentityMatrix", _xtest.TestMCPBoardGetTransportContract_CanonicalSlugIdentityMatrix},

	{"TestMCPBoardGetTransportContract_JSONRPCPaginationContinuesFromReturnedCursor", _xtest.TestMCPBoardGetTransportContract_JSONRPCPaginationContinuesFromReturnedCursor},

	{"TestMCPBoardGetTransportContract_JSONRPCToolErrorAddsSanitizedStructuredDetails", _xtest.TestMCPBoardGetTransportContract_JSONRPCToolErrorAddsSanitizedStructuredDetails},

	{"TestMCPBoardGetTransportContract_JSONRPCFullModeAuthBoundary", _xtest.TestMCPBoardGetTransportContract_JSONRPCFullModeAuthBoundary},

	{"TestMCPBoardGetTransportContract_LegacyCapabilityAndAuthBoundaries", _xtest.TestMCPBoardGetTransportContract_LegacyCapabilityAndAuthBoundaries},

	{"TestMCPBoardGetTransportContract_JSONRPCAnonymousModeIsToolError", _xtest.TestMCPBoardGetTransportContract_JSONRPCAnonymousModeIsToolError},

	{"TestMCPBoardGetTransportContract_CanonicalAndAliasEquivalent", _xtest.TestMCPBoardGetTransportContract_CanonicalAndAliasEquivalent},

	{"TestMCPBoardGetTransportContract_CanonicalAndAliasValidationEquivalent", _xtest.TestMCPBoardGetTransportContract_CanonicalAndAliasValidationEquivalent},

	{"TestMCPBoardGetTransportContract_PrecedenceEquivalentForDeniedTarget", _xtest.TestMCPBoardGetTransportContract_PrecedenceEquivalentForDeniedTarget},

	{"TestMCPBoardGetTransportContract_ToolsListAdvertisesCanonicalAndSort", _xtest.TestMCPBoardGetTransportContract_ToolsListAdvertisesCanonicalAndSort},

	{"TestMCPBoardGetTransportContract_RuntimeSortMatchesAdvertisedValues", _xtest.TestMCPBoardGetTransportContract_RuntimeSortMatchesAdvertisedValues},

	{"TestMCPBoardGetPriorityFilter", _xtest.TestMCPBoardGetPriorityFilter},

	{"TestMCPBoardGetSortOrder", _xtest.TestMCPBoardGetSortOrder},

	{"TestJSONRPCAuthenticationChallenge", _xtest.TestJSONRPCAuthenticationChallenge},

	{"TestJSONRPCAuthenticationMethods", _xtest.TestJSONRPCAuthenticationMethods},

	{"TestJSONRPCSystemCapabilitiesExposesLegacyAdapterVersion", _xtest.TestJSONRPCSystemCapabilitiesExposesLegacyAdapterVersion},

	{"TestJSONRPCSprintsListExposesLegacyUnscheduledCount", _xtest.TestJSONRPCSprintsListExposesLegacyUnscheduledCount},

	{"TestJSONRPCDashboardListTodosExposesLegacyPagination", _xtest.TestJSONRPCDashboardListTodosExposesLegacyPagination},

	{"TestJSONRPC_InitializeHandshake", _xtest.TestJSONRPC_InitializeHandshake},

	{"TestJSONRPC_InitializeRequiresLifecycleFields", _xtest.TestJSONRPC_InitializeRequiresLifecycleFields},

	{"TestJSONRPC_InitializeRequiresClientInfoVersion", _xtest.TestJSONRPC_InitializeRequiresClientInfoVersion},

	{"TestJSONRPC_PingReturnsEmptyResult", _xtest.TestJSONRPC_PingReturnsEmptyResult},

	{"TestJSONRPC_InitializedNotification", _xtest.TestJSONRPC_InitializedNotification},

	{"TestJSONRPC_InitializedAltName", _xtest.TestJSONRPC_InitializedAltName},

	{"TestJSONRPC_InitializedWithIDRejected", _xtest.TestJSONRPC_InitializedWithIDRejected},

	{"TestJSONRPC_UnknownMethodReturnsError", _xtest.TestJSONRPC_UnknownMethodReturnsError},

	{"TestJSONRPC_InvalidJSONReturnsParseError", _xtest.TestJSONRPC_InvalidJSONReturnsParseError},

	{"TestJSONRPC_InvalidParamsTypeReturnsInvalidRequest", _xtest.TestJSONRPC_InvalidParamsTypeReturnsInvalidRequest},

	{"TestJSONRPC_NotificationWithInvalidParamsRejected", _xtest.TestJSONRPC_NotificationWithInvalidParamsRejected},

	{"TestJSONRPC_StructuralErrorPreservesRecoverableID", _xtest.TestJSONRPC_StructuralErrorPreservesRecoverableID},

	{"TestJSONRPC_MissingVersionReturnsInvalidRequest", _xtest.TestJSONRPC_MissingVersionReturnsInvalidRequest},

	{"TestJSONRPC_UnauthenticatedGetChallenges", _xtest.TestJSONRPC_UnauthenticatedGetChallenges},

	{"TestJSONRPC_LegacyEndpointStillWorks", _xtest.TestJSONRPC_LegacyEndpointStillWorks},

	{"TestJSONRPC_MissingMethodReturnsInvalidRequest", _xtest.TestJSONRPC_MissingMethodReturnsInvalidRequest},

	{"TestJSONRPC_ToolsList_MatchesImplementedTools", _xtest.TestJSONRPC_ToolsList_MatchesImplementedTools},

	{"TestJSONRPC_ToolsList_TodosCreateSchema", _xtest.TestJSONRPC_ToolsList_TodosCreateSchema},

	{"TestJSONRPC_ToolsList_TodosUpdateSchema", _xtest.TestJSONRPC_ToolsList_TodosUpdateSchema},

	{"TestJSONRPC_ToolsList_TodosLinkAddSchema", _xtest.TestJSONRPC_ToolsList_TodosLinkAddSchema},

	{"TestJSONRPC_ToolsList_ProjectsListSchema", _xtest.TestJSONRPC_ToolsList_ProjectsListSchema},

	{"TestJSONRPC_ToolsList_WithoutInitialize", _xtest.TestJSONRPC_ToolsList_WithoutInitialize},

	{"TestJSONRPC_ToolsCall_HappyPath", _xtest.TestJSONRPC_ToolsCall_HappyPath},

	{"TestJSONRPC_ToolsCall_TodosCreate", _xtest.TestJSONRPC_ToolsCall_TodosCreate},

	{"TestJSONRPC_ToolsCall_UnknownTool", _xtest.TestJSONRPC_ToolsCall_UnknownTool},

	{"TestJSONRPC_ToolsCall_MissingName", _xtest.TestJSONRPC_ToolsCall_MissingName},

	{"TestJSONRPC_ToolsCall_MissingParams", _xtest.TestJSONRPC_ToolsCall_MissingParams},

	{"TestJSONRPC_ToolsCall_MissingRequiredArguments", _xtest.TestJSONRPC_ToolsCall_MissingRequiredArguments},

	{"TestJSONRPC_ToolsCall_WithoutInitialize", _xtest.TestJSONRPC_ToolsCall_WithoutInitialize},

	{"TestJSONRPC_ToolsCall_WithoutID", _xtest.TestJSONRPC_ToolsCall_WithoutID},

	{"TestJSONRPC_ToolsCall_ErrorMapping_AuthRequired", _xtest.TestJSONRPC_ToolsCall_ErrorMapping_AuthRequired},

	{"TestJSONRPC_ToolsCall_ErrorMapping_CapabilityUnavailable", _xtest.TestJSONRPC_ToolsCall_ErrorMapping_CapabilityUnavailable},

	{"TestJSONRPC_ToolsCall_NoLegacyLeakage", _xtest.TestJSONRPC_ToolsCall_NoLegacyLeakage},

	{"TestJSONRPC_ToolsCall_DefaultsEmptyArguments", _xtest.TestJSONRPC_ToolsCall_DefaultsEmptyArguments},

	{"TestJSONRPC_ResponsePreservesID", _xtest.TestJSONRPC_ResponsePreservesID},

	{"TestJSONRPC_ToolsList_WorkflowSchemas", _xtest.TestJSONRPC_ToolsList_WorkflowSchemas},

	{"TestJSONRPCTransportMethodOriginAndCanonicalPath", _xtest.TestJSONRPCTransportMethodOriginAndCanonicalPath},

	{"TestJSONRPCTransportMediaAndMessageClassification", _xtest.TestJSONRPCTransportMediaAndMessageClassification},

	{"TestJSONRPCProtocolVersionNegotiation", _xtest.TestJSONRPCProtocolVersionNegotiation},

	{"TestJSONRPCPreservesLargeNumericID", _xtest.TestJSONRPCPreservesLargeNumericID},

	{"TestJSONRPC_ToolsCall_LegacyDottedName_StillDispatches", _xtest.TestJSONRPC_ToolsCall_LegacyDottedName_StillDispatches},

	{"TestJSONRPC_ToolsCall_LegacyDottedName_RequiredFieldValidation", _xtest.TestJSONRPC_ToolsCall_LegacyDottedName_RequiredFieldValidation},

	{"TestJSONRPC_ToolsCall_LegacyDottedName_UnknownAliasStillErrors", _xtest.TestJSONRPC_ToolsCall_LegacyDottedName_UnknownAliasStillErrors},

	{"TestHTTP_LegacyMCPEndpoint_DottedNameStillDispatches", _xtest.TestHTTP_LegacyMCPEndpoint_DottedNameStillDispatches},

	{"TestHTTP_LegacyMCPEndpoint_UnknownDottedNameStill404s", _xtest.TestHTTP_LegacyMCPEndpoint_UnknownDottedNameStill404s},

	{"TestJSONRPC_ToolsList_NeverContainsDottedNames", _xtest.TestJSONRPC_ToolsList_NeverContainsDottedNames},

	{"TestHTTP_LegacyGetCapabilities_NeverContainsDottedNames", _xtest.TestHTTP_LegacyGetCapabilities_NeverContainsDottedNames},

	{"TestPriorityMutationMCPTransportAndRealtimeContracts", _xtest.TestPriorityMutationMCPTransportAndRealtimeContracts},

	{"TestPriorityListMCPTransportContract", _xtest.TestPriorityListMCPTransportContract},

	{"TestPriorityMutationMCPSemanticValidationPrecedesAccess", _xtest.TestPriorityMutationMCPSemanticValidationPrecedesAccess},

	{"TestPriorityMutationMCPReasonContract", _xtest.TestPriorityMutationMCPReasonContract},

	{"TestProjectLifecycleMCPTransportsCanonicalCreateAndAliasAbsence", _xtest.TestProjectLifecycleMCPTransportsCanonicalCreateAndAliasAbsence},

	{"TestProjectLifecycleMCPRegistrySchemasAndCapabilityGates", _xtest.TestProjectLifecycleMCPRegistrySchemasAndCapabilityGates},

	{"TestProjectLifecycleMCPUpdateOrderingPostReadFailureAndSilence", _xtest.TestProjectLifecycleMCPUpdateOrderingPostReadFailureAndSilence},

	{"TestProjectLifecycleMCPDeleteOrderingProjectionAndSilence", _xtest.TestProjectLifecycleMCPDeleteOrderingProjectionAndSilence},

	{"TestProjectMembershipMCPTransportAliasAndRealtimeMatrix", _xtest.TestProjectMembershipMCPTransportAliasAndRealtimeMatrix},

	{"TestProjectMembershipMCPSemanticValidationPrecedesAccess", _xtest.TestProjectMembershipMCPSemanticValidationPrecedesAccess},

	{"TestProjectMembershipMCPNoOpAndSelfRemovalContracts", _xtest.TestProjectMembershipMCPNoOpAndSelfRemovalContracts},

	{"TestProjectMembershipMCPBoardModeContracts", _xtest.TestProjectMembershipMCPBoardModeContracts},

	{"TestProjectMembershipMCPPostReadContracts", _xtest.TestProjectMembershipMCPPostReadContracts},

	{"TestProjectMembershipMCPRemoveSkipsPostRead", _xtest.TestProjectMembershipMCPRemoveSkipsPostRead},

	{"TestMCPProjectsCreateSuccess", _xtest.TestMCPProjectsCreateSuccess},

	{"TestMCPProjectsUpdateTwoFieldsSuccess", _xtest.TestMCPProjectsUpdateTwoFieldsSuccess},

	{"TestMCPProjectsUpdateAtomicityInvalidWeeks", _xtest.TestMCPProjectsUpdateAtomicityInvalidWeeks},

	{"TestMCPProjectsUpdateViewerForbidden", _xtest.TestMCPProjectsUpdateViewerForbidden},

	{"TestMCPProjectsUpdateReturnsCanonicalSlug", _xtest.TestMCPProjectsUpdateReturnsCanonicalSlug},

	{"TestMCPProjectsDeleteSuccess", _xtest.TestMCPProjectsDeleteSuccess},

	{"TestMCPProjectsDeleteViewerForbidden", _xtest.TestMCPProjectsDeleteViewerForbidden},

	{"TestMCPProjectsDeleteRequiresAuth", _xtest.TestMCPProjectsDeleteRequiresAuth},

	{"TestMCPProjectsDeleteCapabilityUnavailableInAnonymousMode", _xtest.TestMCPProjectsDeleteCapabilityUnavailableInAnonymousMode},

	{"TestMCPAdminListUsersRegularUserForbidden", _xtest.TestMCPAdminListUsersRegularUserForbidden},

	{"TestMCPAdminListUsersAsAdmin", _xtest.TestMCPAdminListUsersAsAdmin},

	{"TestMCPAdminUpdateUserRoleOwnerSuccess", _xtest.TestMCPAdminUpdateUserRoleOwnerSuccess},

	{"TestMCPAdminUpdateUserRoleAdminForbidden", _xtest.TestMCPAdminUpdateUserRoleAdminForbidden},

	{"TestMCPAdminUpdateUserRolePreventsLastOwnerDemotion", _xtest.TestMCPAdminUpdateUserRolePreventsLastOwnerDemotion},

	{"TestMCPAdminDeleteUserOwnerSuccess", _xtest.TestMCPAdminDeleteUserOwnerSuccess},

	{"TestMCPAdminDeleteUserAdminForbidden", _xtest.TestMCPAdminDeleteUserAdminForbidden},

	{"TestMCPAdminDeleteUserSelfRejected", _xtest.TestMCPAdminDeleteUserSelfRejected},

	{"TestMCPDashboardGetSummaryAndListTodos", _xtest.TestMCPDashboardGetSummaryAndListTodos},

	{"TestMCPMetricsGetBurndownSuccess", _xtest.TestMCPMetricsGetBurndownSuccess},

	{"TestMCPMetricsGetBurndownSprintProjectMismatch", _xtest.TestMCPMetricsGetBurndownSprintProjectMismatch},

	{"TestMCPMetricsGetBacklogSizeSuccess", _xtest.TestMCPMetricsGetBacklogSizeSuccess},

	{"TestMCPProjectsUpdateTemporaryBoardOwnerSuccess", _xtest.TestMCPProjectsUpdateTemporaryBoardOwnerSuccess},

	{"TestMCPProjectsDeleteTemporaryBoardOwnerSuccess", _xtest.TestMCPProjectsDeleteTemporaryBoardOwnerSuccess},

	{"TestMCPProjectsUpdateTemporaryBoardOtherUserForbidden", _xtest.TestMCPProjectsUpdateTemporaryBoardOtherUserForbidden},

	{"TestMCPProjectsDeleteTemporaryBoardOtherUserForbidden", _xtest.TestMCPProjectsDeleteTemporaryBoardOtherUserForbidden},

	{"TestMCPProjectsUpdateDurableNonMemberNotFound", _xtest.TestMCPProjectsUpdateDurableNonMemberNotFound},

	{"TestMCPProjectsDeleteDurableNonMemberNotFound", _xtest.TestMCPProjectsDeleteDurableNonMemberNotFound},

	{"TestMCPProjectsUpdateAnonymousBoardNotFound", _xtest.TestMCPProjectsUpdateAnonymousBoardNotFound},

	{"TestMCPProjectsDeleteAnonymousBoardNotFound", _xtest.TestMCPProjectsDeleteAnonymousBoardNotFound},

	{"TestSprintDefinitionMCPTransportAndDefinitionContracts", _xtest.TestSprintDefinitionMCPTransportAndDefinitionContracts},

	{"TestSprintDefinitionMCPEmptyPatchContract", _xtest.TestSprintDefinitionMCPEmptyPatchContract},

	{"TestSprintDefinitionMCPCancellationContract", _xtest.TestSprintDefinitionMCPCancellationContract},

	{"TestSprintDefinitionMCPCommittedCreateFailureContract", _xtest.TestSprintDefinitionMCPCommittedCreateFailureContract},

	{"TestSprintDefinitionMCPAuthorityAndBoundaryContracts", _xtest.TestSprintDefinitionMCPAuthorityAndBoundaryContracts},

	{"TestSprintDefinitionMCPAuthenticationAndCapabilityContracts", _xtest.TestSprintDefinitionMCPAuthenticationAndCapabilityContracts},

	{"TestSprintDefinitionMCPAliasesRemainDispatchOnly", _xtest.TestSprintDefinitionMCPAliasesRemainDispatchOnly},

	{"TestSprintDefinitionMCPDefinitionFieldsRespectExistingSprintState", _xtest.TestSprintDefinitionMCPDefinitionFieldsRespectExistingSprintState},

	{"TestSprintDefinitionMCPRejectsDisabledProjectAcrossTransports", _xtest.TestSprintDefinitionMCPRejectsDisabledProjectAcrossTransports},

	{"TestSprintDefinitionMCPCreateReturnFailureDoesNotLeakCause", _xtest.TestSprintDefinitionMCPCreateReturnFailureDoesNotLeakCause},

	{"TestSprintLifecycleMCPActivateContract", _xtest.TestSprintLifecycleMCPActivateContract},

	{"TestSprintLifecycleMCPCloseContract", _xtest.TestSprintLifecycleMCPCloseContract},

	{"TestSprintLifecycleMCPDeleteContract", _xtest.TestSprintLifecycleMCPDeleteContract},

	{"TestSprintLifecycleMCPActivateRejectionContract", _xtest.TestSprintLifecycleMCPActivateRejectionContract},

	{"TestSprintLifecycleMCPCloseRejectionContract", _xtest.TestSprintLifecycleMCPCloseRejectionContract},

	{"TestSprintLifecycleMCPCommittedProjectionFailureContract", _xtest.TestSprintLifecycleMCPCommittedProjectionFailureContract},

	{"TestSprintLifecycleMCPDeleteDetachesTodos", _xtest.TestSprintLifecycleMCPDeleteDetachesTodos},

	{"TestSprintLifecycleMCPDependencyFailureContract", _xtest.TestSprintLifecycleMCPDependencyFailureContract},

	{"TestSprintLifecycleMCPCancellationContract", _xtest.TestSprintLifecycleMCPCancellationContract},

	{"TestSprintLifecycleMCPStoreErrorMappingContract", _xtest.TestSprintLifecycleMCPStoreErrorMappingContract},

	{"TestSprintLifecycleMCPRejectsDisabledProjectAcrossTransports", _xtest.TestSprintLifecycleMCPRejectsDisabledProjectAcrossTransports},

	{"TestSprintLifecycleMCPDeleteFailureContract", _xtest.TestSprintLifecycleMCPDeleteFailureContract},

	{"TestSprintLifecycleMCPFreshRoleThresholdContract", _xtest.TestSprintLifecycleMCPFreshRoleThresholdContract},

	{"TestSprintLifecycleMCPAuthenticationAndCapabilityContract", _xtest.TestSprintLifecycleMCPAuthenticationAndCapabilityContract},

	{"TestSprintLifecycleMCPInputContract", _xtest.TestSprintLifecycleMCPInputContract},

	{"TestSprintLifecycleMCPAliasesRemainDispatchOnly", _xtest.TestSprintLifecycleMCPAliasesRemainDispatchOnly},

	{"TestMCPTagsMutationTransportsAliasesAndRealtime", _xtest.TestMCPTagsMutationTransportsAliasesAndRealtime},

	{"TestMCPTagsMutationReadAndDispatchSequencing", _xtest.TestMCPTagsMutationReadAndDispatchSequencing},

	{"TestMCPTagsMutationCommittedUpdatePostReadFailure", _xtest.TestMCPTagsMutationCommittedUpdatePostReadFailure},

	{"TestMCPTagsMutationValidationAndAuthorityOrdering", _xtest.TestMCPTagsMutationValidationAndAuthorityOrdering},

	{"TestMCPTagsMutationDeleteMineCrossProjectHasNoAffectedPublication", _xtest.TestMCPTagsMutationDeleteMineCrossProjectHasNoAffectedPublication},

	{"TestMCPTagsMutationClearMissingPreferenceAndInputPolicy", _xtest.TestMCPTagsMutationClearMissingPreferenceAndInputPolicy},

	{"TestTodoCreateMCPTransportAliasMatrix", _xtest.TestTodoCreateMCPTransportAliasMatrix},

	{"TestTodoCreateMCPRealtimeContracts", _xtest.TestTodoCreateMCPRealtimeContracts},

	{"TestTodoCreateMCPPositionContracts", _xtest.TestTodoCreateMCPPositionContracts},

	{"TestTodoCreateMCPPrecedenceRoleAndModeContracts", _xtest.TestTodoCreateMCPPrecedenceRoleAndModeContracts},

	{"TestTodoCreateMCPLaneAndFieldProjectionContracts", _xtest.TestTodoCreateMCPLaneAndFieldProjectionContracts},

	{"TestTodoCreateMCPRejectsSprintAssignmentWhenDisabledAcrossTransports", _xtest.TestTodoCreateMCPRejectsSprintAssignmentWhenDisabledAcrossTransports},

	{"TestTodoDeleteMCPTransportAliasMatrix", _xtest.TestTodoDeleteMCPTransportAliasMatrix},

	{"TestTodoDeleteMCPRealtimeContracts", _xtest.TestTodoDeleteMCPRealtimeContracts},

	{"TestTodoDeleteMCPAccessRoleAndModeContracts", _xtest.TestTodoDeleteMCPAccessRoleAndModeContracts},

	{"TestTodoDeleteMCPGateAndValidationPrecedence", _xtest.TestTodoDeleteMCPGateAndValidationPrecedence},

	{"TestTodoLinkMutationMCPTransportAndRealtimeContracts", _xtest.TestTodoLinkMutationMCPTransportAndRealtimeContracts},

	{"TestTodoLinkMutationMCPPrecedence", _xtest.TestTodoLinkMutationMCPPrecedence},

	{"TestTodoLinkMutationMCPDuplicateAddContract", _xtest.TestTodoLinkMutationMCPDuplicateAddContract},

	{"TestTodoLinkMutationMCPPostWriteReadFailures", _xtest.TestTodoLinkMutationMCPPostWriteReadFailures},

	{"TestTodoLinkMutationMCPBoardModeContracts", _xtest.TestTodoLinkMutationMCPBoardModeContracts},

	{"TestMCPTodosMoveDottedAliasOverJSONRPCPreservesBoardRefreshSilence", _xtest.TestMCPTodosMoveDottedAliasOverJSONRPCPreservesBoardRefreshSilence},

	{"TestTodoUpdateMCPDisabledSprintFieldMatrix", _xtest.TestTodoUpdateMCPDisabledSprintFieldMatrix},

	{"TestTodoUpdateMCPTransportAliasMatrix", _xtest.TestTodoUpdateMCPTransportAliasMatrix},

	{"TestTodoUpdateMCPPriorityPresenceContract", _xtest.TestTodoUpdateMCPPriorityPresenceContract},

	{"TestTodoUpdateMCPRealtimeContracts", _xtest.TestTodoUpdateMCPRealtimeContracts},

	{"TestTodoUpdateMCPEmptyAndSemanticNoOpEffects", _xtest.TestTodoUpdateMCPEmptyAndSemanticNoOpEffects},

	{"TestTodoUpdateMCPPrecedenceContracts", _xtest.TestTodoUpdateMCPPrecedenceContracts},

	{"TestTodoUpdateMCPRoleAndModeContracts", _xtest.TestTodoUpdateMCPRoleAndModeContracts},

	{"TestTodoUpdateMCPTemporaryBoardSprintOmissionPreservesSprint", _xtest.TestTodoUpdateMCPTemporaryBoardSprintOmissionPreservesSprint},

	{"TestMCPTodosLinkAddAndListSuccess", _xtest.TestMCPTodosLinkAddAndListSuccess},

	{"TestMCPTodosLinkAddWithExplicitLinkType", _xtest.TestMCPTodosLinkAddWithExplicitLinkType},

	{"TestMCPTodosLinkAddRejectsSelfLink", _xtest.TestMCPTodosLinkAddRejectsSelfLink},

	{"TestMCPTodosLinkAddNotFoundForMissingTarget", _xtest.TestMCPTodosLinkAddNotFoundForMissingTarget},

	{"TestMCPTodosLinkRemoveSuccess", _xtest.TestMCPTodosLinkRemoveSuccess},

	{"TestMCPTodosLinkRemoveNotFoundForMissingLink", _xtest.TestMCPTodosLinkRemoveNotFoundForMissingLink},

	{"TestMCPTodosLinksListRequiresAuth", _xtest.TestMCPTodosLinksListRequiresAuth},

	{"TestMCPTodosLinkAddCapabilityUnavailableInAnonymousMode", _xtest.TestMCPTodosLinkAddCapabilityUnavailableInAnonymousMode},

	{"TestMCPTodosLinkAddRejectsInvalidLinkType", _xtest.TestMCPTodosLinkAddRejectsInvalidLinkType},

	{"TestMCPTodosLinksListViewerCanRead", _xtest.TestMCPTodosLinksListViewerCanRead},

	{"TestMCPTodosLinkAddViewerCannotAdd", _xtest.TestMCPTodosLinkAddViewerCannotAdd},

	{"TestMCPTodosLinkRemoveViewerCannotRemoveExistingLink", _xtest.TestMCPTodosLinkRemoveViewerCannotRemoveExistingLink},

	{"TestMCPTodosLinksNonMemberNotFound", _xtest.TestMCPTodosLinksNonMemberNotFound},

	{"TestMCPTodosLinkContributorCanMutate", _xtest.TestMCPTodosLinkContributorCanMutate},

	{"TestMCPTodosLinkAddCrossProjectTargetIsolation", _xtest.TestMCPTodosLinkAddCrossProjectTargetIsolation},

	{"TestWorkflowMutationMCPTransportAndRealtimeContracts", _xtest.TestWorkflowMutationMCPTransportAndRealtimeContracts},

	{"TestWorkflowMutationMCPSemanticValidationPrecedesAccess", _xtest.TestWorkflowMutationMCPSemanticValidationPrecedesAccess},

	{"TestWorkflowMutationMCPBoardModeContracts", _xtest.TestWorkflowMutationMCPBoardModeContracts},

	{"TestWorkflowMutationMCPUpdatePostReadFailureOccursAfterCommit", _xtest.TestWorkflowMutationMCPUpdatePostReadFailureOccursAfterCommit},

	{"TestMCPWorkflowListDefaultColumns", _xtest.TestMCPWorkflowListDefaultColumns},

	{"TestMCPWorkflowCreateSuccess", _xtest.TestMCPWorkflowCreateSuccess},

	{"TestMCPWorkflowCreatePermissionFailure", _xtest.TestMCPWorkflowCreatePermissionFailure},

	{"TestMCPWorkflowUpdateSuccess", _xtest.TestMCPWorkflowUpdateSuccess},

	{"TestMCPWorkflowUpdateInvalidColor", _xtest.TestMCPWorkflowUpdateInvalidColor},

	{"TestMCPWorkflowDeleteSuccess", _xtest.TestMCPWorkflowDeleteSuccess},

	{"TestMCPWorkflowDeleteDoneColumnRejected", _xtest.TestMCPWorkflowDeleteDoneColumnRejected},

	{"TestMCPWorkflowUpdateViewerForbidden", _xtest.TestMCPWorkflowUpdateViewerForbidden},

	{"TestMCPWorkflowDeleteViewerForbidden", _xtest.TestMCPWorkflowDeleteViewerForbidden},

	{"TestMCPWorkflowNonMemberNotFound", _xtest.TestMCPWorkflowNonMemberNotFound},

	{"TestMCPWorkflowDeleteNonEmptyColumnRejected", _xtest.TestMCPWorkflowDeleteNonEmptyColumnRejected},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

	{"FuzzParseJSONRPCMessage", _test.FuzzParseJSONRPCMessage},

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/mcp"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

