
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/eventbus"


)

var tests = []testing.InternalTest{

	{"TestFanoutPublishWithNoConsumersSucceeds", _test.TestFanoutPublishWithNoConsumersSucceeds},

	{"TestFanoutPublishPopulatesMissingIDAndTime", _test.TestFanoutPublishPopulatesMissingIDAndTime},

	{"TestFanoutPublishPreservesExistingIDAndTime", _test.TestFanoutPublishPreservesExistingIDAndTime},

	{"TestFanoutPublishDeliversToConsumersInOrder", _test.TestFanoutPublishDeliversToConsumersInOrder},

	{"TestFanoutPublishPassesContextThrough", _test.TestFanoutPublishPassesContextThrough},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/eventbus"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

