
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/publicorigin"


)

var tests = []testing.InternalTest{

	{"TestResolverOriginTrustLadder", _test.TestResolverOriginTrustLadder},

	{"TestValidateMCPResourceNarrowCanonicalization", _test.TestValidateMCPResourceNarrowCanonicalization},

	{"TestOriginAllowed", _test.TestOriginAllowed},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

	{"FuzzParseHTTPAuthority", _test.FuzzParseHTTPAuthority},

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/publicorigin"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

