
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/priority"


)

var tests = []testing.InternalTest{

	{"TestMCPMutationPrepareAuthorization", _test.TestMCPMutationPrepareAuthorization},

	{"TestMCPMutationUpdateProjection", _test.TestMCPMutationUpdateProjection},

	{"TestMCPMutationCreateAndDeleteNoProjection", _test.TestMCPMutationCreateAndDeleteNoProjection},

	{"TestRESTMutationPrepareAuthorization", _test.TestRESTMutationPrepareAuthorization},

	{"TestPreparedRESTMutationCreate", _test.TestPreparedRESTMutationCreate},

	{"TestPreparedRESTMutationUpdate", _test.TestPreparedRESTMutationUpdate},

	{"TestPreparedRESTMutationDeleteFailureSuppressesRefresh", _test.TestPreparedRESTMutationDeleteFailureSuppressesRefresh},

	{"TestBoardRefreshPublisherFuncNilIsNoop", _test.TestBoardRefreshPublisherFuncNilIsNoop},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/priority"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

