
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/useradmin"


)

var tests = []testing.InternalTest{

	{"TestMCPDeletionServicePrepareRequiresActor", _test.TestMCPDeletionServicePrepareRequiresActor},

	{"TestMCPDeletionServiceRequesterReadFailureStopsDeletion", _test.TestMCPDeletionServiceRequesterReadFailureStopsDeletion},

	{"TestMCPDeletionServiceRequiresExactOwner", _test.TestMCPDeletionServiceRequiresExactOwner},

	{"TestMCPDeletionServiceSuccessOrderAndArguments", _test.TestMCPDeletionServiceSuccessOrderAndArguments},

	{"TestMCPDeletionServiceSelfTargetOrdering", _test.TestMCPDeletionServiceSelfTargetOrdering},

	{"TestMCPDeletionServicePreservesMutationErrors", _test.TestMCPDeletionServicePreservesMutationErrors},

	{"TestMCPDeletionServicePreparedDeleteExecutesMutationAtMostOnce", _test.TestMCPDeletionServicePreparedDeleteExecutesMutationAtMostOnce},

	{"TestMCPDeletionServicePreparedValuesAndContextAreOwned", _test.TestMCPDeletionServicePreparedValuesAndContextAreOwned},

	{"TestMCPRoleServicePrepareRequiresActor", _test.TestMCPRoleServicePrepareRequiresActor},

	{"TestMCPRoleServiceRequesterReadFailure", _test.TestMCPRoleServiceRequesterReadFailure},

	{"TestMCPRoleServiceRequiresExactOwner", _test.TestMCPRoleServiceRequiresExactOwner},

	{"TestMCPRoleServiceSuccessOrderAndResult", _test.TestMCPRoleServiceSuccessOrderAndResult},

	{"TestMCPRoleServiceMutationFailureStopsProjection", _test.TestMCPRoleServiceMutationFailureStopsProjection},

	{"TestMCPRoleServicePostReadFailureClassifiesStageAndPreservesCause", _test.TestMCPRoleServicePostReadFailureClassifiesStageAndPreservesCause},

	{"TestMCPRoleServicePreparedUpdateExecutesMutationAtMostOnce", _test.TestMCPRoleServicePreparedUpdateExecutesMutationAtMostOnce},

	{"TestMCPRoleServicePreparedValuesAndContextAreOwned", _test.TestMCPRoleServicePreparedValuesAndContextAreOwned},

	{"TestCreateCommandPreservesRawValues", _test.TestCreateCommandPreservesRawValues},

	{"TestRoleChangeCommandPreservesTargetAndRole", _test.TestRoleChangeCommandPreservesTargetAndRole},

	{"TestDeleteCommandPreservesTarget", _test.TestDeleteCommandPreservesTarget},

	{"TestRESTCreationServiceForwardsRawValuesContextAndResult", _test.TestRESTCreationServiceForwardsRawValuesContextAndResult},

	{"TestRESTCreationServiceDoesNotValidateOrNormalize", _test.TestRESTCreationServiceDoesNotValidateOrNormalize},

	{"TestRESTCreationServicePreservesStoreErrorWithoutRetry", _test.TestRESTCreationServicePreservesStoreErrorWithoutRetry},

	{"TestRESTDeletionServicePrepareRequiresActor", _test.TestRESTDeletionServicePrepareRequiresActor},

	{"TestRESTDeletionServiceSuccessBindsExactValuesAndContext", _test.TestRESTDeletionServiceSuccessBindsExactValuesAndContext},

	{"TestRESTDeletionServiceSelfTargetReachesDeletionPort", _test.TestRESTDeletionServiceSelfTargetReachesDeletionPort},

	{"TestRESTDeletionServicePreservesMutationErrors", _test.TestRESTDeletionServicePreservesMutationErrors},

	{"TestRESTDeletionServicePreparedDeleteExecutesMutationAtMostOnce", _test.TestRESTDeletionServicePreparedDeleteExecutesMutationAtMostOnce},

	{"TestRESTDeletionServicePreparedValuesAndContextAreOwned", _test.TestRESTDeletionServicePreparedValuesAndContextAreOwned},

	{"TestRESTRoleServicePrepareRequiresActor", _test.TestRESTRoleServicePrepareRequiresActor},

	{"TestRESTRoleServiceSuccessOrderAndResult", _test.TestRESTRoleServiceSuccessOrderAndResult},

	{"TestRESTRoleServiceMutationFailureStopsProjection", _test.TestRESTRoleServiceMutationFailureStopsProjection},

	{"TestRESTRoleServicePostReadFailurePreservesCommittedSequence", _test.TestRESTRoleServicePostReadFailurePreservesCommittedSequence},

	{"TestRESTRoleServicePreparedUpdateExecutesMutationAtMostOnce", _test.TestRESTRoleServicePreparedUpdateExecutesMutationAtMostOnce},

	{"TestRESTRoleServicePreparedValuesAndContextAreOwned", _test.TestRESTRoleServicePreparedValuesAndContextAreOwned},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/useradmin"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

