
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/calendar/ics"


)

var tests = []testing.InternalTest{

	{"TestExpandAllDayExclusiveDTEND", _test.TestExpandAllDayExclusiveDTEND},

	{"TestExpandMidnightSpanningTimedEvent", _test.TestExpandMidnightSpanningTimedEvent},

	{"TestExpandFloatingUsesBoardTimezone", _test.TestExpandFloatingUsesBoardTimezone},

	{"TestExpandTimedEventMissingDTENDIsPointInTime", _test.TestExpandTimedEventMissingDTENDIsPointInTime},

	{"TestExpandTimedEventDURATIONStillApplies", _test.TestExpandTimedEventDURATIONStillApplies},

	{"TestExpandUnknownTZIDFailsClosed", _test.TestExpandUnknownTZIDFailsClosed},

	{"TestExpandUTCConvertedIntoBoardZoneDay", _test.TestExpandUTCConvertedIntoBoardZoneDay},

	{"TestExpandDropsCancelledAndExpandsRRuleWithException", _test.TestExpandDropsCancelledAndExpandsRRuleWithException},

	{"TestExpandDSTSpringForward", _test.TestExpandDSTSpringForward},

	{"TestExpandDSTFallBackKeepsLateEveningOnThatCivilDay", _test.TestExpandDSTFallBackKeepsLateEveningOnThatCivilDay},

	{"TestExpandAllDaySpanningDSTSpringForward", _test.TestExpandAllDaySpanningDSTSpringForward},

	{"TestExpandRecurringAllDayDoesNotLeakAcrossDST", _test.TestExpandRecurringAllDayDoesNotLeakAcrossDST},

	{"TestExpandCancelledRecurrenceExceptionOmitsThatOccurrence", _test.TestExpandCancelledRecurrenceExceptionOmitsThatOccurrence},

	{"TestExpandRDateAndExDate", _test.TestExpandRDateAndExDate},

	{"TestExpandRDateWithoutRRule", _test.TestExpandRDateWithoutRRule},

	{"TestExpandExDateWithoutRRule", _test.TestExpandExDateWithoutRRule},

	{"TestExpandMovedOverrideIntoWindow", _test.TestExpandMovedOverrideIntoWindow},

	{"TestExpandMovedOverrideOutOfWindow", _test.TestExpandMovedOverrideOutOfWindow},

	{"TestExpandMovedOverrideInsideWindowAppearsOnce", _test.TestExpandMovedOverrideInsideWindowAppearsOnce},

	{"TestExpandRejectsDenseSecondlyRecurrence", _test.TestExpandRejectsDenseSecondlyRecurrence},

	{"TestExpandRejectsOversizedBody", _test.TestExpandRejectsOversizedBody},

	{"TestExpandAcceptsBodyAboveOldTwoMiBCeiling", _test.TestExpandAcceptsBodyAboveOldTwoMiBCeiling},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/calendar/ics"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

