
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/workflow"


)

var tests = []testing.InternalTest{

	{"TestMCPMutationPrepareAccessAndRole", _test.TestMCPMutationPrepareAccessAndRole},

	{"TestPreparedMCPMutationBindsContextAndResolvedProjectID", _test.TestPreparedMCPMutationBindsContextAndResolvedProjectID},

	{"TestPreparedMCPMutationCreate", _test.TestPreparedMCPMutationCreate},

	{"TestPreparedMCPMutationUpdate", _test.TestPreparedMCPMutationUpdate},

	{"TestPreparedMCPMutationDeleteFailure", _test.TestPreparedMCPMutationDeleteFailure},

	{"TestPreparedMCPMutationUsesCancelledBoundContext", _test.TestPreparedMCPMutationUsesCancelledBoundContext},

	{"TestRESTMutationPrepareAuthorization", _test.TestRESTMutationPrepareAuthorization},

	{"TestPreparedRESTMutationBindsContextAndProjectIDByValue", _test.TestPreparedRESTMutationBindsContextAndProjectIDByValue},

	{"TestPreparedRESTMutationCreate", _test.TestPreparedRESTMutationCreate},

	{"TestPreparedRESTMutationUpdate", _test.TestPreparedRESTMutationUpdate},

	{"TestPreparedRESTMutationDeleteFailureSuppressesRefresh", _test.TestPreparedRESTMutationDeleteFailureSuppressesRefresh},

	{"TestPreparedRESTMutationUsesCancelledBoundContext", _test.TestPreparedRESTMutationUsesCancelledBoundContext},

	{"TestBoardRefreshPublisherFuncNilIsNoop", _test.TestBoardRefreshPublisherFuncNilIsNoop},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/workflow"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

