
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/db"


)

var tests = []testing.InternalTest{

	{"TestOpenCreatesParentDirectoryAndPings", _test.TestOpenCreatesParentDirectoryAndPings},

	{"TestOpenAppliesSQLitePragmas", _test.TestOpenAppliesSQLitePragmas},

	{"TestOpenConstrainsConnectionPool", _test.TestOpenConstrainsConnectionPool},

	{"TestOpenRejectsZeroBusyTimeout", _test.TestOpenRejectsZeroBusyTimeout},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/db"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

