
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/httpapi/ratelimit"


)

var tests = []testing.InternalTest{

	{"TestNormalizeEmailTrimsAndLowercases", _test.TestNormalizeEmailTrimsAndLowercases},

	{"TestAllowWithNoKeysAlwaysSucceeds", _test.TestAllowWithNoKeysAlwaysSucceeds},

	{"TestAllowHonorsIPLimit", _test.TestAllowHonorsIPLimit},

	{"TestAllowHonorsEmailLimitAcrossDifferentIPs", _test.TestAllowHonorsEmailLimitAcrossDifferentIPs},

	{"TestAllowHonorsIPLimitAcrossDifferentEmails", _test.TestAllowHonorsIPLimitAcrossDifferentEmails},

	{"TestAllowResetsExpiredWindow", _test.TestAllowResetsExpiredWindow},

	{"TestAllowCleansStaleEntries", _test.TestAllowCleansStaleEntries},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/httpapi/ratelimit"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

