
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/store"


	_xtest "scrumboy/internal/store_test"

)

var tests = []testing.InternalTest{

	{"TestCreateUserAPITokenAndGetUserByAPIToken", _test.TestCreateUserAPITokenAndGetUserByAPIToken},

	{"TestAuditEvent_InsertAndQuery", _test.TestAuditEvent_InsertAndQuery},

	{"TestAuditEvent_AppendOnly", _test.TestAuditEvent_AppendOnly},

	{"TestAuditEvent_TodoCreated", _test.TestAuditEvent_TodoCreated},

	{"TestAuditEvent_TodoUpdated_NoOpGuard", _test.TestAuditEvent_TodoUpdated_NoOpGuard},

	{"TestAuditEvent_TodoMoved", _test.TestAuditEvent_TodoMoved},

	{"TestAuditEvent_MemberAdded", _test.TestAuditEvent_MemberAdded},

	{"TestAuditEvent_AnonymousActor", _test.TestAuditEvent_AnonymousActor},

	{"TestCreateAndGetLogin2FAPending", _test.TestCreateAndGetLogin2FAPending},

	{"TestIncrementAttemptRevokesAfterMax", _test.TestIncrementAttemptRevokesAfterMax},

	{"TestRecoveryCodesAndConsume", _test.TestRecoveryCodesAndConsume},

	{"TestRecoveryCodeConcurrentConsumptionIsSingleUse", _test.TestRecoveryCodeConcurrentConsumptionIsSingleUse},

	{"TestUserIsTwoFactorActive", _test.TestUserIsTwoFactorActive},

	{"TestDerivedAuthenticationMethodsUseConfiguredIssuer", _test.TestDerivedAuthenticationMethodsUseConfiguredIssuer},

	{"TestPasswordHashEligibilityAndFirstPasswordCAS", _test.TestPasswordHashEligibilityAndFirstPasswordCAS},

	{"TestOwnerRecoveryPostureUsesEffectiveMethods", _test.TestOwnerRecoveryPostureUsesEffectiveMethods},

	{"TestOIDCLoginMetadataDoesNotChangeCanonicalOwnership", _test.TestOIDCLoginMetadataDoesNotChangeCanonicalOwnership},

	{"TestResetLocalPasswordRevokesSessionsAndPreservesOIDC", _test.TestResetLocalPasswordRevokesSessionsAndPreservesOIDC},

	{"TestFirstPasswordGrantBindingExpiryAndSingleUse", _test.TestFirstPasswordGrantBindingExpiryAndSingleUse},

	{"TestFirstPasswordFailureDoesNotConsumeRecoveryCode", _test.TestFirstPasswordFailureDoesNotConsumeRecoveryCode},

	{"TestBackupExportsAgendaFlagsAndOmitsCalendarSources", _test.TestBackupExportsAgendaFlagsAndOmitsCalendarSources},

	{"TestBackupRejectsInvalidAgendaTimezone", _test.TestBackupRejectsInvalidAgendaTimezone},

	{"TestBackupMissingAgendaColorKeepsDefault", _test.TestBackupMissingAgendaColorKeepsDefault},

	{"TestBackupRejectsInvalidAgendaColor", _test.TestBackupRejectsInvalidAgendaColor},

	{"TestImportMergeUpdate_AnonymousMode_NoHang", _test.TestImportMergeUpdate_AnonymousMode_NoHang},

	{"TestImportMergeUpdate_PreservesExistingAssignee", _test.TestImportMergeUpdate_PreservesExistingAssignee},

	{"TestImportCopy_PreservesAssigneeWhenMember", _test.TestImportCopy_PreservesAssigneeWhenMember},

	{"TestBackupAuth_ViewerCannotExport", _test.TestBackupAuth_ViewerCannotExport},

	{"TestBackupAuth_ContributorCannotExport", _test.TestBackupAuth_ContributorCannotExport},

	{"TestBackupAuth_MaintainerCanExport", _test.TestBackupAuth_MaintainerCanExport},

	{"TestBackupAuth_ViewerCannotMerge", _test.TestBackupAuth_ViewerCannotMerge},

	{"TestBackupAuth_MaintainerCanMerge", _test.TestBackupAuth_MaintainerCanMerge},

	{"TestBackupExportsTodoCreatorAttribution", _test.TestBackupExportsTodoCreatorAttribution},

	{"TestBackupTodoCreatorNullIsOmitted", _test.TestBackupTodoCreatorNullIsOmitted},

	{"TestBackupImportDoesNotTrustRawNumericCreatorID", _test.TestBackupImportDoesNotTrustRawNumericCreatorID},

	{"TestBackupMergePreservesMatchedTodoCreator", _test.TestBackupMergePreservesMatchedTodoCreator},

	{"TestResolveImportCreatedByNeverTreatsNumericEqualityAsIdentity", _test.TestResolveImportCreatedByNeverTreatsNumericEqualityAsIdentity},

	{"TestBackupExportReplace_FullIntegrity", _test.TestBackupExportReplace_FullIntegrity},

	{"TestImportMergeUpdate_MigratedSchema", _test.TestImportMergeUpdate_MigratedSchema},

	{"TestImportCreateCopy_MigratedSchema", _test.TestImportCreateCopy_MigratedSchema},

	{"TestImportPreflight_MalformedRejectedBeforeWrites", _test.TestImportPreflight_MalformedRejectedBeforeWrites},

	{"TestImportPreflight_UnauthorizedRejectedBeforeWrites", _test.TestImportPreflight_UnauthorizedRejectedBeforeWrites},

	{"TestPreviewImport_SurfacesUnknownStatusWarnings", _test.TestPreviewImport_SurfacesUnknownStatusWarnings},

	{"TestPreviewImport_ValidCustomWorkflowColumn_NoWarning", _test.TestPreviewImport_ValidCustomWorkflowColumn_NoWarning},

	{"TestPreviewImport_InvalidColumn_Warning", _test.TestPreviewImport_InvalidColumn_Warning},

	{"TestImportPreflight_InvalidReferencesRejectedBeforeWrites", _test.TestImportPreflight_InvalidReferencesRejectedBeforeWrites},

	{"TestImportPreflight_InvalidWorkflowSprintRejected", _test.TestImportPreflight_InvalidWorkflowSprintRejected},

	{"TestExportImportRoundTrip_DefaultSprintWeeks", _test.TestExportImportRoundTrip_DefaultSprintWeeks},

	{"TestExportImportRoundTrip_WorkflowColumns", _test.TestExportImportRoundTrip_WorkflowColumns},

	{"TestExportImportRoundTrip_Sprints", _test.TestExportImportRoundTrip_Sprints},

	{"TestImportMerge_ExistingCustomWorkflow", _test.TestImportMerge_ExistingCustomWorkflow},

	{"TestImportMerge_WorkflowReplacementRejectedWhenStrandedTodos", _test.TestImportMerge_WorkflowReplacementRejectedWhenStrandedTodos},

	{"TestImportMerge_WorkflowReplacementAllowedWhenAllTodosInBackup", _test.TestImportMerge_WorkflowReplacementAllowedWhenAllTodosInBackup},

	{"TestImportMerge_SprintNumberConflictUpdatesExisting", _test.TestImportMerge_SprintNumberConflictUpdatesExisting},

	{"TestImportMerge_SprintNumberConflict_AddsNewAndLeavesExisting", _test.TestImportMerge_SprintNumberConflict_AddsNewAndLeavesExisting},

	{"TestExportImportRoundTrip_Wall_Replace", _test.TestExportImportRoundTrip_Wall_Replace},

	{"TestExportImportRoundTrip_Wall_Merge_ReplacesWithBackup", _test.TestExportImportRoundTrip_Wall_Merge_ReplacesWithBackup},

	{"TestExportImportRoundTrip_Wall_Merge_PreservesWhenBackupHasNoWall", _test.TestExportImportRoundTrip_Wall_Merge_PreservesWhenBackupHasNoWall},

	{"TestExportImportRoundTrip_Wall_Copy", _test.TestExportImportRoundTrip_Wall_Copy},

	{"TestExportImport_Wall_EmptyWallOmitsField", _test.TestExportImport_Wall_EmptyWallOmitsField},

	{"TestMigration012_OnlyOneUniqueSlugIndex", _test.TestMigration012_OnlyOneUniqueSlugIndex},

	{"TestPriorityExportPresenceWireContract", _test.TestPriorityExportPresenceWireContract},

	{"TestExportEmitsExplicitPriorityPresenceAndRejectsMissingDefinitions", _test.TestExportEmitsExplicitPriorityPresenceAndRejectsMissingDefinitions},

	{"TestPriorityImportDefinitionValidationParity", _test.TestPriorityImportDefinitionValidationParity},

	{"TestImportMergePriorityReplacementIntegrity", _test.TestImportMergePriorityReplacementIntegrity},

	{"TestBackupPreservesSprintsEnabledAndOlderPayloadDefaultsEnabled", _test.TestBackupPreservesSprintsEnabledAndOlderPayloadDefaultsEnabled},

	{"TestBackupExport_OneEntryPerCanonicalName", _test.TestBackupExport_OneEntryPerCanonicalName},

	{"TestBulkUpsertTags_DedupesLegacyDuplicateNames", _test.TestBulkUpsertTags_DedupesLegacyDuplicateNames},

	{"TestBulkUpsertTags_RejectsInvalidTagName", _test.TestBulkUpsertTags_RejectsInvalidTagName},

	{"TestBackupExport_RejectsUncanonicalizableTagName", _test.TestBackupExport_RejectsUncanonicalizableTagName},

	{"TestDurableBoardRead_DoesNotRefreshLastActivityAt", _test.TestDurableBoardRead_DoesNotRefreshLastActivityAt},

	{"TestUpdateBoardActivity_ExtendsExpiresAt90DaysFromNow", _test.TestUpdateBoardActivity_ExtendsExpiresAt90DaysFromNow},

	{"TestExpiringBoardRead_RefreshesLastActivityWhenStale", _test.TestExpiringBoardRead_RefreshesLastActivityWhenStale},

	{"TestParseAssigneeFilter", _test.TestParseAssigneeFilter},

	{"TestAssigneeFilterArgs_InvalidInternalStateFailsClosed", _test.TestAssigneeFilterArgs_InvalidInternalStateFailsClosed},

	{"TestGetBoard_AssigneeFilter", _test.TestGetBoard_AssigneeFilter},

	{"TestListTodosForBoardLane_AssigneeFilter", _test.TestListTodosForBoardLane_AssigneeFilter},

	{"TestGetBoardPaged_AssigneeFilterSoftCapFallback", _test.TestGetBoardPaged_AssigneeFilterSoftCapFallback},

	{"TestGetBoardPaged_AssigneeSprintTagSearchComposition", _test.TestGetBoardPaged_AssigneeSprintTagSearchComposition},

	{"TestParsePriorityFilter", _test.TestParsePriorityFilter},

	{"TestPriorityFilterArgs_InvalidInternalStateFailsClosed", _test.TestPriorityFilterArgs_InvalidInternalStateFailsClosed},

	{"TestGetBoard_PriorityFilter", _test.TestGetBoard_PriorityFilter},

	{"TestListTodosForBoardLane_PriorityFilter", _test.TestListTodosForBoardLane_PriorityFilter},

	{"TestGetBoard_NoHang", _test.TestGetBoard_NoHang},

	{"TestParseSortOrder", _test.TestParseSortOrder},

	{"TestGetBoard_SortOrder", _test.TestGetBoard_SortOrder},

	{"TestListTodosForBoardLane_SortOrderPagination", _test.TestListTodosForBoardLane_SortOrderPagination},

	{"TestGetBoard_SearchMatchesTitle", _test.TestGetBoard_SearchMatchesTitle},

	{"TestGetBoard_SearchMatchesBody", _test.TestGetBoard_SearchMatchesBody},

	{"TestGetBoard_SearchCaseInsensitive", _test.TestGetBoard_SearchCaseInsensitive},

	{"TestGetBoard_SearchSubstringOnly", _test.TestGetBoard_SearchSubstringOnly},

	{"TestGetBoard_TagAndSearchAND", _test.TestGetBoard_TagAndSearchAND},

	{"TestParseLaneCursor", _test.TestParseLaneCursor},

	{"TestListTodosForBoardLane_Pagination", _test.TestListTodosForBoardLane_Pagination},

	{"TestListTodosForBoardLane_PaginationBoundaryContract", _test.TestListTodosForBoardLane_PaginationBoundaryContract},

	{"TestListTodosForBoardLane_TagFilterPaginationInvariants", _test.TestListTodosForBoardLane_TagFilterPaginationInvariants},

	{"TestListTodosForBoardLane_TagFilter", _test.TestListTodosForBoardLane_TagFilter},

	{"TestGetBoardPaged_ReturnsColumnsMeta", _test.TestGetBoardPaged_ReturnsColumnsMeta},

	{"TestUpdateProjectAgendaSettingsTimezoneChangeDeletesSnapshot", _test.TestUpdateProjectAgendaSettingsTimezoneChangeDeletesSnapshot},

	{"TestUpdateProjectAgendaSettingsTimezoneChangeRollsBackWhenSnapshotDeleteFails", _test.TestUpdateProjectAgendaSettingsTimezoneChangeRollsBackWhenSnapshotDeleteFails},

	{"TestUpdateCalendarSourceURLChangeDeletesSnapshot", _test.TestUpdateCalendarSourceURLChangeDeletesSnapshot},

	{"TestUpdateCalendarSourceURLChangeRollsBackWhenSnapshotDeleteFails", _test.TestUpdateCalendarSourceURLChangeRollsBackWhenSnapshotDeleteFails},

	{"TestUpdateProjectBoardSettingsInvalidTimezoneLeavesSprintFieldsUnchanged", _test.TestUpdateProjectBoardSettingsInvalidTimezoneLeavesSprintFieldsUnchanged},

	{"TestUpdateProjectBoardSettingsUnchangedSprintSkipsAudit", _test.TestUpdateProjectBoardSettingsUnchangedSprintSkipsAudit},

	{"TestUpdateProjectBoardSettingsTimezoneChangeDeletesSnapshot", _test.TestUpdateProjectBoardSettingsTimezoneChangeDeletesSnapshot},

	{"TestCalendarFeedSnapshotUpsertTouchAndLastGood", _test.TestCalendarFeedSnapshotUpsertTouchAndLastGood},

	{"TestDeleteCalendarFeedSnapshotsSourceAndProject", _test.TestDeleteCalendarFeedSnapshotsSourceAndProject},

	{"TestCalendarFeedSnapshotWritesRequireCurrentConfig", _test.TestCalendarFeedSnapshotWritesRequireCurrentConfig},

	{"TestConcurrentCalendarSourceCreateAtLimitReturnsDomainError", _test.TestConcurrentCalendarSourceCreateAtLimitReturnsDomainError},

	{"TestCalendarSourceEncryptDecryptAndUniqueness", _test.TestCalendarSourceEncryptDecryptAndUniqueness},

	{"TestCalendarSourceHostKindFenceDoesNotBumpUpdatedAt", _test.TestCalendarSourceHostKindFenceDoesNotBumpUpdatedAt},

	{"TestEncryptSecretWithoutKey", _test.TestEncryptSecretWithoutKey},

	{"TestCalendarSourceEncryptSecretUsesAESGCMFraming", _test.TestCalendarSourceEncryptSecretUsesAESGCMFraming},

	{"TestProjectAgendaColorPersistsAndValidates", _test.TestProjectAgendaColorPersistsAndValidates},

	{"TestUpdateProjectAgendaSettingsRejectsInvalidIANATimezone", _test.TestUpdateProjectAgendaSettingsRejectsInvalidIANATimezone},

	{"TestClaimTemporaryBoard_ExpiredNotClaimable_StoreEnforcesCondition", _test.TestClaimTemporaryBoard_ExpiredNotClaimable_StoreEnforcesCondition},

	{"TestClaimTemporaryBoard_PromotesExistingMembershipToMaintainer", _test.TestClaimTemporaryBoard_PromotesExistingMembershipToMaintainer},

	{"TestCountTodosByColumnKey_EmptyProject", _test.TestCountTodosByColumnKey_EmptyProject},

	{"TestCountTodosByColumnKey_MultipleLanes", _test.TestCountTodosByColumnKey_MultipleLanes},

	{"TestCountTodosByColumnKey_MissingKeyMeansZero", _test.TestCountTodosByColumnKey_MissingKeyMeansZero},

	{"TestDashboardSummary_CustomDoneKey", _test.TestDashboardSummary_CustomDoneKey},

	{"TestDashboardSummary_CustomWIPKeys_AllNonDoneCountAsWipWithoutLegacySplit", _test.TestDashboardSummary_CustomWIPKeys_AllNonDoneCountAsWipWithoutLegacySplit},

	{"TestDashboardSummary_DefaultWIPKeys_PreserveLegacySplit", _test.TestDashboardSummary_DefaultWIPKeys_PreserveLegacySplit},

	{"TestDashboardSummary_UnassignedTodoExcludedEvenInActiveSprint", _test.TestDashboardSummary_UnassignedTodoExcludedEvenInActiveSprint},

	{"TestDashboardSummary_AssignedTodoInActiveSprintCountsAsSprint", _test.TestDashboardSummary_AssignedTodoInActiveSprintCountsAsSprint},

	{"TestDashboardSummary_AssignedTodoInPlannedSprintCountsAsBacklog", _test.TestDashboardSummary_AssignedTodoInPlannedSprintCountsAsBacklog},

	{"TestListDashboardTodos_CustomDoneKeyExcludesDone", _test.TestListDashboardTodos_CustomDoneKeyExcludesDone},

	{"TestListDashboardTodos_BoardOrderByProjectID", _test.TestListDashboardTodos_BoardOrderByProjectID},

	{"TestListDashboardTodos_BoardOrderLanesAndRankTiebreaker", _test.TestListDashboardTodos_BoardOrderLanesAndRankTiebreaker},

	{"TestListDashboardTodos_BoardCursorRoundTrip", _test.TestListDashboardTodos_BoardCursorRoundTrip},

	{"TestListDashboardTodos_CursorSortMismatch", _test.TestListDashboardTodos_CursorSortMismatch},

	{"TestGetDefaultBoardOrgSetting_UnsetIsNotCustomized", _test.TestGetDefaultBoardOrgSetting_UnsetIsNotCustomized},

	{"TestSetDefaultBoardOrgSetting_RequiresAdminOrOwner", _test.TestSetDefaultBoardOrgSetting_RequiresAdminOrOwner},

	{"TestSetDefaultBoardOrgSetting_AdminWithoutProjectMembershipRejected", _test.TestSetDefaultBoardOrgSetting_AdminWithoutProjectMembershipRejected},

	{"TestSetDefaultBoardOrgSetting_AdminWhoIsMaintainerSucceeds", _test.TestSetDefaultBoardOrgSetting_AdminWhoIsMaintainerSucceeds},

	{"TestSetDefaultBoardOrgSetting_RejectsMissingProject", _test.TestSetDefaultBoardOrgSetting_RejectsMissingProject},

	{"TestSetDefaultBoardOrgSetting_RejectsTemporaryBoard", _test.TestSetDefaultBoardOrgSetting_RejectsTemporaryBoard},

	{"TestSetDefaultBoardOrgSetting_RejectsAnonymousBoard", _test.TestSetDefaultBoardOrgSetting_RejectsAnonymousBoard},

	{"TestCreateUser_SeedsDefaultBoardMembership", _test.TestCreateUser_SeedsDefaultBoardMembership},

	{"TestCreateUser_NoDefaultBoardConfiguredSeedsNothing", _test.TestCreateUser_NoDefaultBoardConfiguredSeedsNothing},

	{"TestCreateUser_ExistingUsersUnaffectedByLaterDefaultBoardChange", _test.TestCreateUser_ExistingUsersUnaffectedByLaterDefaultBoardChange},

	{"TestCreateUserOIDC_SeedsDefaultBoardMembership", _test.TestCreateUserOIDC_SeedsDefaultBoardMembership},

	{"TestCreateUserOIDC_SeedsDefaultBoardMembershipAtConfiguredRole", _test.TestCreateUserOIDC_SeedsDefaultBoardMembershipAtConfiguredRole},

	{"TestBootstrapUser_NotSeededIntoDefaultBoard", _test.TestBootstrapUser_NotSeededIntoDefaultBoard},

	{"TestCreateUser_DeletedDefaultBoardProjectSkipsSeedingWithoutFailingCreation", _test.TestCreateUser_DeletedDefaultBoardProjectSkipsSeedingWithoutFailingCreation},

	{"TestCreateUser_StaleNonDurableDefaultBoardSkipsSeeding", _test.TestCreateUser_StaleNonDurableDefaultBoardSkipsSeeding},

	{"TestCreateUser_SeedsDefaultBoardMembershipAtConfiguredRole", _test.TestCreateUser_SeedsDefaultBoardMembershipAtConfiguredRole},

	{"TestSetDefaultBoardOrgSetting_RejectsInvalidRole", _test.TestSetDefaultBoardOrgSetting_RejectsInvalidRole},

	{"TestSetDefaultBoardOrgSetting_RejectsDeprecatedRoles", _test.TestSetDefaultBoardOrgSetting_RejectsDeprecatedRoles},

	{"TestClearDefaultBoardOrgSetting_ResetsRoleToViewerFallback", _test.TestClearDefaultBoardOrgSetting_ResetsRoleToViewerFallback},

	{"TestDoneAt_MoveTodo_IntoDONE", _test.TestDoneAt_MoveTodo_IntoDONE},

	{"TestDoneAt_MoveTodo_DONEtoDONE_NoChange", _test.TestDoneAt_MoveTodo_DONEtoDONE_NoChange},

	{"TestDoneAt_MoveTodo_ReopenPreserves", _test.TestDoneAt_MoveTodo_ReopenPreserves},

	{"TestDoneAt_CreateTodo_StatusDone", _test.TestDoneAt_CreateTodo_StatusDone},

	{"TestParseEmailNotifyPref", _test.TestParseEmailNotifyPref},

	{"TestParseEmailNotifyPrefRejectsInvalidJSON", _test.TestParseEmailNotifyPrefRejectsInvalidJSON},

	{"TestEmailNotifyPrefCanonicalJSON", _test.TestEmailNotifyPrefCanonicalJSON},

	{"TestValidateEmailNotifyPrefJSON", _test.TestValidateEmailNotifyPrefJSON},

	{"TestListProjects_IncludesAuthenticatedTemporaryBoardForInvitedMember", _test.TestListProjects_IncludesAuthenticatedTemporaryBoardForInvitedMember},

	{"TestListProjects_ExcludesAnonymousTemporaryBoardEvenWithOrphanMembership", _test.TestListProjects_ExcludesAnonymousTemporaryBoardEvenWithOrphanMembership},

	{"TestUpdateProjectMemberRole_MaintainerPromotesContributor", _test.TestUpdateProjectMemberRole_MaintainerPromotesContributor},

	{"TestUpdateProjectMemberRole_MaintainerDemotesOtherMaintainer", _test.TestUpdateProjectMemberRole_MaintainerDemotesOtherMaintainer},

	{"TestUpdateProjectMemberRole_CannotDemoteSelf", _test.TestUpdateProjectMemberRole_CannotDemoteSelf},

	{"TestUpdateProjectMemberRole_ContributorUnauthorized", _test.TestUpdateProjectMemberRole_ContributorUnauthorized},

	{"TestUpdateProjectMemberRole_TargetNotMember", _test.TestUpdateProjectMemberRole_TargetNotMember},

	{"TestUpdateProjectMemberRole_InvalidRole", _test.TestUpdateProjectMemberRole_InvalidRole},

	{"TestUpdateProjectMemberRole_DemoteToViewer", _test.TestUpdateProjectMemberRole_DemoteToViewer},

	{"TestUpdateProjectMemberRole_LastMaintainerCannotDemoteToViewer", _test.TestUpdateProjectMemberRole_LastMaintainerCannotDemoteToViewer},

	{"TestUpdateProjectMemberRole_NoOpUnchanged", _test.TestUpdateProjectMemberRole_NoOpUnchanged},

	{"TestMobileOIDCFlowPersistsOnlyHashedStateAndChallenge", _test.TestMobileOIDCFlowPersistsOnlyHashedStateAndChallenge},

	{"TestMobileOIDCWrongProofDoesNotConsumeGrant", _test.TestMobileOIDCWrongProofDoesNotConsumeGrant},

	{"TestMobileOIDCExpiredGrantFailsClosed", _test.TestMobileOIDCExpiredGrantFailsClosed},

	{"TestMobileOIDCConcurrentExchangeCreatesExactlyOneSession", _test.TestMobileOIDCConcurrentExchangeCreatesExactlyOneSession},

	{"TestRedeemOAuthAuthCodeFailedValidationDoesNotBurnGrant", _test.TestRedeemOAuthAuthCodeFailedValidationDoesNotBurnGrant},

	{"TestConsumeOAuthRefreshTokenFailedValidationDoesNotBurnGrant", _test.TestConsumeOAuthRefreshTokenFailedValidationDoesNotBurnGrant},

	{"TestOAuthAccessTokenRequiresExpectedResource", _test.TestOAuthAccessTokenRequiresExpectedResource},

	{"TestConcurrentOAuthRedemptionAllowsExactlyOneSuccess", _test.TestConcurrentOAuthRedemptionAllowsExactlyOneSuccess},

	{"TestRedeemOAuthAuthCodeAndIssueRollsBackWhenTokenInsertFails", _test.TestRedeemOAuthAuthCodeAndIssueRollsBackWhenTokenInsertFails},

	{"TestConsumeOAuthRefreshTokenAndIssueRollsBackWhenTokenInsertFails", _test.TestConsumeOAuthRefreshTokenAndIssueRollsBackWhenTokenInsertFails},

	{"TestDeleteExpiredOAuthArtifacts", _test.TestDeleteExpiredOAuthArtifacts},

	{"TestMoveTodo_ReorderWithinColumn", _test.TestMoveTodo_ReorderWithinColumn},

	{"TestMoveTodo_MoveAcrossColumns", _test.TestMoveTodo_MoveAcrossColumns},

	{"TestMoveTodo_RebalanceWhenGapTooSmall", _test.TestMoveTodo_RebalanceWhenGapTooSmall},

	{"TestMoveTodo_MoveToTopRepeatedly_NoNegativeRank", _test.TestMoveTodo_MoveToTopRepeatedly_NoNegativeRank},

	{"TestMoveTodo_MoveToTopProducesPositiveRank", _test.TestMoveTodo_MoveToTopProducesPositiveRank},

	{"TestMoveTodo_FilteredVisibleSameColumn", _test.TestMoveTodo_FilteredVisibleSameColumn},

	{"TestMoveTodo_FilteredTopBoundaryAcrossColumns", _test.TestMoveTodo_FilteredTopBoundaryAcrossColumns},

	{"TestMoveTodo_FilteredBottomBoundaryWithinColumn", _test.TestMoveTodo_FilteredBottomBoundaryWithinColumn},

	{"TestMoveTodo_FilteredBottomBoundaryAcrossColumns", _test.TestMoveTodo_FilteredBottomBoundaryAcrossColumns},

	{"TestMoveTodo_FilteredMoveToEmptyTargetColumn", _test.TestMoveTodo_FilteredMoveToEmptyTargetColumn},

	{"TestCreateUser_UnsetOrgDefault_CreatesNoRow", _test.TestCreateUser_UnsetOrgDefault_CreatesNoRow},

	{"TestCreateUser_OrgDefaultSet_SeedsOrgDefaultProvenance", _test.TestCreateUser_OrgDefaultSet_SeedsOrgDefaultProvenance},

	{"TestSetUserPreference_FlipsInheritedRowToUser", _test.TestSetUserPreference_FlipsInheritedRowToUser},

	{"TestClearEmailNotifyOrgDefault_ResetsAndLeavesUsersUntouched", _test.TestClearEmailNotifyOrgDefault_ResetsAndLeavesUsersUntouched},

	{"TestBootstrapUser_CreatesNoRow", _test.TestBootstrapUser_CreatesNoRow},

	{"TestCreateUserOIDC_UnsetOrgDefault_CreatesNoRow", _test.TestCreateUserOIDC_UnsetOrgDefault_CreatesNoRow},

	{"TestCreateUser_CorruptOrgDefault_SkipsSeedingWithoutFailing", _test.TestCreateUser_CorruptOrgDefault_SkipsSeedingWithoutFailing},

	{"TestCreateUser_ExplicitColumnTrigger_NoOverrideSucceeds", _test.TestCreateUser_ExplicitColumnTrigger_NoOverrideSucceeds},

	{"TestCreateUser_ExplicitColumnTrigger_OverrideWins", _test.TestCreateUser_ExplicitColumnTrigger_OverrideWins},

	{"TestCreateUser_OrgDefaultQueryErrorIsReturned", _test.TestCreateUser_OrgDefaultQueryErrorIsReturned},

	{"TestOrgDefaultChange_LeavesUserAndLegacyRowsUntouched", _test.TestOrgDefaultChange_LeavesUserAndLegacyRowsUntouched},

	{"TestGetEmailNotifyOrgDefault_UnsetFallsBackToHardcodedDefault", _test.TestGetEmailNotifyOrgDefault_UnsetFallsBackToHardcodedDefault},

	{"TestSetEmailNotifyOrgDefault_RequiresAdminOrOwner", _test.TestSetEmailNotifyOrgDefault_RequiresAdminOrOwner},

	{"TestSetEmailNotifyOrgDefault_RejectsInvalidJSON", _test.TestSetEmailNotifyOrgDefault_RejectsInvalidJSON},

	{"TestCreateUser_SeedsCurrentOrgDefault", _test.TestCreateUser_SeedsCurrentOrgDefault},

	{"TestCreateUser_ExistingUsersUnaffectedByLaterOrgDefaultChange", _test.TestCreateUser_ExistingUsersUnaffectedByLaterOrgDefaultChange},

	{"TestCreateUserOIDC_SeedsCurrentOrgDefault", _test.TestCreateUserOIDC_SeedsCurrentOrgDefault},

	{"TestBootstrapUser_NotSeededFromOrgDefault", _test.TestBootstrapUser_NotSeededFromOrgDefault},

	{"TestSetUserPreference_TagColors_RejectsInvalid", _test.TestSetUserPreference_TagColors_RejectsInvalid},

	{"TestSetUserPreference_CardsPerLane_AllowlistOnly", _test.TestSetUserPreference_CardsPerLane_AllowlistOnly},

	{"TestSetUserPreference_EmailNotifications_RoundTripAndRejectsInvalid", _test.TestSetUserPreference_EmailNotifications_RoundTripAndRejectsInvalid},

	{"TestConcurrentPriorityCreateAllocatesDistinctKeysAndPositions", _test.TestConcurrentPriorityCreateAllocatesDistinctKeysAndPositions},

	{"TestConcurrentPriorityCreateAtLimitReturnsDomainError", _test.TestConcurrentPriorityCreateAtLimitReturnsDomainError},

	{"TestConcurrentPriorityDeleteVersusTodoAssignmentIsLinear", _test.TestConcurrentPriorityDeleteVersusTodoAssignmentIsLinear},

	{"TestConcurrentPriorityDeleteVersusUpdateIsLinear", _test.TestConcurrentPriorityDeleteVersusUpdateIsLinear},

	{"TestConcurrentPriorityDeletesRemainContiguous", _test.TestConcurrentPriorityDeletesRemainContiguous},

	{"TestImportPriorityConcurrentAssignmentIsLinear", _test.TestImportPriorityConcurrentAssignmentIsLinear},

	{"TestCreateProject_SeedsDefaultPriorities", _test.TestCreateProject_SeedsDefaultPriorities},

	{"TestCreateAnonymousBoardPrioritySeedFailureRollsBackProjectAndAudit", _test.TestCreateAnonymousBoardPrioritySeedFailureRollsBackProjectAndAudit},

	{"TestPriorityTierValidationLimits", _test.TestPriorityTierValidationLimits},

	{"TestGetProjectPriorities_IsReadOnlyWhenDefinitionsAreMissing", _test.TestGetProjectPriorities_IsReadOnlyWhenDefinitionsAreMissing},

	{"TestAddPriorityTier_AppendsAtEnd", _test.TestAddPriorityTier_AppendsAtEnd},

	{"TestAddPriorityTier_RejectsEmptyName", _test.TestAddPriorityTier_RejectsEmptyName},

	{"TestUpdatePriorityTier_ChangesNameAndColor", _test.TestUpdatePriorityTier_ChangesNameAndColor},

	{"TestUpdatePriorityTier_RejectsInvalidColor", _test.TestUpdatePriorityTier_RejectsInvalidColor},

	{"TestUpdatePriorityTier_NotFound", _test.TestUpdatePriorityTier_NotFound},

	{"TestDeletePriorityTier_ResequencesPositions", _test.TestDeletePriorityTier_ResequencesPositions},

	{"TestDeletePriorityTier_BlockedWhenInUse", _test.TestDeletePriorityTier_BlockedWhenInUse},

	{"TestDeletePriorityTier_BlockedWhenLastTier", _test.TestDeletePriorityTier_BlockedWhenLastTier},

	{"TestDeletePriorityTier_NotFound", _test.TestDeletePriorityTier_NotFound},

	{"TestCreateTodo_ValidatesPriorityKey", _test.TestCreateTodo_ValidatesPriorityKey},

	{"TestUpdateTodoByLocalID_ChangesPriorityKey", _test.TestUpdateTodoByLocalID_ChangesPriorityKey},

	{"TestUpdateTodo_ValidatesPriorityKey", _test.TestUpdateTodo_ValidatesPriorityKey},

	{"TestProjectLifecycleStoreDurableCreationContracts", _test.TestProjectLifecycleStoreDurableCreationContracts},

	{"TestProjectLifecycleStoreDurableCreationRollsBackAllState", _test.TestProjectLifecycleStoreDurableCreationRollsBackAllState},

	{"TestProjectLifecycleStoreAnonymousCreationCommitBoundaries", _test.TestProjectLifecycleStoreAnonymousCreationCommitBoundaries},

	{"TestProjectLifecycleStorePatchRollbackAndSameValueAudits", _test.TestProjectLifecycleStorePatchRollbackAndSameValueAudits},

	{"TestProjectLifecycleStoreDeletionRollbackAndSnapshot", _test.TestProjectLifecycleStoreDeletionRollbackAndSnapshot},

	{"TestProjectLifecycleStoreClaimConditionalAuthorityAndRollback", _test.TestProjectLifecycleStoreClaimConditionalAuthorityAndRollback},

	{"TestCreateAnonymousBoard_InitialExpiresAt90Days", _test.TestCreateAnonymousBoard_InitialExpiresAt90Days},

	{"TestDeleteProject_AnonymousTempBoard_Blocked", _test.TestDeleteProject_AnonymousTempBoard_Blocked},

	{"TestDeleteProject_ReturnsCommittedNotificationSnapshot", _test.TestDeleteProject_ReturnsCommittedNotificationSnapshot},

	{"TestExpiredTemporaryProject_BoardReadDenied", _test.TestExpiredTemporaryProject_BoardReadDenied},

	{"TestExpiredTemporaryProject_TodoCreateDenied", _test.TestExpiredTemporaryProject_TodoCreateDenied},

	{"TestDeleteExpiredProjects_AuthenticatedTempBoard", _test.TestDeleteExpiredProjects_AuthenticatedTempBoard},

	{"TestDeleteExpiredProjects_AuditEventsMayRemain", _test.TestDeleteExpiredProjects_AuditEventsMayRemain},

	{"TestDeleteExpiredProjects_CascadesTodos", _test.TestDeleteExpiredProjects_CascadesTodos},

	{"TestImportReplace_ForbiddenInAnonymousMode", _test.TestImportReplace_ForbiddenInAnonymousMode},

	{"TestCheckCanManageProject_durableMaintainerAllowed", _test.TestCheckCanManageProject_durableMaintainerAllowed},

	{"TestCheckCanManageProject_durableViewerForbidden", _test.TestCheckCanManageProject_durableViewerForbidden},

	{"TestCheckCanManageProject_durableNonMemberNotFound", _test.TestCheckCanManageProject_durableNonMemberNotFound},

	{"TestCheckCanManageProject_temporaryBoardOwnerAllowed", _test.TestCheckCanManageProject_temporaryBoardOwnerAllowed},

	{"TestCheckCanManageProject_temporaryBoardOtherUserForbidden", _test.TestCheckCanManageProject_temporaryBoardOtherUserForbidden},

	{"TestCheckCanManageProject_anonymousBoardNotFound", _test.TestCheckCanManageProject_anonymousBoardNotFound},

	{"TestUpdateProjectPatch_temporaryBoardOwnerSuccess", _test.TestUpdateProjectPatch_temporaryBoardOwnerSuccess},

	{"TestDeleteProject_temporaryBoardOwnerSuccess", _test.TestDeleteProject_temporaryBoardOwnerSuccess},

	{"TestUpdateProjectName_temporaryBoardOwnerSuccess", _test.TestUpdateProjectName_temporaryBoardOwnerSuccess},

	{"TestUpdateProjectName_temporaryBoardNonOwnerForbidden", _test.TestUpdateProjectName_temporaryBoardNonOwnerForbidden},

	{"TestUpdateProjectName_anonymousBoardRenameUnchanged", _test.TestUpdateProjectName_anonymousBoardRenameUnchanged},

	{"TestUpdateProjectImage_temporaryBoardOwnerSuccess", _test.TestUpdateProjectImage_temporaryBoardOwnerSuccess},

	{"TestUpdateProjectImage_temporaryBoardNonOwnerForbidden", _test.TestUpdateProjectImage_temporaryBoardNonOwnerForbidden},

	{"TestUpdateProjectImage_anonymousBoardNotFound", _test.TestUpdateProjectImage_anonymousBoardNotFound},

	{"TestUpdateProjectDefaultSprintWeeks_temporaryBoardOwnerSuccess", _test.TestUpdateProjectDefaultSprintWeeks_temporaryBoardOwnerSuccess},

	{"TestUpdateProjectDefaultSprintWeeks_temporaryBoardNonOwnerForbidden", _test.TestUpdateProjectDefaultSprintWeeks_temporaryBoardNonOwnerForbidden},

	{"TestUpdateProjectDefaultSprintWeeks_anonymousBoardNotFound", _test.TestUpdateProjectDefaultSprintWeeks_anonymousBoardNotFound},

	{"TestUpdateProjectName_durableViewerForbidden", _test.TestUpdateProjectName_durableViewerForbidden},

	{"TestUpdateProjectDefaultSprintWeeks_temporaryBoardNonOwnerInvalidWeeksForbidden", _test.TestUpdateProjectDefaultSprintWeeks_temporaryBoardNonOwnerInvalidWeeksForbidden},

	{"TestUpdateProjectDefaultSprintWeeks_durableNonMemberInvalidWeeksNotFound", _test.TestUpdateProjectDefaultSprintWeeks_durableNonMemberInvalidWeeksNotFound},

	{"TestUpdateProjectDefaultSprintWeeks_temporaryBoardOwnerInvalidWeeksValidation", _test.TestUpdateProjectDefaultSprintWeeks_temporaryBoardOwnerInvalidWeeksValidation},

	{"TestUpdateProjectDefaultSprintWeeks_durableMaintainerInvalidWeeksValidation", _test.TestUpdateProjectDefaultSprintWeeks_durableMaintainerInvalidWeeksValidation},

	{"TestUpdateProjectDefaultSprintWeeks_durableMaintainerValidWeeksSuccess", _test.TestUpdateProjectDefaultSprintWeeks_durableMaintainerValidWeeksSuccess},

	{"TestUpdateProjectPatch_twoFieldsSuccess", _test.TestUpdateProjectPatch_twoFieldsSuccess},

	{"TestUpdateProjectPatch_invalidWeeksLeavesNameUnchanged", _test.TestUpdateProjectPatch_invalidWeeksLeavesNameUnchanged},

	{"TestGenerateSlugFromName", _test.TestGenerateSlugFromName},

	{"TestCreateProject_SlugCollisionAddsSuffix", _test.TestCreateProject_SlugCollisionAddsSuffix},

	{"TestRewriteDurableProjectSlugs_RewritesFromLegacyRandom", _test.TestRewriteDurableProjectSlugs_RewritesFromLegacyRandom},

	{"TestSprintDefinitionCreate_InsertRemainsCommittedWhenReturnReadFails", _test.TestSprintDefinitionCreate_InsertRemainsCommittedWhenReturnReadFails},

	{"TestSprintDefinitionStoreOwnsDefinitionValidationByState", _test.TestSprintDefinitionStoreOwnsDefinitionValidationByState},

	{"TestSprintLifecycleStoreActivateContract", _test.TestSprintLifecycleStoreActivateContract},

	{"TestSprintLifecycleStoreActivateReplacesCurrentAtomically", _test.TestSprintLifecycleStoreActivateReplacesCurrentAtomically},

	{"TestSprintLifecycleStoreActivateRollbackRestoresPriorActive", _test.TestSprintLifecycleStoreActivateRollbackRestoresPriorActive},

	{"TestSprintLifecycleStoreCloseCurrentContract", _test.TestSprintLifecycleStoreCloseCurrentContract},

	{"TestSprintLifecycleStoreDeleteContract", _test.TestSprintLifecycleStoreDeleteContract},

	{"TestSprintLifecycleStoreDeleteDetachesTodos", _test.TestSprintLifecycleStoreDeleteDetachesTodos},

	{"TestSprintLifecycleStoreCanceledActivationDoesNotPartiallyTransition", _test.TestSprintLifecycleStoreCanceledActivationDoesNotPartiallyTransition},

	{"TestSprintCapabilitySerializationDisableFirstRejectsSprintMutations", _test.TestSprintCapabilitySerializationDisableFirstRejectsSprintMutations},

	{"TestSprintCapabilitySerializationMutationFirstCommitsBeforeDisable", _test.TestSprintCapabilitySerializationMutationFirstCommitsBeforeDisable},

	{"TestSprintCapabilitySerializationDisableFirstRejectsTodoSprintAssignment", _test.TestSprintCapabilitySerializationDisableFirstRejectsTodoSprintAssignment},

	{"TestConcurrentSprintCreationAllocatesDistinctNumbers", _test.TestConcurrentSprintCreationAllocatesDistinctNumbers},

	{"TestSprintsDisabledCapabilityIsReversibleAndNonDestructive", _test.TestSprintsDisabledCapabilityIsReversibleAndNonDestructive},

	{"TestResolveStartupEncryptionKey_InvalidNoUsersAllowed", _test.TestResolveStartupEncryptionKey_InvalidNoUsersAllowed},

	{"TestResolveStartupEncryptionKey_InvalidNormalUserAllowed", _test.TestResolveStartupEncryptionKey_InvalidNormalUserAllowed},

	{"TestResolveStartupEncryptionKey_InvalidWithTwoFactorEnabledFails", _test.TestResolveStartupEncryptionKey_InvalidWithTwoFactorEnabledFails},

	{"TestResolveStartupEncryptionKey_InvalidWithUserSecretFails", _test.TestResolveStartupEncryptionKey_InvalidWithUserSecretFails},

	{"TestResolveStartupEncryptionKey_InvalidWithEnrollmentSecretFails", _test.TestResolveStartupEncryptionKey_InvalidWithEnrollmentSecretFails},

	{"TestResolveStartupEncryptionKey_EmptyWithEncryptedStateFails", _test.TestResolveStartupEncryptionKey_EmptyWithEncryptedStateFails},

	{"TestResolveStartupEncryptionKey_ValidNoEncryptedStateReturned", _test.TestResolveStartupEncryptionKey_ValidNoEncryptedStateReturned},

	{"TestResolveStartupEncryptionKey_ValidWithEncryptedStateReturned", _test.TestResolveStartupEncryptionKey_ValidWithEncryptedStateReturned},

	{"TestResolveStartupEncryptionKey_EmptyWithCalendarCiphertextFails", _test.TestResolveStartupEncryptionKey_EmptyWithCalendarCiphertextFails},

	{"TestResolveStartupEncryptionKey_InvalidWithCalendarCiphertextFails", _test.TestResolveStartupEncryptionKey_InvalidWithCalendarCiphertextFails},

	{"TestResolveStartupEncryptionKey_EmptyNormalUserAllowed", _test.TestResolveStartupEncryptionKey_EmptyNormalUserAllowed},

	{"TestBurndown_TestingIsIncomplete", _test.TestBurndown_TestingIsIncomplete},

	{"TestMoveTodo_ToTesting", _test.TestMoveTodo_ToTesting},

	{"TestParseStatus_Testing", _test.TestParseStatus_Testing},

	{"TestGetBoard_IncludesTestingColumn", _test.TestGetBoard_IncludesTestingColumn},

	{"TestBurndown_TestingCompletedAfterDay", _test.TestBurndown_TestingCompletedAfterDay},

	{"TestStatus_OrderingIsUIOnly", _test.TestStatus_OrderingIsUIOnly},

	{"TestSystemRoles_RequireOwner", _test.TestSystemRoles_RequireOwner},

	{"TestSystemRoles_RequireAdmin", _test.TestSystemRoles_RequireAdmin},

	{"TestSystemRoles_ListUsers_RequiresAdmin", _test.TestSystemRoles_ListUsers_RequiresAdmin},

	{"TestSystemRoles_DeleteUser_OwnerOnly", _test.TestSystemRoles_DeleteUser_OwnerOnly},

	{"TestSystemRoles_DeleteUser_PreventsLastOwnerDeletion", _test.TestSystemRoles_DeleteUser_PreventsLastOwnerDeletion},

	{"TestSystemRoles_UpdateUserRole_OwnerOnly", _test.TestSystemRoles_UpdateUserRole_OwnerOnly},

	{"TestSystemRoles_UpdateUserRole_PreventsLastOwnerDemotion", _test.TestSystemRoles_UpdateUserRole_PreventsLastOwnerDemotion},

	{"TestSystemRoles_CannotDeleteSelf", _test.TestSystemRoles_CannotDeleteSelf},

	{"TestSystemRoles_Invariant_AlwaysAtLeastOneOwner", _test.TestSystemRoles_Invariant_AlwaysAtLeastOneOwner},

	{"TestTagMutationStoreColorClearContracts", _test.TestTagMutationStoreColorClearContracts},

	{"TestTagMutationStoreDurableIDCompatibilityAndAuthority", _test.TestTagMutationStoreDurableIDCompatibilityAndAuthority},

	{"TestTagMutationStoreTemporaryAndExpiryContracts", _test.TestTagMutationStoreTemporaryAndExpiryContracts},

	{"TestTagMutationStoreDeleteAffectedProjectsAndAtomicity", _test.TestTagMutationStoreDeleteAffectedProjectsAndAtomicity},

	{"TestAnonymousBoard_CreateTodoWithTags", _test.TestAnonymousBoard_CreateTodoWithTags},

	{"TestAnonymousBoard_UpdateTodoTags", _test.TestAnonymousBoard_UpdateTodoTags},

	{"TestAnonymousBoard_TagIsolation", _test.TestAnonymousBoard_TagIsolation},

	{"TestAnonymousBoard_TagColors", _test.TestAnonymousBoard_TagColors},

	{"TestUpdateTagColor_RejectsInvalidColor", _test.TestUpdateTagColor_RejectsInvalidColor},

	{"TestAnonymousBoard_UpdateUserOwnedTagColorFails", _test.TestAnonymousBoard_UpdateUserOwnedTagColorFails},

	{"TestCreatorOwnedTempBoard_AnonymousUpdatesUserOwnedTagDisplayColor", _test.TestCreatorOwnedTempBoard_AnonymousUpdatesUserOwnedTagDisplayColor},

	{"TestAnonymousBoard_TagDeletion", _test.TestAnonymousBoard_TagDeletion},

	{"TestDurableBoard_TagsRequireAuth", _test.TestDurableBoard_TagsRequireAuth},

	{"TestAuthenticatedUser_ViewsAnonymousBoard", _test.TestAuthenticatedUser_ViewsAnonymousBoard},

	{"TestTagColorResolution", _test.TestTagColorResolution},

	{"TestDurableBoard_UserOwnedTagsUnchanged", _test.TestDurableBoard_UserOwnedTagsUnchanged},

	{"TestAnonymousBoard_DefaultTagsAutoPopulated", _test.TestAnonymousBoard_DefaultTagsAutoPopulated},

	{"TestAuthenticatedProject_NoDefaultTags", _test.TestAuthenticatedProject_NoDefaultTags},

	{"TestDeleteTagForDurableProjectByID_RejectsCrossProjectPersonal", _test.TestDeleteTagForDurableProjectByID_RejectsCrossProjectPersonal},

	{"TestDeleteTagForDurableProjectByID_RejectsForeignBoardScoped", _test.TestDeleteTagForDurableProjectByID_RejectsForeignBoardScoped},

	{"TestDeleteTagForDurableProjectByID_RejectsNonMember", _test.TestDeleteTagForDurableProjectByID_RejectsNonMember},

	{"TestDeleteTagForDurableProjectByID_ViewerCannotDeleteBoardScoped", _test.TestDeleteTagForDurableProjectByID_ViewerCannotDeleteBoardScoped},

	{"TestDeleteTagForDurableProjectByID_MaintainerDeletesBoardScoped", _test.TestDeleteTagForDurableProjectByID_MaintainerDeletesBoardScoped},

	{"TestDeleteTagForDurableProjectByID_CannotDeleteOthersPersonal", _test.TestDeleteTagForDurableProjectByID_CannotDeleteOthersPersonal},

	{"TestDeleteTagForDurableProjectByID_OwnCrossProjectPersonalReturnsAllAffected", _test.TestDeleteTagForDurableProjectByID_OwnCrossProjectPersonalReturnsAllAffected},

	{"TestDeleteMyTagByID_ReturnsAllAffectedProjects", _test.TestDeleteMyTagByID_ReturnsAllAffectedProjects},

	{"TestDeleteMyTagByID_RejectsNonOwner", _test.TestDeleteMyTagByID_RejectsNonOwner},

	{"TestUpdateMyTagColor_OwnerOnly", _test.TestUpdateMyTagColor_OwnerOnly},

	{"TestProjectLabels_TwoUsersBugCollapseToOneEntry", _test.TestProjectLabels_TwoUsersBugCollapseToOneEntry},

	{"TestProjectLabels_LegacyConflictingViewerColorsResolveDeterministically", _test.TestProjectLabels_LegacyConflictingViewerColorsResolveDeterministically},

	{"TestProjectLabels_ViewerColorSurvivesBackingRowRotation", _test.TestProjectLabels_ViewerColorSurvivesBackingRowRotation},

	{"TestProjectLabels_ViewerColorIgnoresUnrelatedProjectRows", _test.TestProjectLabels_ViewerColorIgnoresUnrelatedProjectRows},

	{"TestProjectLabels_HistoricalPersonalColorDoesNotOverridePureBoardGroup", _test.TestProjectLabels_HistoricalPersonalColorDoesNotOverridePureBoardGroup},

	{"TestProjectLabels_NonOwnerCanSetColorByNameWithoutAffectingOthers", _test.TestProjectLabels_NonOwnerCanSetColorByNameWithoutAffectingOthers},

	{"TestProjectLabels_DeleteScopeByViewer", _test.TestProjectLabels_DeleteScopeByViewer},

	{"TestProjectLabels_DeleteMineIsCrossProject", _test.TestProjectLabels_DeleteMineIsCrossProject},

	{"TestProjectLabels_DeleteMineLeavesGroupWhenAnotherMemberUsesName", _test.TestProjectLabels_DeleteMineLeavesGroupWhenAnotherMemberUsesName},

	{"TestProjectLabels_BoardScopedAndMixedGroups", _test.TestProjectLabels_BoardScopedAndMixedGroups},

	{"TestProjectLabels_CrossOwnerCanonicalEquivalence", _test.TestProjectLabels_CrossOwnerCanonicalEquivalence},

	{"TestProjectLabels_TemporaryBoardKeepsRowLevelProjection", _test.TestProjectLabels_TemporaryBoardKeepsRowLevelProjection},

	{"TestProjectLabels_NameWritesRequireMembership", _test.TestProjectLabels_NameWritesRequireMembership},

	{"TestProjectLabels_ReadInclusionUnchanged", _test.TestProjectLabels_ReadInclusionUnchanged},

	{"TestProjectLabels_CanonicalFilterMatchesGroupedCount", _test.TestProjectLabels_CanonicalFilterMatchesGroupedCount},

	{"TestProjectLabels_TemporaryBoardFilterStaysRowLevel", _test.TestProjectLabels_TemporaryBoardFilterStaysRowLevel},

	{"TestProjectLabels_UncanonicalizableRowStaysAddressable", _test.TestProjectLabels_UncanonicalizableRowStaysAddressable},

	{"TestUserOwnedTags_CreationRequiresUserAccess", _test.TestUserOwnedTags_CreationRequiresUserAccess},

	{"TestUserOwnedTags_NamesNormalizedToLowercase", _test.TestUserOwnedTags_NamesNormalizedToLowercase},

	{"TestUserOwnedTags_UniqueConstraintPreventsDuplicates", _test.TestUserOwnedTags_UniqueConstraintPreventsDuplicates},

	{"TestUserOwnedTags_CanAttachToMultipleProjects", _test.TestUserOwnedTags_CanAttachToMultipleProjects},

	{"TestUserOwnedTags_BoardShowsAllTags", _test.TestUserOwnedTags_BoardShowsAllTags},

	{"TestUserOwnedTags_AutocompleteShowsUserTagsOnly", _test.TestUserOwnedTags_AutocompleteShowsUserTagsOnly},

	{"TestUserOwnedTags_ColorPerViewer", _test.TestUserOwnedTags_ColorPerViewer},

	{"TestUserOwnedTags_DeleteRequiresZeroReferences", _test.TestUserOwnedTags_DeleteRequiresZeroReferences},

	{"TestUserOwnedTags_OwnershipPermanent", _test.TestUserOwnedTags_OwnershipPermanent},

	{"TestUserOwnedTags_UsersCanOnlyAttachOwnTags", _test.TestUserOwnedTags_UsersCanOnlyAttachOwnTags},

	{"TestUserOwnedTags_FilteringMatchesByNameAcrossOwners", _test.TestUserOwnedTags_FilteringMatchesByNameAcrossOwners},

	{"TestUserOwnedTags_ProjectTagsIsProjectWide", _test.TestUserOwnedTags_ProjectTagsIsProjectWide},

	{"TestUserOwnedTags_CannotDeleteOtherUsersTags", _test.TestUserOwnedTags_CannotDeleteOtherUsersTags},

	{"TestUserOwnedTags_MaintainerOverrideRequiresAll", _test.TestUserOwnedTags_MaintainerOverrideRequiresAll},

	{"TestUserOwnedTags_ListUserTags", _test.TestUserOwnedTags_ListUserTags},

	{"TestTodoCreatorAttributionCreationSemantics", _test.TestTodoCreatorAttributionCreationSemantics},

	{"TestTodoCreatorAttributionIsHistoricalNotMembership", _test.TestTodoCreatorAttributionIsHistoricalNotMembership},

	{"TestTodoCreatorAttributionNullsWhenUserIsDeleted", _test.TestTodoCreatorAttributionNullsWhenUserIsDeleted},

	{"TestTodoCreatorAttributionAllowsHistoricalNull", _test.TestTodoCreatorAttributionAllowsHistoricalNull},

	{"TestDeleteTodoByLocalID_PersistenceContract", _test.TestDeleteTodoByLocalID_PersistenceContract},

	{"TestDeleteTodoByLocalID_RollsBackOnDeleteFailure", _test.TestDeleteTodoByLocalID_RollsBackOnDeleteFailure},

	{"TestDeleteTodo_ActivityFailureDoesNotReverseCommittedDelete", _test.TestDeleteTodo_ActivityFailureDoesNotReverseCommittedDelete},

	{"TestCreateTodo_AnonymousTempBoard_WithAuthEnabled_AllowsCreateWithoutUser", _test.TestCreateTodo_AnonymousTempBoard_WithAuthEnabled_AllowsCreateWithoutUser},

	{"TestCreateTodo_CreatorOwnedTempBoard_WithAuthEnabled_AllowsCreateWithoutUser", _test.TestCreateTodo_CreatorOwnedTempBoard_WithAuthEnabled_AllowsCreateWithoutUser},

	{"TestCreateTodo_DurableProject_WithAuthEnabled_DeniesCreateWithoutUser", _test.TestCreateTodo_DurableProject_WithAuthEnabled_DeniesCreateWithoutUser},

	{"TestMoveTodo_CreatorOwnedTempBoard_WithAuthEnabled_AllowsAnonymous", _test.TestMoveTodo_CreatorOwnedTempBoard_WithAuthEnabled_AllowsAnonymous},

	{"TestDeleteTodo_CreatorOwnedTempBoard_WithAuthEnabled_AllowsAnonymous", _test.TestDeleteTodo_CreatorOwnedTempBoard_WithAuthEnabled_AllowsAnonymous},

	{"TestMoveTodo_DurableProject_WithAuthEnabled_DeniesAnonymous", _test.TestMoveTodo_DurableProject_WithAuthEnabled_DeniesAnonymous},

	{"TestTodoAssignee_ContributorCanEditBodyWhenAssigned", _test.TestTodoAssignee_ContributorCanEditBodyWhenAssigned},

	{"TestTodoAssignee_ContributorCannotAssignOthers", _test.TestTodoAssignee_ContributorCannotAssignOthers},

	{"TestTodoAssignee_ContributorCannotSelfAssign", _test.TestTodoAssignee_ContributorCannotSelfAssign},

	{"TestTodoAssignee_MaintainerCanAssignOthersAndViewerAssignable", _test.TestTodoAssignee_MaintainerCanAssignOthersAndViewerAssignable},

	{"TestTodoAssignee_AnonymousModeRejectsAssignment", _test.TestTodoAssignee_AnonymousModeRejectsAssignment},

	{"TestTodoAssignee_AuditAndMemberRemovalUnassign", _test.TestTodoAssignee_AuditAndMemberRemovalUnassign},

	{"TestTodoAssignee_AssignNonMemberRejected", _test.TestTodoAssignee_AssignNonMemberRejected},

	{"TestTodoAssignee_AssignNonexistentUserRejected", _test.TestTodoAssignee_AssignNonexistentUserRejected},

	{"TestTodoAssignee_ContributorCannotUnassign", _test.TestTodoAssignee_ContributorCannotUnassign},

	{"TestTodoAssignee_ViewerCannotAssignSelf", _test.TestTodoAssignee_ViewerCannotAssignSelf},

	{"TestTodoAssignee_UnauthenticatedAssignmentChangeRejected", _test.TestTodoAssignee_UnauthenticatedAssignmentChangeRejected},

	{"TestTodoAssignee_ContributorCannotCreate", _test.TestTodoAssignee_ContributorCannotCreate},

	{"TestTodoAssignee_ContributorCannotDelete", _test.TestTodoAssignee_ContributorCannotDelete},

	{"TestTodoAssignee_ContributorCannotMove", _test.TestTodoAssignee_ContributorCannotMove},

	{"TestTodoAssignee_ContributorCannotEditUnassignedTodo", _test.TestTodoAssignee_ContributorCannotEditUnassignedTodo},

	{"TestTodoAssignee_ContributorCannotModifyTitle", _test.TestTodoAssignee_ContributorCannotModifyTitle},

	{"TestTodoAssignee_MaintainerFullAccess", _test.TestTodoAssignee_MaintainerFullAccess},

	{"TestTodoLocalID_ConcurrentCreatesAreUniqueAndContiguous", _test.TestTodoLocalID_ConcurrentCreatesAreUniqueAndContiguous},

	{"TestUserAdministrationStoreAuthorizationValidationAndTargetPrecedence", _test.TestUserAdministrationStoreAuthorizationValidationAndTargetPrecedence},

	{"TestUserAdministrationStoreOwnerInvariantMatrix", _test.TestUserAdministrationStoreOwnerInvariantMatrix},

	{"TestUserAdministrationStoreDeleteCascadesAndPreservesTodoHistory", _test.TestUserAdministrationStoreDeleteCascadesAndPreservesTodoHistory},

	{"TestUserAdministrationStoreDeleteOwnedProjectFailureIsAtomic", _test.TestUserAdministrationStoreDeleteOwnedProjectFailureIsAtomic},

	{"TestUserAdministrationStoreCreateUserSeedFailureRollsBackUser", _test.TestUserAdministrationStoreCreateUserSeedFailureRollsBackUser},

	{"TestWallMutationStoreCharacterizationReplaceRegeneratesNotesAndPreservesDanglingEdges", _test.TestWallMutationStoreCharacterizationReplaceRegeneratesNotesAndPreservesDanglingEdges},

	{"TestWallMutationStoreCharacterizationEmptyPatchIsVersionedWrite", _test.TestWallMutationStoreCharacterizationEmptyPatchIsVersionedWrite},

	{"TestWallMutationStoreCharacterizationValidationPrecedesTargetLookup", _test.TestWallMutationStoreCharacterizationValidationPrecedesTargetLookup},

	{"TestWallMutationStoreCharacterizationReplacementLimitPrecedesNoteValidationAndWrite", _test.TestWallMutationStoreCharacterizationReplacementLimitPrecedesNoteValidationAndWrite},

	{"TestWallMutationStoreCharacterizationSQLWriteFailureLeavesPersistedWallUnchanged", _test.TestWallMutationStoreCharacterizationSQLWriteFailureLeavesPersistedWallUnchanged},

	{"TestWallMutationStoreCharacterizationDuplicateEdgePerformsNoWrite", _test.TestWallMutationStoreCharacterizationDuplicateEdgePerformsNoWrite},

	{"TestWallMutationStoreCharacterizationConcurrentDifferentNotePatchesSerializeWithoutConflict", _test.TestWallMutationStoreCharacterizationConcurrentDifferentNotePatchesSerializeWithoutConflict},

	{"TestWallMutationStoreCharacterizationConcurrentSameNoteAllowsOneWinner", _test.TestWallMutationStoreCharacterizationConcurrentSameNoteAllowsOneWinner},

	{"TestWallGetIsSideEffectFree", _test.TestWallGetIsSideEffectFree},

	{"TestWallCreateMaterializesRow", _test.TestWallCreateMaterializesRow},

	{"TestWallPatchConflictsOnVersionMismatch", _test.TestWallPatchConflictsOnVersionMismatch},

	{"TestWallPatchOnDifferentNotesDoesNotConflict", _test.TestWallPatchOnDifferentNotesDoesNotConflict},

	{"TestWallDeleteNote", _test.TestWallDeleteNote},

	{"TestWallEdgeCreateRejectsSelfLoopAndUnknownNote", _test.TestWallEdgeCreateRejectsSelfLoopAndUnknownNote},

	{"TestWallEdgeCreateIsIdempotent", _test.TestWallEdgeCreateIsIdempotent},

	{"TestWallDeleteEdgeAndCascadeOnNoteDelete", _test.TestWallDeleteEdgeAndCascadeOnNoteDelete},

	{"TestWallRejectsInvalidColor", _test.TestWallRejectsInvalidColor},

	{"TestParseWallpaperPref", _test.TestParseWallpaperPref},

	{"TestAddLane_InsertsBeforeDone", _test.TestAddLane_InsertsBeforeDone},

	{"TestAddLane_StoredNameIsTrimmed", _test.TestAddLane_StoredNameIsTrimmed},

	{"TestAddLane_ServerGeneratedKeyUniqueWhenNamesCollide", _test.TestAddLane_ServerGeneratedKeyUniqueWhenNamesCollide},

	{"TestAddLane_InvalidNameRejected", _test.TestAddLane_InvalidNameRejected},

	{"TestAddLane_MaxLanesEnforced", _test.TestAddLane_MaxLanesEnforced},

	{"TestAddLane_IsDoneFalseEnforced", _test.TestAddLane_IsDoneFalseEnforced},

	{"TestAddLane_PreservesSingleDoneLane", _test.TestAddLane_PreservesSingleDoneLane},

	{"TestDeleteLane_EmptyNonDoneLaneRemoved", _test.TestDeleteLane_EmptyNonDoneLaneRemoved},

	{"TestDeleteLane_NonEmptyLaneRejected", _test.TestDeleteLane_NonEmptyLaneRejected},

	{"TestDeleteLane_DoneLaneRejected", _test.TestDeleteLane_DoneLaneRejected},

	{"TestDeleteLane_MinLanesEnforced", _test.TestDeleteLane_MinLanesEnforced},

	{"TestDeleteLane_PositionsReindexed", _test.TestDeleteLane_PositionsReindexed},

	{"TestDeleteLane_PreservesSingleDoneLane", _test.TestDeleteLane_PreservesSingleDoneLane},

	{"TestRenameLane_UpdatesNamePreservesKey", _test.TestRenameLane_UpdatesNamePreservesKey},

	{"TestRenameLane_BurndownUnaffected", _test.TestRenameLane_BurndownUnaffected},

	{"TestUpdateWorkflowColumn_ValidNameAndColor", _test.TestUpdateWorkflowColumn_ValidNameAndColor},

	{"TestUpdateWorkflowColumn_InvalidColorRejected", _test.TestUpdateWorkflowColumn_InvalidColorRejected},

	{"TestUpdateWorkflowColumn_NonexistentKey", _test.TestUpdateWorkflowColumn_NonexistentKey},

	{"TestUpdateWorkflowColumn_OtherFieldsUnchanged", _test.TestUpdateWorkflowColumn_OtherFieldsUnchanged},

	{"TestImportTrelloProject_CreatesDistinctSlugOnDuplicateImport", _xtest.TestImportTrelloProject_CreatesDistinctSlugOnDuplicateImport},

	{"TestImportTrelloProject_PersistsImportMetadata", _xtest.TestImportTrelloProject_PersistsImportMetadata},

	{"TestImportTrelloProject_RollsBackOnMetadataMismatch", _xtest.TestImportTrelloProject_RollsBackOnMetadataMismatch},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/store"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

