
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/migrate"


)

var tests = []testing.InternalTest{

	{"TestApplyFreshDatabaseRecordsAllEmbeddedMigrations", _test.TestApplyFreshDatabaseRecordsAllEmbeddedMigrations},

	{"TestApplyIsIdempotent", _test.TestApplyIsIdempotent},

	{"TestApplyUpgradesCurrentMain061WithPriorityDefaults", _test.TestApplyUpgradesCurrentMain061WithPriorityDefaults},

	{"TestApplyCreatesCurrentSchemaLandmarks", _test.TestApplyCreatesCurrentSchemaLandmarks},

	{"TestChronologicalTodoIndexSupportsLaneOrder", _test.TestChronologicalTodoIndexSupportsLaneOrder},

	{"TestMigration057InvalidatesUnboundArtifactsAndPreservesClients", _test.TestMigration057InvalidatesUnboundArtifactsAndPreservesClients},

	{"TestApplyLeavesForeignKeysEnabled", _test.TestApplyLeavesForeignKeysEnabled},

	{"TestApplyWithCanceledContextReturnsError", _test.TestApplyWithCanceledContextReturnsError},

	{"TestMigration059ClassifiesExistingPreferencesAsLegacy", _test.TestMigration059ClassifiesExistingPreferencesAsLegacy},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/migrate"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

