
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/config"


)

var tests = []testing.InternalTest{

	{"TestMarkdownNotesEnabledFromEnv", _test.TestMarkdownNotesEnabledFromEnv},

	{"TestMermaidNotesEnabledFromEnv", _test.TestMermaidNotesEnabledFromEnv},

	{"TestNormalizeBaseURL", _test.TestNormalizeBaseURL},

	{"TestFromEnv_PublicBaseURL", _test.TestFromEnv_PublicBaseURL},

	{"TestNormalizeSMTPTLSMode", _test.TestNormalizeSMTPTLSMode},

	{"TestSMTPPortFromEnv", _test.TestSMTPPortFromEnv},

	{"TestFromEnv_SMTP", _test.TestFromEnv_SMTP},

	{"TestTrustProxyFromEnv", _test.TestTrustProxyFromEnv},

	{"TestWallEnabledFromEnv", _test.TestWallEnabledFromEnv},

	{"TestNormalizeVAPIDSubscriber", _test.TestNormalizeVAPIDSubscriber},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/config"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

