
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/tag"


)

var tests = []testing.InternalTest{

	{"TestMCPColorMineIDSequenceAndSyntheticResult", _test.TestMCPColorMineIDSequenceAndSyntheticResult},

	{"TestMCPColorMineIDFailures", _test.TestMCPColorMineIDFailures},

	{"TestMCPColorProjectNameSequenceAndProjection", _test.TestMCPColorProjectNameSequenceAndProjection},

	{"TestMCPColorProjectNameFailures", _test.TestMCPColorProjectNameFailures},

	{"TestMCPColorProjectIDDurableAndTemporarySequences", _test.TestMCPColorProjectIDDurableAndTemporarySequences},

	{"TestMCPColorPreparedProjectIDOwnsTemporaryClassification", _test.TestMCPColorPreparedProjectIDOwnsTemporaryClassification},

	{"TestMCPColorProjectIDPreparationOrdering", _test.TestMCPColorProjectIDPreparationOrdering},

	{"TestMCPColorProjectIDMutationAndPostReadFailures", _test.TestMCPColorProjectIDMutationAndPostReadFailures},

	{"TestMCPColorCancellationUsesExactBoundContext", _test.TestMCPColorCancellationUsesExactBoundContext},

	{"TestMCPDeletionMineIDSequenceAndErrors", _test.TestMCPDeletionMineIDSequenceAndErrors},

	{"TestMCPDeletionProjectIDSequenceAndClassification", _test.TestMCPDeletionProjectIDSequenceAndClassification},

	{"TestMCPDeletionProjectIDPreparationPrecedence", _test.TestMCPDeletionProjectIDPreparationPrecedence},

	{"TestMCPDeletionProjectIDDeleteErrorAndCancellation", _test.TestMCPDeletionProjectIDDeleteErrorAndCancellation},

	{"TestColorIntentPreservesPreparedValue", _test.TestColorIntentPreservesPreparedValue},

	{"TestColorIntentOwnsAndReturnsCopies", _test.TestColorIntentOwnsAndReturnsCopies},

	{"TestDeletionResultOwnsAffectedProjectIDs", _test.TestDeletionResultOwnsAffectedProjectIDs},

	{"TestProjectKindsAreDistinct", _test.TestProjectKindsAreDistinct},

	{"TestCommandsPreservePreparedIdentityValues", _test.TestCommandsPreservePreparedIdentityValues},

	{"TestRESTColorMineIDSequenceAndErrors", _test.TestRESTColorMineIDSequenceAndErrors},

	{"TestRESTColorProjectIDDispatchAndPublication", _test.TestRESTColorProjectIDDispatchAndPublication},

	{"TestRESTColorProjectNameDispatchAndPublication", _test.TestRESTColorProjectNameDispatchAndPublication},

	{"TestRESTColorProjectMutationFailuresNeverPublish", _test.TestRESTColorProjectMutationFailuresNeverPublish},

	{"TestRESTColorRejectsInvalidPreparedProjectCombinations", _test.TestRESTColorRejectsInvalidPreparedProjectCombinations},

	{"TestRESTColorPreparedProjectUsesCancelledBoundContext", _test.TestRESTColorPreparedProjectUsesCancelledBoundContext},

	{"TestRESTColorNilPublisherIsNoOp", _test.TestRESTColorNilPublisherIsNoOp},

	{"TestRESTDeletionMineIDFanout", _test.TestRESTDeletionMineIDFanout},

	{"TestRESTDeletionProjectIDDispatchAndPublication", _test.TestRESTDeletionProjectIDDispatchAndPublication},

	{"TestRESTDeletionProjectIDFailureSilence", _test.TestRESTDeletionProjectIDFailureSilence},

	{"TestRESTDeletionProjectNameDurableAndCreatorTemporary", _test.TestRESTDeletionProjectNameDurableAndCreatorTemporary},

	{"TestRESTDeletionAnonymousNameResolution", _test.TestRESTDeletionAnonymousNameResolution},

	{"TestRESTDeletionRejectsInvalidPreparedCombinations", _test.TestRESTDeletionRejectsInvalidPreparedCombinations},

	{"TestRESTDeletionUsesCancelledBoundContext", _test.TestRESTDeletionUsesCancelledBoundContext},

	{"TestRESTDeletionNilPublisherIsNoOp", _test.TestRESTDeletionNilPublisherIsNoOp},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/tag"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

