
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/auth/tokens"


)

var tests = []testing.InternalTest{

	{"TestGeneratePasswordResetToken_EmptySecret", _test.TestGeneratePasswordResetToken_EmptySecret},

	{"TestGeneratePasswordResetToken_ValidToken", _test.TestGeneratePasswordResetToken_ValidToken},

	{"TestParsePasswordResetToken_MalformedInputs", _test.TestParsePasswordResetToken_MalformedInputs},

	{"TestVerifyPasswordResetToken_ValidGeneratedToken", _test.TestVerifyPasswordResetToken_ValidGeneratedToken},

	{"TestVerifyPasswordResetToken_RejectsInvalidInputs", _test.TestVerifyPasswordResetToken_RejectsInvalidInputs},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/auth/tokens"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

