
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/todolink"


)

var tests = []testing.InternalTest{

	{"TestMCPMutationServiceConstructorIsInert", _test.TestMCPMutationServiceConstructorIsInert},

	{"TestMCPMutationPrepareBindsAccessAndSource", _test.TestMCPMutationPrepareBindsAccessAndSource},

	{"TestMCPMutationPrepareAccessFailureReturnsRawError", _test.TestMCPMutationPrepareAccessFailureReturnsRawError},

	{"TestMCPMutationPrepareClassifiesSourceFailureWithoutLeakingCause", _test.TestMCPMutationPrepareClassifiesSourceFailureWithoutLeakingCause},

	{"TestPreparedMCPMutationBindsTargetByValueAndKeepsResolvedIdentity", _test.TestPreparedMCPMutationBindsTargetByValueAndKeepsResolvedIdentity},

	{"TestPreparedMCPMutationAdd", _test.TestPreparedMCPMutationAdd},

	{"TestPreparedMCPMutationRemove", _test.TestPreparedMCPMutationRemove},

	{"TestPreparedMCPMutationPreservesNilAndEmptyLinkSlices", _test.TestPreparedMCPMutationPreservesNilAndEmptyLinkSlices},

	{"TestPreparedMCPMutationFailuresShortCircuitReads", _test.TestPreparedMCPMutationFailuresShortCircuitReads},

	{"TestPreparedMCPMutationClassifiesProjectionFailuresWithoutLeakingCause", _test.TestPreparedMCPMutationClassifiesProjectionFailuresWithoutLeakingCause},

	{"TestPreparedMCPMutationCancellationBoundaries", _test.TestPreparedMCPMutationCancellationBoundaries},

	{"TestRESTMutationPrepareBindsSourceGate", _test.TestRESTMutationPrepareBindsSourceGate},

	{"TestRESTMutationPrepareFailureCreatesNoCapability", _test.TestRESTMutationPrepareFailureCreatesNoCapability},

	{"TestPreparedRESTMutationBindsTargetByValueAndDiscardsSourceResult", _test.TestPreparedRESTMutationBindsTargetByValueAndDiscardsSourceResult},

	{"TestPreparedRESTMutationAdd", _test.TestPreparedRESTMutationAdd},

	{"TestPreparedRESTMutationRemove", _test.TestPreparedRESTMutationRemove},

	{"TestPreparedRESTMutationFailureSuppressesPublication", _test.TestPreparedRESTMutationFailureSuppressesPublication},

	{"TestPreparedRESTMutationUsesCancelledBoundContext", _test.TestPreparedRESTMutationUsesCancelledBoundContext},

	{"TestRESTMutationServiceNilPublisher", _test.TestRESTMutationServiceNilPublisher},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/todolink"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

