package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

// nowUnixMs returns Unix milliseconds (UTC) for audit timestamps.
// Use this instead of SQLite strftime() to match existing conventions (SSE, todo_assignee_events).
func nowUnixMs() int64 {
	return time.Now().UTC().UnixMilli()
}

// insertAuditEventTx inserts an audit event within the given transaction.
// actorUserID: nil for anonymous/unauthenticated actions.
// targetID: nil when target_type is "todo_link" (no stable row ID).
// metadata: nil stores NULL; otherwise json.Marshal(metadata).
// created_at: generated by nowUnixMs() in Go.
func insertAuditEventTx(ctx context.Context, tx *sql.Tx, projectID int64, actorUserID *int64, action, targetType string, targetID *int64, metadata any) error {
	var metadataJSON any
	if metadata != nil {
		b, err := json.Marshal(metadata)
		if err != nil {
			return err
		}
		metadataJSON = string(b)
	}
	var actorArg any
	if actorUserID != nil {
		actorArg = *actorUserID
	}
	var targetArg any
	if targetID != nil {
		targetArg = *targetID
	}
	createdAt := nowUnixMs()
	_, err := tx.ExecContext(ctx, `
		INSERT INTO audit_events(project_id, actor_user_id, action, target_type, target_id, metadata, created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?)`,
		projectID, actorArg, action, targetType, targetArg, metadataJSON, createdAt,
	)
	return err
}
