
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/membership"


)

var tests = []testing.InternalTest{

	{"TestMCPMutationPrepareOrderingAndBinding", _test.TestMCPMutationPrepareOrderingAndBinding},

	{"TestPreparedMCPMutationSuccessfulSequences", _test.TestPreparedMCPMutationSuccessfulSequences},

	{"TestPreparedMCPMutationFailuresPreserveOrderAndIdentity", _test.TestPreparedMCPMutationFailuresPreserveOrderAndIdentity},

	{"TestPreparedMCPMutationMissingTargetSentinelsAreDistinct", _test.TestPreparedMCPMutationMissingTargetSentinelsAreDistinct},

	{"TestPreparedMCPMutationUsesCancelledBoundContext", _test.TestPreparedMCPMutationUsesCancelledBoundContext},

	{"TestPreparedMCPMutationCancellationAfterMutationReachesList", _test.TestPreparedMCPMutationCancellationAfterMutationReachesList},

	{"TestRESTMutationPrepareBindsActorContextAndProject", _test.TestRESTMutationPrepareBindsActorContextAndProject},

	{"TestPreparedRESTMutationSuccessfulSequences", _test.TestPreparedRESTMutationSuccessfulSequences},

	{"TestPreparedRESTMutationFailuresShortCircuit", _test.TestPreparedRESTMutationFailuresShortCircuit},

	{"TestPreparedRESTMutationUsesCancelledBoundContext", _test.TestPreparedRESTMutationUsesCancelledBoundContext},

	{"TestRESTMutationServiceNilPublisherIsNoop", _test.TestRESTMutationServiceNilPublisherIsNoop},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/membership"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

