
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/agora"


	_xtest "scrumboy/internal/agora_test"

)

var tests = []testing.InternalTest{

	{"TestInvokeSuccessNormalized_invalidStructuredContent_fallsBackToTextJSON", _test.TestInvokeSuccessNormalized_invalidStructuredContent_fallsBackToTextJSON},

	{"TestInvokeSuccessNormalized_invalidStructuredContent_fallsBackToRawText", _test.TestInvokeSuccessNormalized_invalidStructuredContent_fallsBackToRawText},

	{"TestAgora_MCPJSONRPCUnchangedWithAgoraWired", _xtest.TestAgora_MCPJSONRPCUnchangedWithAgoraWired},

	{"TestAgora_DiscoverSuccess", _xtest.TestAgora_DiscoverSuccess},

	{"TestAgora_InvokeSuccessStructured", _xtest.TestAgora_InvokeSuccessStructured},

	{"TestAgora_BearerPassthroughInvoke", _xtest.TestAgora_BearerPassthroughInvoke},

	{"TestAgora_DoesNotAcceptMCPResourceOAuthToken", _xtest.TestAgora_DoesNotAcceptMCPResourceOAuthToken},

	{"TestAgora_InvokeArgumentsNonObjectRejected", _xtest.TestAgora_InvokeArgumentsNonObjectRejected},

	{"TestAgora_UnknownAgoraPathJSON404", _xtest.TestAgora_UnknownAgoraPathJSON404},

	{"TestAgora_InvokeTopLevelUnknownRejected", _xtest.TestAgora_InvokeTopLevelUnknownRejected},

	{"TestAgora_InvokeArgumentsPassThrough", _xtest.TestAgora_InvokeArgumentsPassThrough},

	{"TestAgora_InvokeToolError", _xtest.TestAgora_InvokeToolError},

	{"TestAgora_ProtocolErrorFromMCP", _xtest.TestAgora_ProtocolErrorFromMCP},

	{"TestAgora_JSONRPCErrorDataPassthrough", _xtest.TestAgora_JSONRPCErrorDataPassthrough},

	{"TestAgora_InvokeMissingArgumentsKey", _xtest.TestAgora_InvokeMissingArgumentsKey},

	{"TestAgora_InvokeArgumentsJSONNullNormalizes", _xtest.TestAgora_InvokeArgumentsJSONNullNormalizes},

	{"TestAgora_InvokeResultAllowsArrayFromStructuredContent", _xtest.TestAgora_InvokeResultAllowsArrayFromStructuredContent},

	{"TestAgora_DiscoverEnvelopeHasRequiredTopLevelKeys", _xtest.TestAgora_DiscoverEnvelopeHasRequiredTopLevelKeys},

	{"TestAgora_AgoraRouteNotUnderMCP", _xtest.TestAgora_AgoraRouteNotUnderMCP},

	{"TestAgora_AgoraV1RootJSON404", _xtest.TestAgora_AgoraV1RootJSON404},

	{"TestAgora_DiscoverWhitespaceBodyOK", _xtest.TestAgora_DiscoverWhitespaceBodyOK},

	{"TestAgora_CookiePassthroughParity", _xtest.TestAgora_CookiePassthroughParity},

	{"TestAgora_DiscoverToolsPayloadMatchesMCPToolsList", _xtest.TestAgora_DiscoverToolsPayloadMatchesMCPToolsList},

	{"TestAgora_InvokeEmptyOrWhitespaceBodyMissingTool", _xtest.TestAgora_InvokeEmptyOrWhitespaceBodyMissingTool},

	{"TestAgora_StandaloneHandlerNonAgoraPathJSON404", _xtest.TestAgora_StandaloneHandlerNonAgoraPathJSON404},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/agora"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

