
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/cmd/dbquery"


)

var tests = []testing.InternalTest{

	{"TestRunPrintsHeadersAndRows", _test.TestRunPrintsHeadersAndRows},

	{"TestRunPrintsNULLValues", _test.TestRunPrintsNULLValues},

	{"TestRunSupportsExpressionQueries", _test.TestRunSupportsExpressionQueries},

	{"TestRunReturnsQueryError", _test.TestRunReturnsQueryError},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/cmd/dbquery"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

