
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/projectcolor"


)

var tests = []testing.InternalTest{

	{"TestExtractFromDataURL_InvalidInputsReturnFallback", _test.TestExtractFromDataURL_InvalidInputsReturnFallback},

	{"TestExtractFromDataURL_SolidPNGPreservesDominantChannel", _test.TestExtractFromDataURL_SolidPNGPreservesDominantChannel},

	{"TestExtractFromDataURL_ClampsBlackAndWhite", _test.TestExtractFromDataURL_ClampsBlackAndWhite},

	{"TestExtractFromDataURL_TransparentPNGReturnsValidColor", _test.TestExtractFromDataURL_TransparentPNGReturnsValidColor},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/projectcolor"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

