
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/sprint"


)

var tests = []testing.InternalTest{

	{"TestUpdateCommandHasFieldsPreservesSyntacticPresence", _test.TestUpdateCommandHasFieldsPreservesSyntacticPresence},

	{"TestMaterializeUpdateInputPreservesPresenceAndValues", _test.TestMaterializeUpdateInputPreservesPresenceAndValues},

	{"TestMaterializeUpdateInputIsolatesPointers", _test.TestMaterializeUpdateInputIsolatesPointers},

	{"TestMCPDefinitionServiceConstructionIsInertAndPublicationFree", _test.TestMCPDefinitionServiceConstructionIsInertAndPublicationFree},

	{"TestMCPDefinitionPreparationAuthorization", _test.TestMCPDefinitionPreparationAuthorization},

	{"TestMCPDefinitionPreparationUsesFreshRole", _test.TestMCPDefinitionPreparationUsesFreshRole},

	{"TestMCPDefinitionPrepareUpdateTargetGate", _test.TestMCPDefinitionPrepareUpdateTargetGate},

	{"TestMCPDefinitionDisabledCapabilityFollowsAuthorizationAndTargetChecks", _test.TestMCPDefinitionDisabledCapabilityFollowsAuthorizationAndTargetChecks},

	{"TestPreparedMCPDefinitionBindsTargetsByValue", _test.TestPreparedMCPDefinitionBindsTargetsByValue},

	{"TestPreparedMCPCreateDelegatesAndReturnsExactResult", _test.TestPreparedMCPCreateDelegatesAndReturnsExactResult},

	{"TestPreparedMCPCreateFailureReturnsNoPartialResult", _test.TestPreparedMCPCreateFailureReturnsNoPartialResult},

	{"TestPreparedMCPUpdateEmptyReturnsRetainedSprint", _test.TestPreparedMCPUpdateEmptyReturnsRetainedSprint},

	{"TestPreparedMCPUpdateDelegatesThenReadsExactResult", _test.TestPreparedMCPUpdateDelegatesThenReadsExactResult},

	{"TestPreparedMCPUpdatePreservesExplicitEmptyAndZero", _test.TestPreparedMCPUpdatePreservesExplicitEmptyAndZero},

	{"TestPreparedMCPUpdateFailuresReturnNoPartialResult", _test.TestPreparedMCPUpdateFailuresReturnNoPartialResult},

	{"TestPreparedMCPDefinitionUsesCancelledBoundContext", _test.TestPreparedMCPDefinitionUsesCancelledBoundContext},

	{"TestMCPDeletionServiceConstructionIsInertAndPublicationFree", _test.TestMCPDeletionServiceConstructionIsInertAndPublicationFree},

	{"TestMCPDeletionPreparationAcceptsEveryLifecycleState", _test.TestMCPDeletionPreparationAcceptsEveryLifecycleState},

	{"TestMCPDeletionSuccessBindsIdentityAndHasNoPostRead", _test.TestMCPDeletionSuccessBindsIdentityAndHasNoPostRead},

	{"TestMCPDeletionMutationFailurePassesThroughWithoutRetry", _test.TestMCPDeletionMutationFailurePassesThroughWithoutRetry},

	{"TestMCPDeletionCancellationAfterPreparationUsesBoundContext", _test.TestMCPDeletionCancellationAfterPreparationUsesBoundContext},

	{"TestMCPLifecycleServiceConstructionIsInertAndPublicationFree", _test.TestMCPLifecycleServiceConstructionIsInertAndPublicationFree},

	{"TestMCPLifecyclePreparationAuthorization", _test.TestMCPLifecyclePreparationAuthorization},

	{"TestMCPLifecyclePreparationUsesFreshRole", _test.TestMCPLifecyclePreparationUsesFreshRole},

	{"TestMCPLifecyclePreparationTargetFailures", _test.TestMCPLifecyclePreparationTargetFailures},

	{"TestMCPLifecycleDisabledCapabilityFollowsTargetCheckAndPrecedesStatePolicy", _test.TestMCPLifecycleDisabledCapabilityFollowsTargetCheckAndPrecedesStatePolicy},

	{"TestMCPLifecyclePrepareActivatePolicyAndClock", _test.TestMCPLifecyclePrepareActivatePolicyAndClock},

	{"TestMCPLifecyclePrepareClosePolicy", _test.TestMCPLifecyclePrepareClosePolicy},

	{"TestMCPLifecycleSuccessfulTransitionsBindIdentityAndReturnProjection", _test.TestMCPLifecycleSuccessfulTransitionsBindIdentityAndReturnProjection},

	{"TestMCPLifecycleMutationFailuresPassThroughWithoutProjection", _test.TestMCPLifecycleMutationFailuresPassThroughWithoutProjection},

	{"TestMCPLifecycleActivateStoreTimeFailureRemainsRaw", _test.TestMCPLifecycleActivateStoreTimeFailureRemainsRaw},

	{"TestMCPLifecycleProjectionFailuresOccurAfterCommittedMutation", _test.TestMCPLifecycleProjectionFailuresOccurAfterCommittedMutation},

	{"TestMCPLifecycleCancellationAfterPreparation", _test.TestMCPLifecycleCancellationAfterPreparation},

	{"TestMCPLifecycleProjectionCancellationOccursAfterCommittedMutation", _test.TestMCPLifecycleProjectionCancellationOccursAfterCommittedMutation},

	{"TestRESTDefinitionPrepareAuthorization", _test.TestRESTDefinitionPrepareAuthorization},

	{"TestRESTDefinitionPrepareBindsDistinctTargetsByValue", _test.TestRESTDefinitionPrepareBindsDistinctTargetsByValue},

	{"TestPreparedRESTCreateDelegatesAndPublishes", _test.TestPreparedRESTCreateDelegatesAndPublishes},

	{"TestPreparedRESTUpdateDelegatesAndPublishes", _test.TestPreparedRESTUpdateDelegatesAndPublishes},

	{"TestPreparedRESTDefinitionFailuresSuppressPublication", _test.TestPreparedRESTDefinitionFailuresSuppressPublication},

	{"TestPreparedRESTDefinitionUsesCancelledBoundContext", _test.TestPreparedRESTDefinitionUsesCancelledBoundContext},

	{"TestRESTDefinitionServiceNilPublisher", _test.TestRESTDefinitionServiceNilPublisher},

	{"TestPreparedRESTUpdatePublishesRenameCorrectName", _test.TestPreparedRESTUpdatePublishesRenameCorrectName},

	{"TestRESTDeletionPrepareAuthorization", _test.TestRESTDeletionPrepareAuthorization},

	{"TestRESTDeletionBindsTargetAndPublishesAfterPersistence", _test.TestRESTDeletionBindsTargetAndPublishesAfterPersistence},

	{"TestRESTDeletionFailurePassesThroughWithoutPublication", _test.TestRESTDeletionFailurePassesThroughWithoutPublication},

	{"TestRESTDeletionCancellationAfterPreparationUsesBoundContext", _test.TestRESTDeletionCancellationAfterPreparationUsesBoundContext},

	{"TestRESTDeletionNilPublisherIsNoop", _test.TestRESTDeletionNilPublisherIsNoop},

	{"TestRESTLifecyclePrepareActivateAuthorization", _test.TestRESTLifecyclePrepareActivateAuthorization},

	{"TestRESTLifecyclePrepareCloseTargetGateAndBinding", _test.TestRESTLifecyclePrepareCloseTargetGateAndBinding},

	{"TestRESTLifecyclePrepareCloseFailures", _test.TestRESTLifecyclePrepareCloseFailures},

	{"TestRESTLifecyclePrepareActivateBindsTargetAndPublishesAfterPersistence", _test.TestRESTLifecyclePrepareActivateBindsTargetAndPublishesAfterPersistence},

	{"TestRESTLifecycleRepeatedActivationSuccessStillPublishes", _test.TestRESTLifecycleRepeatedActivationSuccessStillPublishes},

	{"TestRESTLifecycleMutationFailuresPassThroughWithoutPublication", _test.TestRESTLifecycleMutationFailuresPassThroughWithoutPublication},

	{"TestRESTLifecycleCancellationAfterPreparationUsesBoundContext", _test.TestRESTLifecycleCancellationAfterPreparationUsesBoundContext},

	{"TestRESTLifecycleNilPublisherIsNoop", _test.TestRESTLifecycleNilPublisherIsNoop},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/sprint"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

