
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/cmd/scrumboy"


)

var tests = []testing.InternalTest{

	{"TestLogWebPushConfiguration", _test.TestLogWebPushConfiguration},

	{"TestLogSMTPConfiguration", _test.TestLogSMTPConfiguration},

	{"TestRecoverOwnerCommandWithoutMigration056", _test.TestRecoverOwnerCommandWithoutMigration056},

	{"TestRecoverOwnerCommandEstablishesPasswordForOIDCOnlyOwner", _test.TestRecoverOwnerCommandEstablishesPasswordForOIDCOnlyOwner},

	{"TestRecoverOwnerCommandRejectsUnsafeTargetsAndArgvPassword", _test.TestRecoverOwnerCommandRejectsUnsafeTargetsAndArgvPassword},

	{"TestRecoverOwnerCommandRejectsIncompatibleSchema", _test.TestRecoverOwnerCommandRejectsIncompatibleSchema},

	{"TestRecoverOwnerCommandRejectsTooOldAndMissingAuthSchema", _test.TestRecoverOwnerCommandRejectsTooOldAndMissingAuthSchema},

	{"TestRecoverOwnerCommandRejectsWeakPasswordAndImplicitPipe", _test.TestRecoverOwnerCommandRejectsWeakPasswordAndImplicitPipe},

	{"TestRecoverOwnerCommandFailsClearlyWhenDatabaseIsLocked", _test.TestRecoverOwnerCommandFailsClearlyWhenDatabaseIsLocked},

	{"TestNamedZonesAvailableWithoutSystemTZData", _test.TestNamedZonesAvailableWithoutSystemTZData},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/cmd/scrumboy"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

