
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/projectsettings"


)

var tests = []testing.InternalTest{

	{"TestPrepareRequiresActorAndManageAuth", _test.TestPrepareRequiresActorAndManageAuth},

	{"TestPatchPublishesOnceAfterSuccessfulMutation", _test.TestPatchPublishesOnceAfterSuccessfulMutation},

	{"TestPatchDoesNotPublishWhenStoreFails", _test.TestPatchDoesNotPublishWhenStoreFails},

	{"TestPatchAgendaOnTemporaryBoardFailsClosed", _test.TestPatchAgendaOnTemporaryBoardFailsClosed},

	{"TestPatchSprintOnlyAllowsTemporaryBoard", _test.TestPatchSprintOnlyAllowsTemporaryBoard},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/projectsettings"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

