
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/mailer"


)

var tests = []testing.InternalTest{

	{"TestSend_STARTTLS_NoAuth", _test.TestSend_STARTTLS_NoAuth},

	{"TestSend_STARTTLS_WithAuth", _test.TestSend_STARTTLS_WithAuth},

	{"TestSend_AuthFailure", _test.TestSend_AuthFailure},

	{"TestSend_ImplicitTLS", _test.TestSend_ImplicitTLS},

	{"TestSend_NoneMode_Plaintext", _test.TestSend_NoneMode_Plaintext},

	{"TestSend_Debug_LogsAttemptWithoutCredentialsBodyOrRecipient", _test.TestSend_Debug_LogsAttemptWithoutCredentialsBodyOrRecipient},

	{"TestSend_Debug_Disabled_LogsNothing", _test.TestSend_Debug_Disabled_LogsNothing},

	{"TestSend_DialFailure", _test.TestSend_DialFailure},

	{"TestSend_RCPTRejected", _test.TestSend_RCPTRejected},

	{"TestSend_STARTTLSRequiredButUnsupported", _test.TestSend_STARTTLSRequiredButUnsupported},

	{"TestNew_NormalizesTLSMode", _test.TestNew_NormalizesTLSMode},

	{"TestSend_UnknownTLSMode_DoesNotUsePlaintext", _test.TestSend_UnknownTLSMode_DoesNotUsePlaintext},

	{"TestSend_HeaderInjectionRejected", _test.TestSend_HeaderInjectionRejected},

	{"TestSend_InvalidFromRejected", _test.TestSend_InvalidFromRejected},

	{"TestParseFrom", _test.TestParseFrom},

	{"TestValidateFrom", _test.TestValidateFrom},

	{"TestSend_QUITFailureAfterDATA_StillSucceeds", _test.TestSend_QUITFailureAfterDATA_StillSucceeds},

	{"TestSend_StallsAfterGreeting_ReturnsWithinTimeout", _test.TestSend_StallsAfterGreeting_ReturnsWithinTimeout},

	{"TestIsPermanent", _test.TestIsPermanent},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/mailer"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

