
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/oauth"


)

var tests = []testing.InternalTest{

	{"TestVerifyPKCE_S256Match", _test.TestVerifyPKCE_S256Match},

	{"TestVerifyPKCE_S256Mismatch", _test.TestVerifyPKCE_S256Mismatch},

	{"TestVerifyPKCE_EmptyValues", _test.TestVerifyPKCE_EmptyValues},

	{"TestVerifyPKCE_PlainMethodRejected", _test.TestVerifyPKCE_PlainMethodRejected},

	{"TestVerifyPKCE_UnknownMethodRejected", _test.TestVerifyPKCE_UnknownMethodRejected},

	{"TestGenerateClientID", _test.TestGenerateClientID},

	{"TestGenerateOpaqueSecret", _test.TestGenerateOpaqueSecret},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/oauth"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

