
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/internal/application/board"


)

var tests = []testing.InternalTest{

	{"TestLaneServiceRead_DelegatesExactlyAndNamesResult", _test.TestLaneServiceRead_DelegatesExactlyAndNamesResult},

	{"TestLaneServiceRead_ReturnsStoreErrorUnchanged", _test.TestLaneServiceRead_ReturnsStoreErrorUnchanged},

	{"TestMCPBoardReadCursorValidationOrder", _test.TestMCPBoardReadCursorValidationOrder},

	{"TestMCPBoardReadCursorSentinelsAndContinuation", _test.TestMCPBoardReadCursorSentinelsAndContinuation},

	{"TestMCPBoardReadIndependentInputCursors", _test.TestMCPBoardReadIndependentInputCursors},

	{"TestMCPBoardReadEmptyCursorUsesFirstPageBoundary", _test.TestMCPBoardReadEmptyCursorUsesFirstPageBoundary},

	{"TestMCPBoardReadNextCursorRequiresMoreAndItems", _test.TestMCPBoardReadNextCursorRequiresMoreAndItems},

	{"TestMCPBoardReadPrepareBindsContextAndAccess", _test.TestMCPBoardReadPrepareBindsContextAndAccess},

	{"TestMCPBoardReadSuccessfulOrchestration", _test.TestMCPBoardReadSuccessfulOrchestration},

	{"TestMCPBoardReadColumnKeyFilter", _test.TestMCPBoardReadColumnKeyFilter},

	{"TestMCPBoardReadSprintSemantics", _test.TestMCPBoardReadSprintSemantics},

	{"TestMCPBoardReadDisabledSprintProjection", _test.TestMCPBoardReadDisabledSprintProjection},

	{"TestMCPBoardReadFailureShortCircuiting", _test.TestMCPBoardReadFailureShortCircuiting},

	{"TestMCPBoardReadActivityRefreshFailureIsBestEffortAndReported", _test.TestMCPBoardReadActivityRefreshFailureIsBestEffortAndReported},

	{"TestPreparedSlugRead_ReadInitialDelegatesToExistingService", _test.TestPreparedSlugRead_ReadInitialDelegatesToExistingService},

	{"TestPreparedSlugRead_ReadLaneDelegatesToExistingService", _test.TestPreparedSlugRead_ReadLaneDelegatesToExistingService},

	{"TestReadServicePrepareLegacy_DelegatesAccessExactly", _test.TestReadServicePrepareLegacy_DelegatesAccessExactly},

	{"TestReadServicePrepareLegacy_ReturnsAccessErrorUnchanged", _test.TestReadServicePrepareLegacy_ReturnsAccessErrorUnchanged},

	{"TestPreparedLegacyRead_DelegatesExactlyAndNamesResult", _test.TestPreparedLegacyRead_DelegatesExactlyAndNamesResult},

	{"TestPreparedLegacyRead_RejectsSprintFilterWhenDisabledAfterAccess", _test.TestPreparedLegacyRead_RejectsSprintFilterWhenDisabledAfterAccess},

	{"TestPreparedLegacyRead_ObservesCancellationAfterPreparation", _test.TestPreparedLegacyRead_ObservesCancellationAfterPreparation},

	{"TestPreparedLegacyRead_ReturnsStoreErrorUnchanged", _test.TestPreparedLegacyRead_ReturnsStoreErrorUnchanged},

	{"TestServiceReadInitial_DelegatesExactlyAndNamesResult", _test.TestServiceReadInitial_DelegatesExactlyAndNamesResult},

	{"TestServiceReadInitial_ReturnsPriorityReadErrorUnchanged", _test.TestServiceReadInitial_ReturnsPriorityReadErrorUnchanged},

	{"TestServiceReadInitial_ReturnsStoreErrorUnchanged", _test.TestServiceReadInitial_ReturnsStoreErrorUnchanged},

	{"TestReadServicePrepareSlugRead_DelegatesAccessExactly", _test.TestReadServicePrepareSlugRead_DelegatesAccessExactly},

	{"TestReadServicePrepareSlugRead_ReturnsAccessErrorUnchanged", _test.TestReadServicePrepareSlugRead_ReturnsAccessErrorUnchanged},

	{"TestPreparedSlugRead_HasSprintsUsesBoundContextAndProject", _test.TestPreparedSlugRead_HasSprintsUsesBoundContextAndProject},

	{"TestPreparedSlugRead_HasSprintsReturnsStoreErrorUnchanged", _test.TestPreparedSlugRead_HasSprintsReturnsStoreErrorUnchanged},

	{"TestPreparedSlugRead_HasSprintsReturnsFalseWhenCapabilityDisabled", _test.TestPreparedSlugRead_HasSprintsReturnsFalseWhenCapabilityDisabled},

	{"TestPreparedSlugRead_ReadInitialDelegatesExactly", _test.TestPreparedSlugRead_ReadInitialDelegatesExactly},

	{"TestPreparedSlugRead_ReadInitialReturnsStoreErrorUnchanged", _test.TestPreparedSlugRead_ReadInitialReturnsStoreErrorUnchanged},

	{"TestPreparedSlugRead_ReadLaneDelegatesExactly", _test.TestPreparedSlugRead_ReadLaneDelegatesExactly},

	{"TestPreparedSlugRead_ReadLaneReturnsStoreErrorUnchanged", _test.TestPreparedSlugRead_ReadLaneReturnsStoreErrorUnchanged},

	{"TestPreparedSlugRead_ObservesCancellationAfterPreparation", _test.TestPreparedSlugRead_ObservesCancellationAfterPreparation},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/internal/application/board"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

