
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "scrumboy/cmd/tagrecover"


)

var tests = []testing.InternalTest{

	{"TestRunReportsRecoverySummaryAndTags", _test.TestRunReportsRecoverySummaryAndTags},

	{"TestRunHandlesNoTagsOrTodos", _test.TestRunHandlesNoTagsOrTodos},

	{"TestRunReturnsCountTodosError", _test.TestRunReturnsCountTodosError},

	{"TestRunReturnsMissingTagsError", _test.TestRunReturnsMissingTagsError},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "scrumboy"
	testdeps.ImportPath = "scrumboy/cmd/tagrecover"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

